// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/common/audience_insights_attribute.proto

package common

import (
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An audience attribute, with metadata about it, returned in response to a
// search.
type AudienceInsightsAttributeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the attribute.
	Dimension enums.AudienceInsightsDimensionEnum_AudienceInsightsDimension `protobuf:"varint,1,opt,name=dimension,proto3,enum=google.ads.googleads.v22.enums.AudienceInsightsDimensionEnum_AudienceInsightsDimension" json:"dimension,omitempty"`
	// The attribute itself.
	Attribute *AudienceInsightsAttribute `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	// The human-readable name of the attribute.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// A string that supplements the display_name to identify the attribute.
	// If the dimension is TOPIC, this is a brief description of the
	// Knowledge Graph entity, such as "American singer-songwriter".
	// If the dimension is CATEGORY, this is the complete path to the category in
	// The Product & Service taxonomy, for example
	// "/Apparel/Clothing/Outerwear".
	DisplayInfo string `protobuf:"bytes,4,opt,name=display_info,json=displayInfo,proto3" json:"display_info,omitempty"`
	// An estimate of the number of reachable YouTube users matching this
	// attribute in the requested location, or zero if that information is not
	// available for this attribute. This field is not populated in every
	// response.
	PotentialYoutubeReach int64 `protobuf:"varint,8,opt,name=potential_youtube_reach,json=potentialYoutubeReach,proto3" json:"potential_youtube_reach,omitempty"`
	// The share of subscribers within this attribute, between and including 0 and
	// 1. This field is not populated in every response.
	SubscriberShare float64 `protobuf:"fixed64,9,opt,name=subscriber_share,json=subscriberShare,proto3" json:"subscriber_share,omitempty"`
	// The share of viewers within this attribute, between and including 0 and
	// 1. This field is not populated in every response.
	ViewerShare float64 `protobuf:"fixed64,13,opt,name=viewer_share,json=viewerShare,proto3" json:"viewer_share,omitempty"`
	// Metadata specific to the dimension of this attribute.
	//
	// Types that are valid to be assigned to DimensionMetadata:
	//
	//	*AudienceInsightsAttributeMetadata_YoutubeChannelMetadata
	//	*AudienceInsightsAttributeMetadata_YoutubeVideoMetadata
	//	*AudienceInsightsAttributeMetadata_LineupAttributeMetadata
	//	*AudienceInsightsAttributeMetadata_LocationAttributeMetadata
	//	*AudienceInsightsAttributeMetadata_UserInterestAttributeMetadata
	//	*AudienceInsightsAttributeMetadata_KnowledgeGraphAttributeMetadata
	//	*AudienceInsightsAttributeMetadata_UserListAttributeMetadata
	DimensionMetadata isAudienceInsightsAttributeMetadata_DimensionMetadata `protobuf_oneof:"dimension_metadata"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AudienceInsightsAttributeMetadata) Reset() {
	*x = AudienceInsightsAttributeMetadata{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudienceInsightsAttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudienceInsightsAttributeMetadata) ProtoMessage() {}

func (x *AudienceInsightsAttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceInsightsAttributeMetadata.ProtoReflect.Descriptor instead.
func (*AudienceInsightsAttributeMetadata) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{0}
}

func (x *AudienceInsightsAttributeMetadata) GetDimension() enums.AudienceInsightsDimensionEnum_AudienceInsightsDimension {
	if x != nil {
		return x.Dimension
	}
	return enums.AudienceInsightsDimensionEnum_AudienceInsightsDimension(0)
}

func (x *AudienceInsightsAttributeMetadata) GetAttribute() *AudienceInsightsAttribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *AudienceInsightsAttributeMetadata) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AudienceInsightsAttributeMetadata) GetDisplayInfo() string {
	if x != nil {
		return x.DisplayInfo
	}
	return ""
}

func (x *AudienceInsightsAttributeMetadata) GetPotentialYoutubeReach() int64 {
	if x != nil {
		return x.PotentialYoutubeReach
	}
	return 0
}

func (x *AudienceInsightsAttributeMetadata) GetSubscriberShare() float64 {
	if x != nil {
		return x.SubscriberShare
	}
	return 0
}

func (x *AudienceInsightsAttributeMetadata) GetViewerShare() float64 {
	if x != nil {
		return x.ViewerShare
	}
	return 0
}

func (x *AudienceInsightsAttributeMetadata) GetDimensionMetadata() isAudienceInsightsAttributeMetadata_DimensionMetadata {
	if x != nil {
		return x.DimensionMetadata
	}
	return nil
}

func (x *AudienceInsightsAttributeMetadata) GetYoutubeChannelMetadata() *YouTubeChannelAttributeMetadata {
	if x != nil {
		if x, ok := x.DimensionMetadata.(*AudienceInsightsAttributeMetadata_YoutubeChannelMetadata); ok {
			return x.YoutubeChannelMetadata
		}
	}
	return nil
}

func (x *AudienceInsightsAttributeMetadata) GetYoutubeVideoMetadata() *YouTubeVideoAttributeMetadata {
	if x != nil {
		if x, ok := x.DimensionMetadata.(*AudienceInsightsAttributeMetadata_YoutubeVideoMetadata); ok {
			return x.YoutubeVideoMetadata
		}
	}
	return nil
}

func (x *AudienceInsightsAttributeMetadata) GetLineupAttributeMetadata() *LineupAttributeMetadata {
	if x != nil {
		if x, ok := x.DimensionMetadata.(*AudienceInsightsAttributeMetadata_LineupAttributeMetadata); ok {
			return x.LineupAttributeMetadata
		}
	}
	return nil
}

func (x *AudienceInsightsAttributeMetadata) GetLocationAttributeMetadata() *LocationAttributeMetadata {
	if x != nil {
		if x, ok := x.DimensionMetadata.(*AudienceInsightsAttributeMetadata_LocationAttributeMetadata); ok {
			return x.LocationAttributeMetadata
		}
	}
	return nil
}

func (x *AudienceInsightsAttributeMetadata) GetUserInterestAttributeMetadata() *UserInterestAttributeMetadata {
	if x != nil {
		if x, ok := x.DimensionMetadata.(*AudienceInsightsAttributeMetadata_UserInterestAttributeMetadata); ok {
			return x.UserInterestAttributeMetadata
		}
	}
	return nil
}

func (x *AudienceInsightsAttributeMetadata) GetKnowledgeGraphAttributeMetadata() *KnowledgeGraphAttributeMetadata {
	if x != nil {
		if x, ok := x.DimensionMetadata.(*AudienceInsightsAttributeMetadata_KnowledgeGraphAttributeMetadata); ok {
			return x.KnowledgeGraphAttributeMetadata
		}
	}
	return nil
}

func (x *AudienceInsightsAttributeMetadata) GetUserListAttributeMetadata() *UserListAttributeMetadata {
	if x != nil {
		if x, ok := x.DimensionMetadata.(*AudienceInsightsAttributeMetadata_UserListAttributeMetadata); ok {
			return x.UserListAttributeMetadata
		}
	}
	return nil
}

type isAudienceInsightsAttributeMetadata_DimensionMetadata interface {
	isAudienceInsightsAttributeMetadata_DimensionMetadata()
}

type AudienceInsightsAttributeMetadata_YoutubeChannelMetadata struct {
	// Special metadata for a YouTube channel.
	YoutubeChannelMetadata *YouTubeChannelAttributeMetadata `protobuf:"bytes,5,opt,name=youtube_channel_metadata,json=youtubeChannelMetadata,proto3,oneof"`
}

type AudienceInsightsAttributeMetadata_YoutubeVideoMetadata struct {
	// Special metadata for a YouTube video.
	YoutubeVideoMetadata *YouTubeVideoAttributeMetadata `protobuf:"bytes,10,opt,name=youtube_video_metadata,json=youtubeVideoMetadata,proto3,oneof"`
}

type AudienceInsightsAttributeMetadata_LineupAttributeMetadata struct {
	// Special metadata for a YouTube Lineup.
	LineupAttributeMetadata *LineupAttributeMetadata `protobuf:"bytes,14,opt,name=lineup_attribute_metadata,json=lineupAttributeMetadata,proto3,oneof"`
}

type AudienceInsightsAttributeMetadata_LocationAttributeMetadata struct {
	// Special metadata for a Location.
	LocationAttributeMetadata *LocationAttributeMetadata `protobuf:"bytes,7,opt,name=location_attribute_metadata,json=locationAttributeMetadata,proto3,oneof"`
}

type AudienceInsightsAttributeMetadata_UserInterestAttributeMetadata struct {
	// Special metadata for a User Interest.
	UserInterestAttributeMetadata *UserInterestAttributeMetadata `protobuf:"bytes,11,opt,name=user_interest_attribute_metadata,json=userInterestAttributeMetadata,proto3,oneof"`
}

type AudienceInsightsAttributeMetadata_KnowledgeGraphAttributeMetadata struct {
	// Special metadata for a Knowledge Graph Entity.
	KnowledgeGraphAttributeMetadata *KnowledgeGraphAttributeMetadata `protobuf:"bytes,12,opt,name=knowledge_graph_attribute_metadata,json=knowledgeGraphAttributeMetadata,proto3,oneof"`
}

type AudienceInsightsAttributeMetadata_UserListAttributeMetadata struct {
	// Special metadata for a User List.
	UserListAttributeMetadata *UserListAttributeMetadata `protobuf:"bytes,15,opt,name=user_list_attribute_metadata,json=userListAttributeMetadata,proto3,oneof"`
}

func (*AudienceInsightsAttributeMetadata_YoutubeChannelMetadata) isAudienceInsightsAttributeMetadata_DimensionMetadata() {
}

func (*AudienceInsightsAttributeMetadata_YoutubeVideoMetadata) isAudienceInsightsAttributeMetadata_DimensionMetadata() {
}

func (*AudienceInsightsAttributeMetadata_LineupAttributeMetadata) isAudienceInsightsAttributeMetadata_DimensionMetadata() {
}

func (*AudienceInsightsAttributeMetadata_LocationAttributeMetadata) isAudienceInsightsAttributeMetadata_DimensionMetadata() {
}

func (*AudienceInsightsAttributeMetadata_UserInterestAttributeMetadata) isAudienceInsightsAttributeMetadata_DimensionMetadata() {
}

func (*AudienceInsightsAttributeMetadata_KnowledgeGraphAttributeMetadata) isAudienceInsightsAttributeMetadata_DimensionMetadata() {
}

func (*AudienceInsightsAttributeMetadata_UserListAttributeMetadata) isAudienceInsightsAttributeMetadata_DimensionMetadata() {
}

// An audience attribute that can be used to request insights about the
// audience. Valid inputs for these fields are available from
// [AudienceInsightsService.ListAudienceInsightsAttributes][].
type AudienceInsightsAttribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An audience attribute.
	//
	// Types that are valid to be assigned to Attribute:
	//
	//	*AudienceInsightsAttribute_AgeRange
	//	*AudienceInsightsAttribute_Gender
	//	*AudienceInsightsAttribute_Location
	//	*AudienceInsightsAttribute_UserInterest
	//	*AudienceInsightsAttribute_Entity
	//	*AudienceInsightsAttribute_Category
	//	*AudienceInsightsAttribute_Lineup
	//	*AudienceInsightsAttribute_ParentalStatus
	//	*AudienceInsightsAttribute_IncomeRange
	//	*AudienceInsightsAttribute_YoutubeChannel
	//	*AudienceInsightsAttribute_YoutubeVideo
	//	*AudienceInsightsAttribute_Device
	//	*AudienceInsightsAttribute_UserList
	Attribute     isAudienceInsightsAttribute_Attribute `protobuf_oneof:"attribute"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudienceInsightsAttribute) Reset() {
	*x = AudienceInsightsAttribute{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudienceInsightsAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudienceInsightsAttribute) ProtoMessage() {}

func (x *AudienceInsightsAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceInsightsAttribute.ProtoReflect.Descriptor instead.
func (*AudienceInsightsAttribute) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{1}
}

func (x *AudienceInsightsAttribute) GetAttribute() isAudienceInsightsAttribute_Attribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetAgeRange() *AgeRangeInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_AgeRange); ok {
			return x.AgeRange
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetGender() *GenderInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_Gender); ok {
			return x.Gender
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetLocation() *LocationInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetUserInterest() *UserInterestInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_UserInterest); ok {
			return x.UserInterest
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetEntity() *AudienceInsightsEntity {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_Entity); ok {
			return x.Entity
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetCategory() *AudienceInsightsCategory {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_Category); ok {
			return x.Category
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetLineup() *AudienceInsightsLineup {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_Lineup); ok {
			return x.Lineup
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetParentalStatus() *ParentalStatusInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_ParentalStatus); ok {
			return x.ParentalStatus
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetIncomeRange() *IncomeRangeInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_IncomeRange); ok {
			return x.IncomeRange
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetYoutubeChannel() *YouTubeChannelInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_YoutubeChannel); ok {
			return x.YoutubeChannel
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetYoutubeVideo() *YouTubeVideoInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_YoutubeVideo); ok {
			return x.YoutubeVideo
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetDevice() *DeviceInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_Device); ok {
			return x.Device
		}
	}
	return nil
}

func (x *AudienceInsightsAttribute) GetUserList() *UserListInfo {
	if x != nil {
		if x, ok := x.Attribute.(*AudienceInsightsAttribute_UserList); ok {
			return x.UserList
		}
	}
	return nil
}

type isAudienceInsightsAttribute_Attribute interface {
	isAudienceInsightsAttribute_Attribute()
}

type AudienceInsightsAttribute_AgeRange struct {
	// An audience attribute defined by an age range.
	AgeRange *AgeRangeInfo `protobuf:"bytes,1,opt,name=age_range,json=ageRange,proto3,oneof"`
}

type AudienceInsightsAttribute_Gender struct {
	// An audience attribute defined by a gender.
	Gender *GenderInfo `protobuf:"bytes,2,opt,name=gender,proto3,oneof"`
}

type AudienceInsightsAttribute_Location struct {
	// An audience attribute defined by a geographic location.
	Location *LocationInfo `protobuf:"bytes,3,opt,name=location,proto3,oneof"`
}

type AudienceInsightsAttribute_UserInterest struct {
	// An Affinity or In-Market audience.
	UserInterest *UserInterestInfo `protobuf:"bytes,4,opt,name=user_interest,json=userInterest,proto3,oneof"`
}

type AudienceInsightsAttribute_Entity struct {
	// An audience attribute defined by interest in a topic represented by a
	// Knowledge Graph entity.
	Entity *AudienceInsightsEntity `protobuf:"bytes,5,opt,name=entity,proto3,oneof"`
}

type AudienceInsightsAttribute_Category struct {
	// An audience attribute defined by interest in a Product & Service
	// category.
	Category *AudienceInsightsCategory `protobuf:"bytes,6,opt,name=category,proto3,oneof"`
}

type AudienceInsightsAttribute_Lineup struct {
	// A YouTube Lineup.
	Lineup *AudienceInsightsLineup `protobuf:"bytes,13,opt,name=lineup,proto3,oneof"`
}

type AudienceInsightsAttribute_ParentalStatus struct {
	// A Parental Status value (parent, or not a parent).
	ParentalStatus *ParentalStatusInfo `protobuf:"bytes,8,opt,name=parental_status,json=parentalStatus,proto3,oneof"`
}

type AudienceInsightsAttribute_IncomeRange struct {
	// A household income percentile range.
	IncomeRange *IncomeRangeInfo `protobuf:"bytes,9,opt,name=income_range,json=incomeRange,proto3,oneof"`
}

type AudienceInsightsAttribute_YoutubeChannel struct {
	// A YouTube channel.
	YoutubeChannel *YouTubeChannelInfo `protobuf:"bytes,10,opt,name=youtube_channel,json=youtubeChannel,proto3,oneof"`
}

type AudienceInsightsAttribute_YoutubeVideo struct {
	// A YouTube video.
	YoutubeVideo *YouTubeVideoInfo `protobuf:"bytes,11,opt,name=youtube_video,json=youtubeVideo,proto3,oneof"`
}

type AudienceInsightsAttribute_Device struct {
	// A device type. (Mobile, Desktop, Tablet)
	Device *DeviceInfo `protobuf:"bytes,12,opt,name=device,proto3,oneof"`
}

type AudienceInsightsAttribute_UserList struct {
	// A User List.
	UserList *UserListInfo `protobuf:"bytes,14,opt,name=user_list,json=userList,proto3,oneof"`
}

func (*AudienceInsightsAttribute_AgeRange) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_Gender) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_Location) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_UserInterest) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_Entity) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_Category) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_Lineup) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_ParentalStatus) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_IncomeRange) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_YoutubeChannel) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_YoutubeVideo) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_Device) isAudienceInsightsAttribute_Attribute() {}

func (*AudienceInsightsAttribute_UserList) isAudienceInsightsAttribute_Attribute() {}

// A Knowledge Graph entity, represented by its machine id.
type AudienceInsightsEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The machine ID (mid) of the Knowledge Graph entity.
	KnowledgeGraphMachineId string `protobuf:"bytes,1,opt,name=knowledge_graph_machine_id,json=knowledgeGraphMachineId,proto3" json:"knowledge_graph_machine_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AudienceInsightsEntity) Reset() {
	*x = AudienceInsightsEntity{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudienceInsightsEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudienceInsightsEntity) ProtoMessage() {}

func (x *AudienceInsightsEntity) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceInsightsEntity.ProtoReflect.Descriptor instead.
func (*AudienceInsightsEntity) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{2}
}

func (x *AudienceInsightsEntity) GetKnowledgeGraphMachineId() string {
	if x != nil {
		return x.KnowledgeGraphMachineId
	}
	return ""
}

// A Product and Service category.
type AudienceInsightsCategory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The criterion ID of the category.
	CategoryId    string `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudienceInsightsCategory) Reset() {
	*x = AudienceInsightsCategory{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudienceInsightsCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudienceInsightsCategory) ProtoMessage() {}

func (x *AudienceInsightsCategory) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceInsightsCategory.ProtoReflect.Descriptor instead.
func (*AudienceInsightsCategory) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{3}
}

func (x *AudienceInsightsCategory) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

// A YouTube Lineup.
type AudienceInsightsLineup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The numeric ID of the lineup.
	LineupId      string `protobuf:"bytes,1,opt,name=lineup_id,json=lineupId,proto3" json:"lineup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudienceInsightsLineup) Reset() {
	*x = AudienceInsightsLineup{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudienceInsightsLineup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudienceInsightsLineup) ProtoMessage() {}

func (x *AudienceInsightsLineup) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceInsightsLineup.ProtoReflect.Descriptor instead.
func (*AudienceInsightsLineup) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{4}
}

func (x *AudienceInsightsLineup) GetLineupId() string {
	if x != nil {
		return x.LineupId
	}
	return ""
}

// Metadata associated with a YouTube channel attribute.
type YouTubeChannelAttributeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The approximate number of subscribers to the YouTube channel.
	SubscriberCount int64 `protobuf:"varint,1,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *YouTubeChannelAttributeMetadata) Reset() {
	*x = YouTubeChannelAttributeMetadata{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YouTubeChannelAttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YouTubeChannelAttributeMetadata) ProtoMessage() {}

func (x *YouTubeChannelAttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YouTubeChannelAttributeMetadata.ProtoReflect.Descriptor instead.
func (*YouTubeChannelAttributeMetadata) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{5}
}

func (x *YouTubeChannelAttributeMetadata) GetSubscriberCount() int64 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

// Metadata for a YouTube video attribute.
type YouTubeVideoAttributeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL of the video thumbnail, prefixed by "https://img.youtube.com/".
	ThumbnailUrl string `protobuf:"bytes,1,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	// The URL of the video, prefixed by "https://www.youtube.com/".
	VideoUrl string `protobuf:"bytes,2,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	// The total number of views.
	ViewsCount int64 `protobuf:"varint,3,opt,name=views_count,json=viewsCount,proto3" json:"views_count,omitempty"`
	// The total number of likes.
	LikesCount int64 `protobuf:"varint,4,opt,name=likes_count,json=likesCount,proto3" json:"likes_count,omitempty"`
	// The total number of comments.
	CommentsCount int64 `protobuf:"varint,5,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	// The properties of this video (such as shorts, live stream).
	VideoProperties []enums.YouTubeVideoPropertyEnum_YouTubeVideoProperty `protobuf:"varint,6,rep,packed,name=video_properties,json=videoProperties,proto3,enum=google.ads.googleads.v22.enums.YouTubeVideoPropertyEnum_YouTubeVideoProperty" json:"video_properties,omitempty"`
	// The date that the video was created. Formatted as "yyyy-mm-dd".
	PublishDate   string `protobuf:"bytes,7,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YouTubeVideoAttributeMetadata) Reset() {
	*x = YouTubeVideoAttributeMetadata{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YouTubeVideoAttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YouTubeVideoAttributeMetadata) ProtoMessage() {}

func (x *YouTubeVideoAttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YouTubeVideoAttributeMetadata.ProtoReflect.Descriptor instead.
func (*YouTubeVideoAttributeMetadata) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{6}
}

func (x *YouTubeVideoAttributeMetadata) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *YouTubeVideoAttributeMetadata) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *YouTubeVideoAttributeMetadata) GetViewsCount() int64 {
	if x != nil {
		return x.ViewsCount
	}
	return 0
}

func (x *YouTubeVideoAttributeMetadata) GetLikesCount() int64 {
	if x != nil {
		return x.LikesCount
	}
	return 0
}

func (x *YouTubeVideoAttributeMetadata) GetCommentsCount() int64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *YouTubeVideoAttributeMetadata) GetVideoProperties() []enums.YouTubeVideoPropertyEnum_YouTubeVideoProperty {
	if x != nil {
		return x.VideoProperties
	}
	return nil
}

func (x *YouTubeVideoAttributeMetadata) GetPublishDate() string {
	if x != nil {
		return x.PublishDate
	}
	return ""
}

// Metadata associated with a Lineup attribute.
type LineupAttributeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The national market associated with the lineup.
	InventoryCountry *LocationInfo `protobuf:"bytes,1,opt,name=inventory_country,json=inventoryCountry,proto3" json:"inventory_country,omitempty"`
	// The median number of impressions per month on this lineup.
	MedianMonthlyInventory *int64 `protobuf:"varint,2,opt,name=median_monthly_inventory,json=medianMonthlyInventory,proto3,oneof" json:"median_monthly_inventory,omitempty"`
	// The lower end of a range containing the number of channels in the lineup.
	ChannelCountLowerBound *int64 `protobuf:"varint,3,opt,name=channel_count_lower_bound,json=channelCountLowerBound,proto3,oneof" json:"channel_count_lower_bound,omitempty"`
	// The upper end of a range containing the number of channels in the lineup.
	ChannelCountUpperBound *int64 `protobuf:"varint,4,opt,name=channel_count_upper_bound,json=channelCountUpperBound,proto3,oneof" json:"channel_count_upper_bound,omitempty"`
	// Examples of channels that are included in the lineup.
	SampleChannels []*LineupAttributeMetadata_SampleChannel `protobuf:"bytes,5,rep,name=sample_channels,json=sampleChannels,proto3" json:"sample_channels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LineupAttributeMetadata) Reset() {
	*x = LineupAttributeMetadata{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineupAttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineupAttributeMetadata) ProtoMessage() {}

func (x *LineupAttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineupAttributeMetadata.ProtoReflect.Descriptor instead.
func (*LineupAttributeMetadata) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{7}
}

func (x *LineupAttributeMetadata) GetInventoryCountry() *LocationInfo {
	if x != nil {
		return x.InventoryCountry
	}
	return nil
}

func (x *LineupAttributeMetadata) GetMedianMonthlyInventory() int64 {
	if x != nil && x.MedianMonthlyInventory != nil {
		return *x.MedianMonthlyInventory
	}
	return 0
}

func (x *LineupAttributeMetadata) GetChannelCountLowerBound() int64 {
	if x != nil && x.ChannelCountLowerBound != nil {
		return *x.ChannelCountLowerBound
	}
	return 0
}

func (x *LineupAttributeMetadata) GetChannelCountUpperBound() int64 {
	if x != nil && x.ChannelCountUpperBound != nil {
		return *x.ChannelCountUpperBound
	}
	return 0
}

func (x *LineupAttributeMetadata) GetSampleChannels() []*LineupAttributeMetadata_SampleChannel {
	if x != nil {
		return x.SampleChannels
	}
	return nil
}

// Metadata associated with a Location attribute.
type LocationAttributeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The country location that this attribute’s sub country location is located
	// in.
	CountryLocation *LocationInfo `protobuf:"bytes,1,opt,name=country_location,json=countryLocation,proto3" json:"country_location,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LocationAttributeMetadata) Reset() {
	*x = LocationAttributeMetadata{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationAttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationAttributeMetadata) ProtoMessage() {}

func (x *LocationAttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationAttributeMetadata.ProtoReflect.Descriptor instead.
func (*LocationAttributeMetadata) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{8}
}

func (x *LocationAttributeMetadata) GetCountryLocation() *LocationInfo {
	if x != nil {
		return x.CountryLocation
	}
	return nil
}

// Metadata associated with a User Interest attribute.
type UserInterestAttributeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// English language text description of the user interest category (200
	// characters max).
	UserInterestDescription string `protobuf:"bytes,1,opt,name=user_interest_description,json=userInterestDescription,proto3" json:"user_interest_description,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UserInterestAttributeMetadata) Reset() {
	*x = UserInterestAttributeMetadata{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInterestAttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInterestAttributeMetadata) ProtoMessage() {}

func (x *UserInterestAttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInterestAttributeMetadata.ProtoReflect.Descriptor instead.
func (*UserInterestAttributeMetadata) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{9}
}

func (x *UserInterestAttributeMetadata) GetUserInterestDescription() string {
	if x != nil {
		return x.UserInterestDescription
	}
	return ""
}

// Metadata associated with a Knowledge Graph Entity attribute.
type KnowledgeGraphAttributeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The capabilities of the entity used in [ContentCreatorInsightsService][].
	EntityCapabilities []enums.InsightsKnowledgeGraphEntityCapabilitiesEnum_InsightsKnowledgeGraphEntityCapabilities `protobuf:"varint,1,rep,packed,name=entity_capabilities,json=entityCapabilities,proto3,enum=google.ads.googleads.v22.enums.InsightsKnowledgeGraphEntityCapabilitiesEnum_InsightsKnowledgeGraphEntityCapabilities" json:"entity_capabilities,omitempty"`
	// A list of CATEGORY attributes related to this entity.
	RelatedCategories []*AudienceInsightsAttributeMetadata `protobuf:"bytes,2,rep,name=related_categories,json=relatedCategories,proto3" json:"related_categories,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KnowledgeGraphAttributeMetadata) Reset() {
	*x = KnowledgeGraphAttributeMetadata{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeGraphAttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeGraphAttributeMetadata) ProtoMessage() {}

func (x *KnowledgeGraphAttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeGraphAttributeMetadata.ProtoReflect.Descriptor instead.
func (*KnowledgeGraphAttributeMetadata) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{10}
}

func (x *KnowledgeGraphAttributeMetadata) GetEntityCapabilities() []enums.InsightsKnowledgeGraphEntityCapabilitiesEnum_InsightsKnowledgeGraphEntityCapabilities {
	if x != nil {
		return x.EntityCapabilities
	}
	return nil
}

func (x *KnowledgeGraphAttributeMetadata) GetRelatedCategories() []*AudienceInsightsAttributeMetadata {
	if x != nil {
		return x.RelatedCategories
	}
	return nil
}

// Metadata associated with a User List attribute.
type UserListAttributeMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user list type.
	UserListType  enums.UserListTypeEnum_UserListType `protobuf:"varint,1,opt,name=user_list_type,json=userListType,proto3,enum=google.ads.googleads.v22.enums.UserListTypeEnum_UserListType" json:"user_list_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListAttributeMetadata) Reset() {
	*x = UserListAttributeMetadata{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListAttributeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListAttributeMetadata) ProtoMessage() {}

func (x *UserListAttributeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListAttributeMetadata.ProtoReflect.Descriptor instead.
func (*UserListAttributeMetadata) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{11}
}

func (x *UserListAttributeMetadata) GetUserListType() enums.UserListTypeEnum_UserListType {
	if x != nil {
		return x.UserListType
	}
	return enums.UserListTypeEnum_UserListType(0)
}

// A group of audience attributes with metadata, returned in response to a
// search.
type AudienceInsightsAttributeMetadataGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attributes with metadata returned in response to a search.
	Attributes    []*AudienceInsightsAttributeMetadata `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudienceInsightsAttributeMetadataGroup) Reset() {
	*x = AudienceInsightsAttributeMetadataGroup{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudienceInsightsAttributeMetadataGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudienceInsightsAttributeMetadataGroup) ProtoMessage() {}

func (x *AudienceInsightsAttributeMetadataGroup) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudienceInsightsAttributeMetadataGroup.ProtoReflect.Descriptor instead.
func (*AudienceInsightsAttributeMetadataGroup) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{12}
}

func (x *AudienceInsightsAttributeMetadataGroup) GetAttributes() []*AudienceInsightsAttributeMetadata {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// A YouTube channel returned as an example of the content in a lineup.
type LineupAttributeMetadata_SampleChannel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A YouTube channel.
	YoutubeChannel *YouTubeChannelInfo `protobuf:"bytes,1,opt,name=youtube_channel,json=youtubeChannel,proto3" json:"youtube_channel,omitempty"`
	// The name of the sample channel.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Metadata for the sample channel.
	YoutubeChannelMetadata *YouTubeChannelAttributeMetadata `protobuf:"bytes,3,opt,name=youtube_channel_metadata,json=youtubeChannelMetadata,proto3" json:"youtube_channel_metadata,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LineupAttributeMetadata_SampleChannel) Reset() {
	*x = LineupAttributeMetadata_SampleChannel{}
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineupAttributeMetadata_SampleChannel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineupAttributeMetadata_SampleChannel) ProtoMessage() {}

func (x *LineupAttributeMetadata_SampleChannel) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineupAttributeMetadata_SampleChannel.ProtoReflect.Descriptor instead.
func (*LineupAttributeMetadata_SampleChannel) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP(), []int{7, 0}
}

func (x *LineupAttributeMetadata_SampleChannel) GetYoutubeChannel() *YouTubeChannelInfo {
	if x != nil {
		return x.YoutubeChannel
	}
	return nil
}

func (x *LineupAttributeMetadata_SampleChannel) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LineupAttributeMetadata_SampleChannel) GetYoutubeChannelMetadata() *YouTubeChannelAttributeMetadata {
	if x != nil {
		return x.YoutubeChannelMetadata
	}
	return nil
}

var File_google_ads_googleads_v22_common_audience_insights_attribute_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDesc = "" +
	"\n" +
	"Agoogle/ads/googleads/v22/common/audience_insights_attribute.proto\x12\x1fgoogle.ads.googleads.v22.common\x1a.google/ads/googleads/v22/common/criteria.proto\x1a@google/ads/googleads/v22/enums/audience_insights_dimension.proto\x1aQgoogle/ads/googleads/v22/enums/insights_knowledge_graph_entity_capabilities.proto\x1a3google/ads/googleads/v22/enums/user_list_type.proto\x1a;google/ads/googleads/v22/enums/youtube_video_property.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xdf\n" +
	"\n" +
	"!AudienceInsightsAttributeMetadata\x12u\n" +
	"\tdimension\x18\x01 \x01(\x0e2W.google.ads.googleads.v22.enums.AudienceInsightsDimensionEnum.AudienceInsightsDimensionR\tdimension\x12X\n" +
	"\tattribute\x18\x02 \x01(\v2:.google.ads.googleads.v22.common.AudienceInsightsAttributeR\tattribute\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12!\n" +
	"\fdisplay_info\x18\x04 \x01(\tR\vdisplayInfo\x126\n" +
	"\x17potential_youtube_reach\x18\b \x01(\x03R\x15potentialYoutubeReach\x12)\n" +
	"\x10subscriber_share\x18\t \x01(\x01R\x0fsubscriberShare\x12!\n" +
	"\fviewer_share\x18\r \x01(\x01R\vviewerShare\x12|\n" +
	"\x18youtube_channel_metadata\x18\x05 \x01(\v2@.google.ads.googleads.v22.common.YouTubeChannelAttributeMetadataH\x00R\x16youtubeChannelMetadata\x12v\n" +
	"\x16youtube_video_metadata\x18\n" +
	" \x01(\v2>.google.ads.googleads.v22.common.YouTubeVideoAttributeMetadataH\x00R\x14youtubeVideoMetadata\x12v\n" +
	"\x19lineup_attribute_metadata\x18\x0e \x01(\v28.google.ads.googleads.v22.common.LineupAttributeMetadataH\x00R\x17lineupAttributeMetadata\x12|\n" +
	"\x1blocation_attribute_metadata\x18\a \x01(\v2:.google.ads.googleads.v22.common.LocationAttributeMetadataH\x00R\x19locationAttributeMetadata\x12\x89\x01\n" +
	" user_interest_attribute_metadata\x18\v \x01(\v2>.google.ads.googleads.v22.common.UserInterestAttributeMetadataH\x00R\x1duserInterestAttributeMetadata\x12\x8f\x01\n" +
	"\"knowledge_graph_attribute_metadata\x18\f \x01(\v2@.google.ads.googleads.v22.common.KnowledgeGraphAttributeMetadataH\x00R\x1fknowledgeGraphAttributeMetadata\x12}\n" +
	"\x1cuser_list_attribute_metadata\x18\x0f \x01(\v2:.google.ads.googleads.v22.common.UserListAttributeMetadataH\x00R\x19userListAttributeMetadataB\x14\n" +
	"\x12dimension_metadata\"\xe9\b\n" +
	"\x19AudienceInsightsAttribute\x12L\n" +
	"\tage_range\x18\x01 \x01(\v2-.google.ads.googleads.v22.common.AgeRangeInfoH\x00R\bageRange\x12E\n" +
	"\x06gender\x18\x02 \x01(\v2+.google.ads.googleads.v22.common.GenderInfoH\x00R\x06gender\x12K\n" +
	"\blocation\x18\x03 \x01(\v2-.google.ads.googleads.v22.common.LocationInfoH\x00R\blocation\x12X\n" +
	"\ruser_interest\x18\x04 \x01(\v21.google.ads.googleads.v22.common.UserInterestInfoH\x00R\fuserInterest\x12Q\n" +
	"\x06entity\x18\x05 \x01(\v27.google.ads.googleads.v22.common.AudienceInsightsEntityH\x00R\x06entity\x12W\n" +
	"\bcategory\x18\x06 \x01(\v29.google.ads.googleads.v22.common.AudienceInsightsCategoryH\x00R\bcategory\x12Q\n" +
	"\x06lineup\x18\r \x01(\v27.google.ads.googleads.v22.common.AudienceInsightsLineupH\x00R\x06lineup\x12^\n" +
	"\x0fparental_status\x18\b \x01(\v23.google.ads.googleads.v22.common.ParentalStatusInfoH\x00R\x0eparentalStatus\x12U\n" +
	"\fincome_range\x18\t \x01(\v20.google.ads.googleads.v22.common.IncomeRangeInfoH\x00R\vincomeRange\x12^\n" +
	"\x0fyoutube_channel\x18\n" +
	" \x01(\v23.google.ads.googleads.v22.common.YouTubeChannelInfoH\x00R\x0eyoutubeChannel\x12X\n" +
	"\ryoutube_video\x18\v \x01(\v21.google.ads.googleads.v22.common.YouTubeVideoInfoH\x00R\fyoutubeVideo\x12E\n" +
	"\x06device\x18\f \x01(\v2+.google.ads.googleads.v22.common.DeviceInfoH\x00R\x06device\x12L\n" +
	"\tuser_list\x18\x0e \x01(\v2-.google.ads.googleads.v22.common.UserListInfoH\x00R\buserListB\v\n" +
	"\tattribute\"Z\n" +
	"\x16AudienceInsightsEntity\x12@\n" +
	"\x1aknowledge_graph_machine_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x17knowledgeGraphMachineId\"@\n" +
	"\x18AudienceInsightsCategory\x12$\n" +
	"\vcategory_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"categoryId\":\n" +
	"\x16AudienceInsightsLineup\x12 \n" +
	"\tlineup_id\x18\x01 \x01(\tB\x03\xe0A\x02R\blineupId\"L\n" +
	"\x1fYouTubeChannelAttributeMetadata\x12)\n" +
	"\x10subscriber_count\x18\x01 \x01(\x03R\x0fsubscriberCount\"\xe7\x02\n" +
	"\x1dYouTubeVideoAttributeMetadata\x12#\n" +
	"\rthumbnail_url\x18\x01 \x01(\tR\fthumbnailUrl\x12\x1b\n" +
	"\tvideo_url\x18\x02 \x01(\tR\bvideoUrl\x12\x1f\n" +
	"\vviews_count\x18\x03 \x01(\x03R\n" +
	"viewsCount\x12\x1f\n" +
	"\vlikes_count\x18\x04 \x01(\x03R\n" +
	"likesCount\x12%\n" +
	"\x0ecomments_count\x18\x05 \x01(\x03R\rcommentsCount\x12x\n" +
	"\x10video_properties\x18\x06 \x03(\x0e2M.google.ads.googleads.v22.enums.YouTubeVideoPropertyEnum.YouTubeVideoPropertyR\x0fvideoProperties\x12!\n" +
	"\fpublish_date\x18\a \x01(\tR\vpublishDate\"\x8d\x06\n" +
	"\x17LineupAttributeMetadata\x12Z\n" +
	"\x11inventory_country\x18\x01 \x01(\v2-.google.ads.googleads.v22.common.LocationInfoR\x10inventoryCountry\x12=\n" +
	"\x18median_monthly_inventory\x18\x02 \x01(\x03H\x00R\x16medianMonthlyInventory\x88\x01\x01\x12>\n" +
	"\x19channel_count_lower_bound\x18\x03 \x01(\x03H\x01R\x16channelCountLowerBound\x88\x01\x01\x12>\n" +
	"\x19channel_count_upper_bound\x18\x04 \x01(\x03H\x02R\x16channelCountUpperBound\x88\x01\x01\x12o\n" +
	"\x0fsample_channels\x18\x05 \x03(\v2F.google.ads.googleads.v22.common.LineupAttributeMetadata.SampleChannelR\x0esampleChannels\x1a\x8c\x02\n" +
	"\rSampleChannel\x12\\\n" +
	"\x0fyoutube_channel\x18\x01 \x01(\v23.google.ads.googleads.v22.common.YouTubeChannelInfoR\x0eyoutubeChannel\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12z\n" +
	"\x18youtube_channel_metadata\x18\x03 \x01(\v2@.google.ads.googleads.v22.common.YouTubeChannelAttributeMetadataR\x16youtubeChannelMetadataB\x1b\n" +
	"\x19_median_monthly_inventoryB\x1c\n" +
	"\x1a_channel_count_lower_boundB\x1c\n" +
	"\x1a_channel_count_upper_bound\"u\n" +
	"\x19LocationAttributeMetadata\x12X\n" +
	"\x10country_location\x18\x01 \x01(\v2-.google.ads.googleads.v22.common.LocationInfoR\x0fcountryLocation\"[\n" +
	"\x1dUserInterestAttributeMetadata\x12:\n" +
	"\x19user_interest_description\x18\x01 \x01(\tR\x17userInterestDescription\"\xbd\x02\n" +
	"\x1fKnowledgeGraphAttributeMetadata\x12\xa6\x01\n" +
	"\x13entity_capabilities\x18\x01 \x03(\x0e2u.google.ads.googleads.v22.enums.InsightsKnowledgeGraphEntityCapabilitiesEnum.InsightsKnowledgeGraphEntityCapabilitiesR\x12entityCapabilities\x12q\n" +
	"\x12related_categories\x18\x02 \x03(\v2B.google.ads.googleads.v22.common.AudienceInsightsAttributeMetadataR\x11relatedCategories\"\x80\x01\n" +
	"\x19UserListAttributeMetadata\x12c\n" +
	"\x0euser_list_type\x18\x01 \x01(\x0e2=.google.ads.googleads.v22.enums.UserListTypeEnum.UserListTypeR\fuserListType\"\x8c\x01\n" +
	"&AudienceInsightsAttributeMetadataGroup\x12b\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2B.google.ads.googleads.v22.common.AudienceInsightsAttributeMetadataR\n" +
	"attributesB\xfe\x01\n" +
	"#com.google.ads.googleads.v22.commonB\x1eAudienceInsightsAttributeProtoP\x01ZEgithub.com/Optable/google-ads-pb/protogen/common;common\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V22.Common\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V22\\Common\xea\x02#Google::Ads::GoogleAds::V22::Commonb\x06proto3"

var (
	file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDesc), len(file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDescData
}

var file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_google_ads_googleads_v22_common_audience_insights_attribute_proto_goTypes = []any{
	(*AudienceInsightsAttributeMetadata)(nil),                          // 0: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata
	(*AudienceInsightsAttribute)(nil),                                  // 1: google.ads.googleads.v22.common.AudienceInsightsAttribute
	(*AudienceInsightsEntity)(nil),                                     // 2: google.ads.googleads.v22.common.AudienceInsightsEntity
	(*AudienceInsightsCategory)(nil),                                   // 3: google.ads.googleads.v22.common.AudienceInsightsCategory
	(*AudienceInsightsLineup)(nil),                                     // 4: google.ads.googleads.v22.common.AudienceInsightsLineup
	(*YouTubeChannelAttributeMetadata)(nil),                            // 5: google.ads.googleads.v22.common.YouTubeChannelAttributeMetadata
	(*YouTubeVideoAttributeMetadata)(nil),                              // 6: google.ads.googleads.v22.common.YouTubeVideoAttributeMetadata
	(*LineupAttributeMetadata)(nil),                                    // 7: google.ads.googleads.v22.common.LineupAttributeMetadata
	(*LocationAttributeMetadata)(nil),                                  // 8: google.ads.googleads.v22.common.LocationAttributeMetadata
	(*UserInterestAttributeMetadata)(nil),                              // 9: google.ads.googleads.v22.common.UserInterestAttributeMetadata
	(*KnowledgeGraphAttributeMetadata)(nil),                            // 10: google.ads.googleads.v22.common.KnowledgeGraphAttributeMetadata
	(*UserListAttributeMetadata)(nil),                                  // 11: google.ads.googleads.v22.common.UserListAttributeMetadata
	(*AudienceInsightsAttributeMetadataGroup)(nil),                     // 12: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadataGroup
	(*LineupAttributeMetadata_SampleChannel)(nil),                      // 13: google.ads.googleads.v22.common.LineupAttributeMetadata.SampleChannel
	(enums.AudienceInsightsDimensionEnum_AudienceInsightsDimension)(0), // 14: google.ads.googleads.v22.enums.AudienceInsightsDimensionEnum.AudienceInsightsDimension
	(*AgeRangeInfo)(nil),                                               // 15: google.ads.googleads.v22.common.AgeRangeInfo
	(*GenderInfo)(nil),                                                 // 16: google.ads.googleads.v22.common.GenderInfo
	(*LocationInfo)(nil),                                               // 17: google.ads.googleads.v22.common.LocationInfo
	(*UserInterestInfo)(nil),                                           // 18: google.ads.googleads.v22.common.UserInterestInfo
	(*ParentalStatusInfo)(nil),                                         // 19: google.ads.googleads.v22.common.ParentalStatusInfo
	(*IncomeRangeInfo)(nil),                                            // 20: google.ads.googleads.v22.common.IncomeRangeInfo
	(*YouTubeChannelInfo)(nil),                                         // 21: google.ads.googleads.v22.common.YouTubeChannelInfo
	(*YouTubeVideoInfo)(nil),                                           // 22: google.ads.googleads.v22.common.YouTubeVideoInfo
	(*DeviceInfo)(nil),                                                 // 23: google.ads.googleads.v22.common.DeviceInfo
	(*UserListInfo)(nil),                                               // 24: google.ads.googleads.v22.common.UserListInfo
	(enums.YouTubeVideoPropertyEnum_YouTubeVideoProperty)(0),           // 25: google.ads.googleads.v22.enums.YouTubeVideoPropertyEnum.YouTubeVideoProperty
	(enums.InsightsKnowledgeGraphEntityCapabilitiesEnum_InsightsKnowledgeGraphEntityCapabilities)(0), // 26: google.ads.googleads.v22.enums.InsightsKnowledgeGraphEntityCapabilitiesEnum.InsightsKnowledgeGraphEntityCapabilities
	(enums.UserListTypeEnum_UserListType)(0),                                                         // 27: google.ads.googleads.v22.enums.UserListTypeEnum.UserListType
}
var file_google_ads_googleads_v22_common_audience_insights_attribute_proto_depIdxs = []int32{
	14, // 0: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata.dimension:type_name -> google.ads.googleads.v22.enums.AudienceInsightsDimensionEnum.AudienceInsightsDimension
	1,  // 1: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata.attribute:type_name -> google.ads.googleads.v22.common.AudienceInsightsAttribute
	5,  // 2: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata.youtube_channel_metadata:type_name -> google.ads.googleads.v22.common.YouTubeChannelAttributeMetadata
	6,  // 3: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata.youtube_video_metadata:type_name -> google.ads.googleads.v22.common.YouTubeVideoAttributeMetadata
	7,  // 4: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata.lineup_attribute_metadata:type_name -> google.ads.googleads.v22.common.LineupAttributeMetadata
	8,  // 5: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata.location_attribute_metadata:type_name -> google.ads.googleads.v22.common.LocationAttributeMetadata
	9,  // 6: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata.user_interest_attribute_metadata:type_name -> google.ads.googleads.v22.common.UserInterestAttributeMetadata
	10, // 7: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata.knowledge_graph_attribute_metadata:type_name -> google.ads.googleads.v22.common.KnowledgeGraphAttributeMetadata
	11, // 8: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata.user_list_attribute_metadata:type_name -> google.ads.googleads.v22.common.UserListAttributeMetadata
	15, // 9: google.ads.googleads.v22.common.AudienceInsightsAttribute.age_range:type_name -> google.ads.googleads.v22.common.AgeRangeInfo
	16, // 10: google.ads.googleads.v22.common.AudienceInsightsAttribute.gender:type_name -> google.ads.googleads.v22.common.GenderInfo
	17, // 11: google.ads.googleads.v22.common.AudienceInsightsAttribute.location:type_name -> google.ads.googleads.v22.common.LocationInfo
	18, // 12: google.ads.googleads.v22.common.AudienceInsightsAttribute.user_interest:type_name -> google.ads.googleads.v22.common.UserInterestInfo
	2,  // 13: google.ads.googleads.v22.common.AudienceInsightsAttribute.entity:type_name -> google.ads.googleads.v22.common.AudienceInsightsEntity
	3,  // 14: google.ads.googleads.v22.common.AudienceInsightsAttribute.category:type_name -> google.ads.googleads.v22.common.AudienceInsightsCategory
	4,  // 15: google.ads.googleads.v22.common.AudienceInsightsAttribute.lineup:type_name -> google.ads.googleads.v22.common.AudienceInsightsLineup
	19, // 16: google.ads.googleads.v22.common.AudienceInsightsAttribute.parental_status:type_name -> google.ads.googleads.v22.common.ParentalStatusInfo
	20, // 17: google.ads.googleads.v22.common.AudienceInsightsAttribute.income_range:type_name -> google.ads.googleads.v22.common.IncomeRangeInfo
	21, // 18: google.ads.googleads.v22.common.AudienceInsightsAttribute.youtube_channel:type_name -> google.ads.googleads.v22.common.YouTubeChannelInfo
	22, // 19: google.ads.googleads.v22.common.AudienceInsightsAttribute.youtube_video:type_name -> google.ads.googleads.v22.common.YouTubeVideoInfo
	23, // 20: google.ads.googleads.v22.common.AudienceInsightsAttribute.device:type_name -> google.ads.googleads.v22.common.DeviceInfo
	24, // 21: google.ads.googleads.v22.common.AudienceInsightsAttribute.user_list:type_name -> google.ads.googleads.v22.common.UserListInfo
	25, // 22: google.ads.googleads.v22.common.YouTubeVideoAttributeMetadata.video_properties:type_name -> google.ads.googleads.v22.enums.YouTubeVideoPropertyEnum.YouTubeVideoProperty
	17, // 23: google.ads.googleads.v22.common.LineupAttributeMetadata.inventory_country:type_name -> google.ads.googleads.v22.common.LocationInfo
	13, // 24: google.ads.googleads.v22.common.LineupAttributeMetadata.sample_channels:type_name -> google.ads.googleads.v22.common.LineupAttributeMetadata.SampleChannel
	17, // 25: google.ads.googleads.v22.common.LocationAttributeMetadata.country_location:type_name -> google.ads.googleads.v22.common.LocationInfo
	26, // 26: google.ads.googleads.v22.common.KnowledgeGraphAttributeMetadata.entity_capabilities:type_name -> google.ads.googleads.v22.enums.InsightsKnowledgeGraphEntityCapabilitiesEnum.InsightsKnowledgeGraphEntityCapabilities
	0,  // 27: google.ads.googleads.v22.common.KnowledgeGraphAttributeMetadata.related_categories:type_name -> google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata
	27, // 28: google.ads.googleads.v22.common.UserListAttributeMetadata.user_list_type:type_name -> google.ads.googleads.v22.enums.UserListTypeEnum.UserListType
	0,  // 29: google.ads.googleads.v22.common.AudienceInsightsAttributeMetadataGroup.attributes:type_name -> google.ads.googleads.v22.common.AudienceInsightsAttributeMetadata
	21, // 30: google.ads.googleads.v22.common.LineupAttributeMetadata.SampleChannel.youtube_channel:type_name -> google.ads.googleads.v22.common.YouTubeChannelInfo
	5,  // 31: google.ads.googleads.v22.common.LineupAttributeMetadata.SampleChannel.youtube_channel_metadata:type_name -> google.ads.googleads.v22.common.YouTubeChannelAttributeMetadata
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_common_audience_insights_attribute_proto_init() }
func file_google_ads_googleads_v22_common_audience_insights_attribute_proto_init() {
	if File_google_ads_googleads_v22_common_audience_insights_attribute_proto != nil {
		return
	}
	file_google_ads_googleads_v22_common_criteria_proto_init()
	file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[0].OneofWrappers = []any{
		(*AudienceInsightsAttributeMetadata_YoutubeChannelMetadata)(nil),
		(*AudienceInsightsAttributeMetadata_YoutubeVideoMetadata)(nil),
		(*AudienceInsightsAttributeMetadata_LineupAttributeMetadata)(nil),
		(*AudienceInsightsAttributeMetadata_LocationAttributeMetadata)(nil),
		(*AudienceInsightsAttributeMetadata_UserInterestAttributeMetadata)(nil),
		(*AudienceInsightsAttributeMetadata_KnowledgeGraphAttributeMetadata)(nil),
		(*AudienceInsightsAttributeMetadata_UserListAttributeMetadata)(nil),
	}
	file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[1].OneofWrappers = []any{
		(*AudienceInsightsAttribute_AgeRange)(nil),
		(*AudienceInsightsAttribute_Gender)(nil),
		(*AudienceInsightsAttribute_Location)(nil),
		(*AudienceInsightsAttribute_UserInterest)(nil),
		(*AudienceInsightsAttribute_Entity)(nil),
		(*AudienceInsightsAttribute_Category)(nil),
		(*AudienceInsightsAttribute_Lineup)(nil),
		(*AudienceInsightsAttribute_ParentalStatus)(nil),
		(*AudienceInsightsAttribute_IncomeRange)(nil),
		(*AudienceInsightsAttribute_YoutubeChannel)(nil),
		(*AudienceInsightsAttribute_YoutubeVideo)(nil),
		(*AudienceInsightsAttribute_Device)(nil),
		(*AudienceInsightsAttribute_UserList)(nil),
	}
	file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDesc), len(file_google_ads_googleads_v22_common_audience_insights_attribute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_common_audience_insights_attribute_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_common_audience_insights_attribute_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_common_audience_insights_attribute_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_common_audience_insights_attribute_proto = out.File
	file_google_ads_googleads_v22_common_audience_insights_attribute_proto_goTypes = nil
	file_google_ads_googleads_v22_common_audience_insights_attribute_proto_depIdxs = nil
}
