// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/common/campaign_goal_settings.proto

package common

import (
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Campaign Goal settings.
type CampaignGoalSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignGoalSettings) Reset() {
	*x = CampaignGoalSettings{}
	mi := &file_google_ads_googleads_v22_common_campaign_goal_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignGoalSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignGoalSettings) ProtoMessage() {}

func (x *CampaignGoalSettings) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_campaign_goal_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignGoalSettings.ProtoReflect.Descriptor instead.
func (*CampaignGoalSettings) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDescGZIP(), []int{0}
}

// Retention campaign goal settings.
type CampaignGoalSettings_CampaignRetentionGoalSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Retention goal campaign specific value settings.
	ValueSettingsOverride *CustomerLifecycleOptimizationValueSettings `protobuf:"bytes,1,opt,name=value_settings_override,json=valueSettingsOverride,proto3" json:"value_settings_override,omitempty"`
	// Retention goal optimization mode for this campaign.
	//
	// Defaults to TARGET_ALL. Only customers on the allowlist can set
	// target_option.
	TargetOption  enums.CustomerLifecycleOptimizationModeEnum_CustomerLifecycleOptimizationMode `protobuf:"varint,2,opt,name=target_option,json=targetOption,proto3,enum=google.ads.googleads.v22.enums.CustomerLifecycleOptimizationModeEnum_CustomerLifecycleOptimizationMode" json:"target_option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignGoalSettings_CampaignRetentionGoalSettings) Reset() {
	*x = CampaignGoalSettings_CampaignRetentionGoalSettings{}
	mi := &file_google_ads_googleads_v22_common_campaign_goal_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignGoalSettings_CampaignRetentionGoalSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignGoalSettings_CampaignRetentionGoalSettings) ProtoMessage() {}

func (x *CampaignGoalSettings_CampaignRetentionGoalSettings) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_campaign_goal_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignGoalSettings_CampaignRetentionGoalSettings.ProtoReflect.Descriptor instead.
func (*CampaignGoalSettings_CampaignRetentionGoalSettings) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CampaignGoalSettings_CampaignRetentionGoalSettings) GetValueSettingsOverride() *CustomerLifecycleOptimizationValueSettings {
	if x != nil {
		return x.ValueSettingsOverride
	}
	return nil
}

func (x *CampaignGoalSettings_CampaignRetentionGoalSettings) GetTargetOption() enums.CustomerLifecycleOptimizationModeEnum_CustomerLifecycleOptimizationMode {
	if x != nil {
		return x.TargetOption
	}
	return enums.CustomerLifecycleOptimizationModeEnum_CustomerLifecycleOptimizationMode(0)
}

var File_google_ads_googleads_v22_common_campaign_goal_settings_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDesc = "" +
	"\n" +
	"<google/ads/googleads/v22/common/campaign_goal_settings.proto\x12\x1fgoogle.ads.googleads.v22.common\x1a1google/ads/googleads/v22/common/goal_common.proto\x1aIgoogle/ads/googleads/v22/enums/customer_lifecycle_optimization_mode.proto\"\xcd\x02\n" +
	"\x14CampaignGoalSettings\x1a\xb4\x02\n" +
	"\x1dCampaignRetentionGoalSettings\x12\x83\x01\n" +
	"\x17value_settings_override\x18\x01 \x01(\v2K.google.ads.googleads.v22.common.CustomerLifecycleOptimizationValueSettingsR\x15valueSettingsOverride\x12\x8c\x01\n" +
	"\rtarget_option\x18\x02 \x01(\x0e2g.google.ads.googleads.v22.enums.CustomerLifecycleOptimizationModeEnum.CustomerLifecycleOptimizationModeR\ftargetOptionB\xf9\x01\n" +
	"#com.google.ads.googleads.v22.commonB\x19CampaignGoalSettingsProtoP\x01ZEgithub.com/Optable/google-ads-pb/protogen/common;common\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V22.Common\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V22\\Common\xea\x02#Google::Ads::GoogleAds::V22::Commonb\x06proto3"

var (
	file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDesc), len(file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDescData
}

var file_google_ads_googleads_v22_common_campaign_goal_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_ads_googleads_v22_common_campaign_goal_settings_proto_goTypes = []any{
	(*CampaignGoalSettings)(nil),                                                       // 0: google.ads.googleads.v22.common.CampaignGoalSettings
	(*CampaignGoalSettings_CampaignRetentionGoalSettings)(nil),                         // 1: google.ads.googleads.v22.common.CampaignGoalSettings.CampaignRetentionGoalSettings
	(*CustomerLifecycleOptimizationValueSettings)(nil),                                 // 2: google.ads.googleads.v22.common.CustomerLifecycleOptimizationValueSettings
	(enums.CustomerLifecycleOptimizationModeEnum_CustomerLifecycleOptimizationMode)(0), // 3: google.ads.googleads.v22.enums.CustomerLifecycleOptimizationModeEnum.CustomerLifecycleOptimizationMode
}
var file_google_ads_googleads_v22_common_campaign_goal_settings_proto_depIdxs = []int32{
	2, // 0: google.ads.googleads.v22.common.CampaignGoalSettings.CampaignRetentionGoalSettings.value_settings_override:type_name -> google.ads.googleads.v22.common.CustomerLifecycleOptimizationValueSettings
	3, // 1: google.ads.googleads.v22.common.CampaignGoalSettings.CampaignRetentionGoalSettings.target_option:type_name -> google.ads.googleads.v22.enums.CustomerLifecycleOptimizationModeEnum.CustomerLifecycleOptimizationMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_common_campaign_goal_settings_proto_init() }
func file_google_ads_googleads_v22_common_campaign_goal_settings_proto_init() {
	if File_google_ads_googleads_v22_common_campaign_goal_settings_proto != nil {
		return
	}
	file_google_ads_googleads_v22_common_goal_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDesc), len(file_google_ads_googleads_v22_common_campaign_goal_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_common_campaign_goal_settings_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_common_campaign_goal_settings_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_common_campaign_goal_settings_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_common_campaign_goal_settings_proto = out.File
	file_google_ads_googleads_v22_common_campaign_goal_settings_proto_goTypes = nil
	file_google_ads_googleads_v22_common_campaign_goal_settings_proto_depIdxs = nil
}
