// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/common/goal_common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle goal optimization value settings.
type CustomerLifecycleOptimizationValueSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value of the lifecycle goal. For example, for retention goals, value is the
	// incremental conversion value for lapsed customers who are not of high
	// value.
	AdditionalValue *float64 `protobuf:"fixed64,1,opt,name=additional_value,json=additionalValue,proto3,oneof" json:"additional_value,omitempty"`
	// High lifetime value of the lifecycle goal. For example, for customer
	// acquisition goals, high lifetime value is the incremental conversion value
	// for lapsed customers who are of high value. High lifetime value should be
	// greater than value, if set.
	AdditionalHighLifetimeValue *float64 `protobuf:"fixed64,2,opt,name=additional_high_lifetime_value,json=additionalHighLifetimeValue,proto3,oneof" json:"additional_high_lifetime_value,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CustomerLifecycleOptimizationValueSettings) Reset() {
	*x = CustomerLifecycleOptimizationValueSettings{}
	mi := &file_google_ads_googleads_v22_common_goal_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerLifecycleOptimizationValueSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerLifecycleOptimizationValueSettings) ProtoMessage() {}

func (x *CustomerLifecycleOptimizationValueSettings) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_goal_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerLifecycleOptimizationValueSettings.ProtoReflect.Descriptor instead.
func (*CustomerLifecycleOptimizationValueSettings) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_goal_common_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerLifecycleOptimizationValueSettings) GetAdditionalValue() float64 {
	if x != nil && x.AdditionalValue != nil {
		return *x.AdditionalValue
	}
	return 0
}

func (x *CustomerLifecycleOptimizationValueSettings) GetAdditionalHighLifetimeValue() float64 {
	if x != nil && x.AdditionalHighLifetimeValue != nil {
		return *x.AdditionalHighLifetimeValue
	}
	return 0
}

var File_google_ads_googleads_v22_common_goal_common_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_common_goal_common_proto_rawDesc = "" +
	"\n" +
	"1google/ads/googleads/v22/common/goal_common.proto\x12\x1fgoogle.ads.googleads.v22.common\"\xde\x01\n" +
	"*CustomerLifecycleOptimizationValueSettings\x12.\n" +
	"\x10additional_value\x18\x01 \x01(\x01H\x00R\x0fadditionalValue\x88\x01\x01\x12H\n" +
	"\x1eadditional_high_lifetime_value\x18\x02 \x01(\x01H\x01R\x1badditionalHighLifetimeValue\x88\x01\x01B\x13\n" +
	"\x11_additional_valueB!\n" +
	"\x1f_additional_high_lifetime_valueB\xef\x01\n" +
	"#com.google.ads.googleads.v22.commonB\x0fGoalCommonProtoP\x01ZEgithub.com/Optable/google-ads-pb/protogen/common;common\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V22.Common\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V22\\Common\xea\x02#Google::Ads::GoogleAds::V22::Commonb\x06proto3"

var (
	file_google_ads_googleads_v22_common_goal_common_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_common_goal_common_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_common_goal_common_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_common_goal_common_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_common_goal_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_goal_common_proto_rawDesc), len(file_google_ads_googleads_v22_common_goal_common_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_common_goal_common_proto_rawDescData
}

var file_google_ads_googleads_v22_common_goal_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_common_goal_common_proto_goTypes = []any{
	(*CustomerLifecycleOptimizationValueSettings)(nil), // 0: google.ads.googleads.v22.common.CustomerLifecycleOptimizationValueSettings
}
var file_google_ads_googleads_v22_common_goal_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_common_goal_common_proto_init() }
func file_google_ads_googleads_v22_common_goal_common_proto_init() {
	if File_google_ads_googleads_v22_common_goal_common_proto != nil {
		return
	}
	file_google_ads_googleads_v22_common_goal_common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_goal_common_proto_rawDesc), len(file_google_ads_googleads_v22_common_goal_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_common_goal_common_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_common_goal_common_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_common_goal_common_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_common_goal_common_proto = out.File
	file_google_ads_googleads_v22_common_goal_common_proto_goTypes = nil
	file_google_ads_googleads_v22_common_goal_common_proto_depIdxs = nil
}
