// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/common/goal_setting.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Goal setting.
type GoalSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalSetting) Reset() {
	*x = GoalSetting{}
	mi := &file_google_ads_googleads_v22_common_goal_setting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalSetting) ProtoMessage() {}

func (x *GoalSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_goal_setting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalSetting.ProtoReflect.Descriptor instead.
func (*GoalSetting) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_goal_setting_proto_rawDescGZIP(), []int{0}
}

// Retention goal settings.
type GoalSetting_RetentionGoal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Retention goal value settings.
	ValueSettings *CustomerLifecycleOptimizationValueSettings `protobuf:"bytes,1,opt,name=value_settings,json=valueSettings,proto3" json:"value_settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalSetting_RetentionGoal) Reset() {
	*x = GoalSetting_RetentionGoal{}
	mi := &file_google_ads_googleads_v22_common_goal_setting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalSetting_RetentionGoal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalSetting_RetentionGoal) ProtoMessage() {}

func (x *GoalSetting_RetentionGoal) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_goal_setting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalSetting_RetentionGoal.ProtoReflect.Descriptor instead.
func (*GoalSetting_RetentionGoal) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_goal_setting_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GoalSetting_RetentionGoal) GetValueSettings() *CustomerLifecycleOptimizationValueSettings {
	if x != nil {
		return x.ValueSettings
	}
	return nil
}

var File_google_ads_googleads_v22_common_goal_setting_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_common_goal_setting_proto_rawDesc = "" +
	"\n" +
	"2google/ads/googleads/v22/common/goal_setting.proto\x12\x1fgoogle.ads.googleads.v22.common\x1a1google/ads/googleads/v22/common/goal_common.proto\"\x93\x01\n" +
	"\vGoalSetting\x1a\x83\x01\n" +
	"\rRetentionGoal\x12r\n" +
	"\x0evalue_settings\x18\x01 \x01(\v2K.google.ads.googleads.v22.common.CustomerLifecycleOptimizationValueSettingsR\rvalueSettingsB\xf0\x01\n" +
	"#com.google.ads.googleads.v22.commonB\x10GoalSettingProtoP\x01ZEgithub.com/Optable/google-ads-pb/protogen/common;common\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V22.Common\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V22\\Common\xea\x02#Google::Ads::GoogleAds::V22::Commonb\x06proto3"

var (
	file_google_ads_googleads_v22_common_goal_setting_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_common_goal_setting_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_common_goal_setting_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_common_goal_setting_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_common_goal_setting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_goal_setting_proto_rawDesc), len(file_google_ads_googleads_v22_common_goal_setting_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_common_goal_setting_proto_rawDescData
}

var file_google_ads_googleads_v22_common_goal_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_ads_googleads_v22_common_goal_setting_proto_goTypes = []any{
	(*GoalSetting)(nil),                                // 0: google.ads.googleads.v22.common.GoalSetting
	(*GoalSetting_RetentionGoal)(nil),                  // 1: google.ads.googleads.v22.common.GoalSetting.RetentionGoal
	(*CustomerLifecycleOptimizationValueSettings)(nil), // 2: google.ads.googleads.v22.common.CustomerLifecycleOptimizationValueSettings
}
var file_google_ads_googleads_v22_common_goal_setting_proto_depIdxs = []int32{
	2, // 0: google.ads.googleads.v22.common.GoalSetting.RetentionGoal.value_settings:type_name -> google.ads.googleads.v22.common.CustomerLifecycleOptimizationValueSettings
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_common_goal_setting_proto_init() }
func file_google_ads_googleads_v22_common_goal_setting_proto_init() {
	if File_google_ads_googleads_v22_common_goal_setting_proto != nil {
		return
	}
	file_google_ads_googleads_v22_common_goal_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_goal_setting_proto_rawDesc), len(file_google_ads_googleads_v22_common_goal_setting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_common_goal_setting_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_common_goal_setting_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_common_goal_setting_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_common_goal_setting_proto = out.File
	file_google_ads_googleads_v22_common_goal_setting_proto_goTypes = nil
	file_google_ads_googleads_v22_common_goal_setting_proto_depIdxs = nil
}
