// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/common/third_party_integration_partners.proto

package common

import (
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container for Customer level third party integration partners.
type CustomerThirdPartyIntegrationPartners struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed third party integration partners for YouTube viewability
	// verification.
	ViewabilityIntegrationPartners []*CustomerThirdPartyViewabilityIntegrationPartner `protobuf:"bytes,1,rep,name=viewability_integration_partners,json=viewabilityIntegrationPartners,proto3" json:"viewability_integration_partners,omitempty"`
	// Allowed third party integration partners for Brand Lift verification.
	BrandLiftIntegrationPartners []*CustomerThirdPartyBrandLiftIntegrationPartner `protobuf:"bytes,2,rep,name=brand_lift_integration_partners,json=brandLiftIntegrationPartners,proto3" json:"brand_lift_integration_partners,omitempty"`
	// Allowed third party integration partners for brand safety verification.
	BrandSafetyIntegrationPartners []*CustomerThirdPartyBrandSafetyIntegrationPartner `protobuf:"bytes,3,rep,name=brand_safety_integration_partners,json=brandSafetyIntegrationPartners,proto3" json:"brand_safety_integration_partners,omitempty"`
	// Allowed third party integration partners for reach verification.
	ReachIntegrationPartners []*CustomerThirdPartyReachIntegrationPartner `protobuf:"bytes,4,rep,name=reach_integration_partners,json=reachIntegrationPartners,proto3" json:"reach_integration_partners,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CustomerThirdPartyIntegrationPartners) Reset() {
	*x = CustomerThirdPartyIntegrationPartners{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerThirdPartyIntegrationPartners) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerThirdPartyIntegrationPartners) ProtoMessage() {}

func (x *CustomerThirdPartyIntegrationPartners) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerThirdPartyIntegrationPartners.ProtoReflect.Descriptor instead.
func (*CustomerThirdPartyIntegrationPartners) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{0}
}

func (x *CustomerThirdPartyIntegrationPartners) GetViewabilityIntegrationPartners() []*CustomerThirdPartyViewabilityIntegrationPartner {
	if x != nil {
		return x.ViewabilityIntegrationPartners
	}
	return nil
}

func (x *CustomerThirdPartyIntegrationPartners) GetBrandLiftIntegrationPartners() []*CustomerThirdPartyBrandLiftIntegrationPartner {
	if x != nil {
		return x.BrandLiftIntegrationPartners
	}
	return nil
}

func (x *CustomerThirdPartyIntegrationPartners) GetBrandSafetyIntegrationPartners() []*CustomerThirdPartyBrandSafetyIntegrationPartner {
	if x != nil {
		return x.BrandSafetyIntegrationPartners
	}
	return nil
}

func (x *CustomerThirdPartyIntegrationPartners) GetReachIntegrationPartners() []*CustomerThirdPartyReachIntegrationPartner {
	if x != nil {
		return x.ReachIntegrationPartners
	}
	return nil
}

// Container for third party viewability integration data for Customer.
type CustomerThirdPartyViewabilityIntegrationPartner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed third party integration partners for YouTube viewability
	// verification.
	ViewabilityIntegrationPartner enums.ThirdPartyViewabilityIntegrationPartnerEnum_ThirdPartyViewabilityIntegrationPartner `protobuf:"varint,1,opt,name=viewability_integration_partner,json=viewabilityIntegrationPartner,proto3,enum=google.ads.googleads.v22.enums.ThirdPartyViewabilityIntegrationPartnerEnum_ThirdPartyViewabilityIntegrationPartner" json:"viewability_integration_partner,omitempty"`
	// If true, cost data can be shared with this vendor.
	AllowShareCost bool `protobuf:"varint,2,opt,name=allow_share_cost,json=allowShareCost,proto3" json:"allow_share_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CustomerThirdPartyViewabilityIntegrationPartner) Reset() {
	*x = CustomerThirdPartyViewabilityIntegrationPartner{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerThirdPartyViewabilityIntegrationPartner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerThirdPartyViewabilityIntegrationPartner) ProtoMessage() {}

func (x *CustomerThirdPartyViewabilityIntegrationPartner) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerThirdPartyViewabilityIntegrationPartner.ProtoReflect.Descriptor instead.
func (*CustomerThirdPartyViewabilityIntegrationPartner) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerThirdPartyViewabilityIntegrationPartner) GetViewabilityIntegrationPartner() enums.ThirdPartyViewabilityIntegrationPartnerEnum_ThirdPartyViewabilityIntegrationPartner {
	if x != nil {
		return x.ViewabilityIntegrationPartner
	}
	return enums.ThirdPartyViewabilityIntegrationPartnerEnum_ThirdPartyViewabilityIntegrationPartner(0)
}

func (x *CustomerThirdPartyViewabilityIntegrationPartner) GetAllowShareCost() bool {
	if x != nil {
		return x.AllowShareCost
	}
	return false
}

// Container for third party brand safety integration data for Customer.
type CustomerThirdPartyBrandSafetyIntegrationPartner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed third party integration partners for brand safety verification.
	BrandSafetyIntegrationPartner enums.ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner `protobuf:"varint,1,opt,name=brand_safety_integration_partner,json=brandSafetyIntegrationPartner,proto3,enum=google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner" json:"brand_safety_integration_partner,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *CustomerThirdPartyBrandSafetyIntegrationPartner) Reset() {
	*x = CustomerThirdPartyBrandSafetyIntegrationPartner{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerThirdPartyBrandSafetyIntegrationPartner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerThirdPartyBrandSafetyIntegrationPartner) ProtoMessage() {}

func (x *CustomerThirdPartyBrandSafetyIntegrationPartner) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerThirdPartyBrandSafetyIntegrationPartner.ProtoReflect.Descriptor instead.
func (*CustomerThirdPartyBrandSafetyIntegrationPartner) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerThirdPartyBrandSafetyIntegrationPartner) GetBrandSafetyIntegrationPartner() enums.ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner {
	if x != nil {
		return x.BrandSafetyIntegrationPartner
	}
	return enums.ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner(0)
}

// Container for third party Brand Lift integration data for Customer.
type CustomerThirdPartyBrandLiftIntegrationPartner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed Third Party integration partners for Brand Lift verification.
	BrandLiftIntegrationPartner enums.ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner `protobuf:"varint,1,opt,name=brand_lift_integration_partner,json=brandLiftIntegrationPartner,proto3,enum=google.ads.googleads.v22.enums.ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner" json:"brand_lift_integration_partner,omitempty"`
	// If true, cost data can be shared with this vendor.
	AllowShareCost bool `protobuf:"varint,2,opt,name=allow_share_cost,json=allowShareCost,proto3" json:"allow_share_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CustomerThirdPartyBrandLiftIntegrationPartner) Reset() {
	*x = CustomerThirdPartyBrandLiftIntegrationPartner{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerThirdPartyBrandLiftIntegrationPartner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerThirdPartyBrandLiftIntegrationPartner) ProtoMessage() {}

func (x *CustomerThirdPartyBrandLiftIntegrationPartner) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerThirdPartyBrandLiftIntegrationPartner.ProtoReflect.Descriptor instead.
func (*CustomerThirdPartyBrandLiftIntegrationPartner) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerThirdPartyBrandLiftIntegrationPartner) GetBrandLiftIntegrationPartner() enums.ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner {
	if x != nil {
		return x.BrandLiftIntegrationPartner
	}
	return enums.ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner(0)
}

func (x *CustomerThirdPartyBrandLiftIntegrationPartner) GetAllowShareCost() bool {
	if x != nil {
		return x.AllowShareCost
	}
	return false
}

// Container for third party reach integration data for Customer.
type CustomerThirdPartyReachIntegrationPartner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed Third Party integration partners for reach verification.
	ReachIntegrationPartner enums.ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner `protobuf:"varint,1,opt,name=reach_integration_partner,json=reachIntegrationPartner,proto3,enum=google.ads.googleads.v22.enums.ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner" json:"reach_integration_partner,omitempty"`
	// If true, cost data can be shared with this vendor.
	AllowShareCost bool `protobuf:"varint,2,opt,name=allow_share_cost,json=allowShareCost,proto3" json:"allow_share_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CustomerThirdPartyReachIntegrationPartner) Reset() {
	*x = CustomerThirdPartyReachIntegrationPartner{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerThirdPartyReachIntegrationPartner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerThirdPartyReachIntegrationPartner) ProtoMessage() {}

func (x *CustomerThirdPartyReachIntegrationPartner) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerThirdPartyReachIntegrationPartner.ProtoReflect.Descriptor instead.
func (*CustomerThirdPartyReachIntegrationPartner) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{4}
}

func (x *CustomerThirdPartyReachIntegrationPartner) GetReachIntegrationPartner() enums.ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner {
	if x != nil {
		return x.ReachIntegrationPartner
	}
	return enums.ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner(0)
}

func (x *CustomerThirdPartyReachIntegrationPartner) GetAllowShareCost() bool {
	if x != nil {
		return x.AllowShareCost
	}
	return false
}

// Container for Campaign level third party integration partners.
type CampaignThirdPartyIntegrationPartners struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Third party integration partners for YouTube viewability
	// verification for this Campaign.
	ViewabilityIntegrationPartners []*CampaignThirdPartyViewabilityIntegrationPartner `protobuf:"bytes,1,rep,name=viewability_integration_partners,json=viewabilityIntegrationPartners,proto3" json:"viewability_integration_partners,omitempty"`
	// Third party integration partners for Brand Lift verification for this
	// Campaign.
	BrandLiftIntegrationPartners []*CampaignThirdPartyBrandLiftIntegrationPartner `protobuf:"bytes,2,rep,name=brand_lift_integration_partners,json=brandLiftIntegrationPartners,proto3" json:"brand_lift_integration_partners,omitempty"`
	// Third party integration partners for brand safety verification for this
	// Campaign.
	BrandSafetyIntegrationPartners []*CampaignThirdPartyBrandSafetyIntegrationPartner `protobuf:"bytes,3,rep,name=brand_safety_integration_partners,json=brandSafetyIntegrationPartners,proto3" json:"brand_safety_integration_partners,omitempty"`
	// Third party integration partners for reach verification for this Campaign.
	ReachIntegrationPartners []*CampaignThirdPartyReachIntegrationPartner `protobuf:"bytes,4,rep,name=reach_integration_partners,json=reachIntegrationPartners,proto3" json:"reach_integration_partners,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CampaignThirdPartyIntegrationPartners) Reset() {
	*x = CampaignThirdPartyIntegrationPartners{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignThirdPartyIntegrationPartners) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignThirdPartyIntegrationPartners) ProtoMessage() {}

func (x *CampaignThirdPartyIntegrationPartners) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignThirdPartyIntegrationPartners.ProtoReflect.Descriptor instead.
func (*CampaignThirdPartyIntegrationPartners) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{5}
}

func (x *CampaignThirdPartyIntegrationPartners) GetViewabilityIntegrationPartners() []*CampaignThirdPartyViewabilityIntegrationPartner {
	if x != nil {
		return x.ViewabilityIntegrationPartners
	}
	return nil
}

func (x *CampaignThirdPartyIntegrationPartners) GetBrandLiftIntegrationPartners() []*CampaignThirdPartyBrandLiftIntegrationPartner {
	if x != nil {
		return x.BrandLiftIntegrationPartners
	}
	return nil
}

func (x *CampaignThirdPartyIntegrationPartners) GetBrandSafetyIntegrationPartners() []*CampaignThirdPartyBrandSafetyIntegrationPartner {
	if x != nil {
		return x.BrandSafetyIntegrationPartners
	}
	return nil
}

func (x *CampaignThirdPartyIntegrationPartners) GetReachIntegrationPartners() []*CampaignThirdPartyReachIntegrationPartner {
	if x != nil {
		return x.ReachIntegrationPartners
	}
	return nil
}

// Container for third party viewability integration data for Campaign.
type CampaignThirdPartyViewabilityIntegrationPartner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed third party integration partners for YouTube viewability
	// verification.
	ViewabilityIntegrationPartner enums.ThirdPartyViewabilityIntegrationPartnerEnum_ThirdPartyViewabilityIntegrationPartner `protobuf:"varint,1,opt,name=viewability_integration_partner,json=viewabilityIntegrationPartner,proto3,enum=google.ads.googleads.v22.enums.ThirdPartyViewabilityIntegrationPartnerEnum_ThirdPartyViewabilityIntegrationPartner" json:"viewability_integration_partner,omitempty"`
	// Third party partner data for YouTube viewability verification. This is
	// optional metadata for partners to join or attach data to Ads campaigns.
	ViewabilityIntegrationPartnerData *ThirdPartyIntegrationPartnerData `protobuf:"bytes,2,opt,name=viewability_integration_partner_data,json=viewabilityIntegrationPartnerData,proto3" json:"viewability_integration_partner_data,omitempty"`
	// If true, then cost data will be shared with this vendor.
	ShareCost     bool `protobuf:"varint,3,opt,name=share_cost,json=shareCost,proto3" json:"share_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignThirdPartyViewabilityIntegrationPartner) Reset() {
	*x = CampaignThirdPartyViewabilityIntegrationPartner{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignThirdPartyViewabilityIntegrationPartner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignThirdPartyViewabilityIntegrationPartner) ProtoMessage() {}

func (x *CampaignThirdPartyViewabilityIntegrationPartner) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignThirdPartyViewabilityIntegrationPartner.ProtoReflect.Descriptor instead.
func (*CampaignThirdPartyViewabilityIntegrationPartner) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{6}
}

func (x *CampaignThirdPartyViewabilityIntegrationPartner) GetViewabilityIntegrationPartner() enums.ThirdPartyViewabilityIntegrationPartnerEnum_ThirdPartyViewabilityIntegrationPartner {
	if x != nil {
		return x.ViewabilityIntegrationPartner
	}
	return enums.ThirdPartyViewabilityIntegrationPartnerEnum_ThirdPartyViewabilityIntegrationPartner(0)
}

func (x *CampaignThirdPartyViewabilityIntegrationPartner) GetViewabilityIntegrationPartnerData() *ThirdPartyIntegrationPartnerData {
	if x != nil {
		return x.ViewabilityIntegrationPartnerData
	}
	return nil
}

func (x *CampaignThirdPartyViewabilityIntegrationPartner) GetShareCost() bool {
	if x != nil {
		return x.ShareCost
	}
	return false
}

// Container for third party brand safety integration data for Campaign.
type CampaignThirdPartyBrandSafetyIntegrationPartner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed third party integration partners for brand safety verification.
	BrandSafetyIntegrationPartner enums.ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner `protobuf:"varint,1,opt,name=brand_safety_integration_partner,json=brandSafetyIntegrationPartner,proto3,enum=google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner" json:"brand_safety_integration_partner,omitempty"`
	// Third party partner data for YouTube brand safety verification. This is
	// optional metadata for partners to join or attach data to Ads campaigns.
	BrandSafetyIntegrationPartnerData *ThirdPartyIntegrationPartnerData `protobuf:"bytes,2,opt,name=brand_safety_integration_partner_data,json=brandSafetyIntegrationPartnerData,proto3" json:"brand_safety_integration_partner_data,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *CampaignThirdPartyBrandSafetyIntegrationPartner) Reset() {
	*x = CampaignThirdPartyBrandSafetyIntegrationPartner{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignThirdPartyBrandSafetyIntegrationPartner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignThirdPartyBrandSafetyIntegrationPartner) ProtoMessage() {}

func (x *CampaignThirdPartyBrandSafetyIntegrationPartner) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignThirdPartyBrandSafetyIntegrationPartner.ProtoReflect.Descriptor instead.
func (*CampaignThirdPartyBrandSafetyIntegrationPartner) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{7}
}

func (x *CampaignThirdPartyBrandSafetyIntegrationPartner) GetBrandSafetyIntegrationPartner() enums.ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner {
	if x != nil {
		return x.BrandSafetyIntegrationPartner
	}
	return enums.ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner(0)
}

func (x *CampaignThirdPartyBrandSafetyIntegrationPartner) GetBrandSafetyIntegrationPartnerData() *ThirdPartyIntegrationPartnerData {
	if x != nil {
		return x.BrandSafetyIntegrationPartnerData
	}
	return nil
}

// Container for third party Brand Lift integration data for Campaign.
type CampaignThirdPartyBrandLiftIntegrationPartner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed third party integration partners for Brand Lift verification.
	BrandLiftIntegrationPartner enums.ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner `protobuf:"varint,1,opt,name=brand_lift_integration_partner,json=brandLiftIntegrationPartner,proto3,enum=google.ads.googleads.v22.enums.ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner" json:"brand_lift_integration_partner,omitempty"`
	// Third party partner data for YouTube Brand Lift verification. This is
	// optional metadata for partners to join or attach data to Ads campaigns.
	BrandLiftIntegrationPartnerData *ThirdPartyIntegrationPartnerData `protobuf:"bytes,2,opt,name=brand_lift_integration_partner_data,json=brandLiftIntegrationPartnerData,proto3" json:"brand_lift_integration_partner_data,omitempty"`
	// If true, then cost data will be shared with this vendor.
	ShareCost     bool `protobuf:"varint,3,opt,name=share_cost,json=shareCost,proto3" json:"share_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignThirdPartyBrandLiftIntegrationPartner) Reset() {
	*x = CampaignThirdPartyBrandLiftIntegrationPartner{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignThirdPartyBrandLiftIntegrationPartner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignThirdPartyBrandLiftIntegrationPartner) ProtoMessage() {}

func (x *CampaignThirdPartyBrandLiftIntegrationPartner) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignThirdPartyBrandLiftIntegrationPartner.ProtoReflect.Descriptor instead.
func (*CampaignThirdPartyBrandLiftIntegrationPartner) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{8}
}

func (x *CampaignThirdPartyBrandLiftIntegrationPartner) GetBrandLiftIntegrationPartner() enums.ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner {
	if x != nil {
		return x.BrandLiftIntegrationPartner
	}
	return enums.ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner(0)
}

func (x *CampaignThirdPartyBrandLiftIntegrationPartner) GetBrandLiftIntegrationPartnerData() *ThirdPartyIntegrationPartnerData {
	if x != nil {
		return x.BrandLiftIntegrationPartnerData
	}
	return nil
}

func (x *CampaignThirdPartyBrandLiftIntegrationPartner) GetShareCost() bool {
	if x != nil {
		return x.ShareCost
	}
	return false
}

// Container for third party reach integration data for Campaign.
type CampaignThirdPartyReachIntegrationPartner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Allowed third party integration partners for reach verification.
	ReachIntegrationPartner enums.ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner `protobuf:"varint,1,opt,name=reach_integration_partner,json=reachIntegrationPartner,proto3,enum=google.ads.googleads.v22.enums.ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner" json:"reach_integration_partner,omitempty"`
	// Third party partner data for YouTube Reach verification. This is
	// optional metadata for partners to join or attach data to Ads campaigns.
	ReachIntegrationPartnerData *ThirdPartyIntegrationPartnerData `protobuf:"bytes,2,opt,name=reach_integration_partner_data,json=reachIntegrationPartnerData,proto3" json:"reach_integration_partner_data,omitempty"`
	// If true, then cost data will be shared with this vendor.
	ShareCost     bool `protobuf:"varint,3,opt,name=share_cost,json=shareCost,proto3" json:"share_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignThirdPartyReachIntegrationPartner) Reset() {
	*x = CampaignThirdPartyReachIntegrationPartner{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignThirdPartyReachIntegrationPartner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignThirdPartyReachIntegrationPartner) ProtoMessage() {}

func (x *CampaignThirdPartyReachIntegrationPartner) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignThirdPartyReachIntegrationPartner.ProtoReflect.Descriptor instead.
func (*CampaignThirdPartyReachIntegrationPartner) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{9}
}

func (x *CampaignThirdPartyReachIntegrationPartner) GetReachIntegrationPartner() enums.ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner {
	if x != nil {
		return x.ReachIntegrationPartner
	}
	return enums.ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner(0)
}

func (x *CampaignThirdPartyReachIntegrationPartner) GetReachIntegrationPartnerData() *ThirdPartyIntegrationPartnerData {
	if x != nil {
		return x.ReachIntegrationPartnerData
	}
	return nil
}

func (x *CampaignThirdPartyReachIntegrationPartner) GetShareCost() bool {
	if x != nil {
		return x.ShareCost
	}
	return false
}

// Contains third party measurement partner related data for video campaigns.
type ThirdPartyIntegrationPartnerData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client ID that allows the measurement partner to join multiple
	// campaigns for a particular advertiser.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The third party placement ID that maps the measurement partner data with a
	// campaign (or a group of related campaigns) specific data.
	ThirdPartyPlacementId string `protobuf:"bytes,2,opt,name=third_party_placement_id,json=thirdPartyPlacementId,proto3" json:"third_party_placement_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ThirdPartyIntegrationPartnerData) Reset() {
	*x = ThirdPartyIntegrationPartnerData{}
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyIntegrationPartnerData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyIntegrationPartnerData) ProtoMessage() {}

func (x *ThirdPartyIntegrationPartnerData) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyIntegrationPartnerData.ProtoReflect.Descriptor instead.
func (*ThirdPartyIntegrationPartnerData) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP(), []int{10}
}

func (x *ThirdPartyIntegrationPartnerData) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ThirdPartyIntegrationPartnerData) GetThirdPartyPlacementId() string {
	if x != nil {
		return x.ThirdPartyPlacementId
	}
	return ""
}

var File_google_ads_googleads_v22_common_third_party_integration_partners_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDesc = "" +
	"\n" +
	"Fgoogle/ads/googleads/v22/common/third_party_integration_partners.proto\x12\x1fgoogle.ads.googleads.v22.common\x1aOgoogle/ads/googleads/v22/enums/third_party_brand_lift_integration_partner.proto\x1aQgoogle/ads/googleads/v22/enums/third_party_brand_safety_integration_partner.proto\x1aJgoogle/ads/googleads/v22/enums/third_party_reach_integration_partner.proto\x1aPgoogle/ads/googleads/v22/enums/third_party_viewability_integration_partner.proto\"\x85\x05\n" +
	"%CustomerThirdPartyIntegrationPartners\x12\x9a\x01\n" +
	" viewability_integration_partners\x18\x01 \x03(\v2P.google.ads.googleads.v22.common.CustomerThirdPartyViewabilityIntegrationPartnerR\x1eviewabilityIntegrationPartners\x12\x95\x01\n" +
	"\x1fbrand_lift_integration_partners\x18\x02 \x03(\v2N.google.ads.googleads.v22.common.CustomerThirdPartyBrandLiftIntegrationPartnerR\x1cbrandLiftIntegrationPartners\x12\x9b\x01\n" +
	"!brand_safety_integration_partners\x18\x03 \x03(\v2P.google.ads.googleads.v22.common.CustomerThirdPartyBrandSafetyIntegrationPartnerR\x1ebrandSafetyIntegrationPartners\x12\x88\x01\n" +
	"\x1areach_integration_partners\x18\x04 \x03(\v2J.google.ads.googleads.v22.common.CustomerThirdPartyReachIntegrationPartnerR\x18reachIntegrationPartners\"\x99\x02\n" +
	"/CustomerThirdPartyViewabilityIntegrationPartner\x12\xbb\x01\n" +
	"\x1fviewability_integration_partner\x18\x01 \x01(\x0e2s.google.ads.googleads.v22.enums.ThirdPartyViewabilityIntegrationPartnerEnum.ThirdPartyViewabilityIntegrationPartnerR\x1dviewabilityIntegrationPartner\x12(\n" +
	"\x10allow_share_cost\x18\x02 \x01(\bR\x0eallowShareCost\"\xf0\x01\n" +
	"/CustomerThirdPartyBrandSafetyIntegrationPartner\x12\xbc\x01\n" +
	" brand_safety_integration_partner\x18\x01 \x01(\x0e2s.google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum.ThirdPartyBrandSafetyIntegrationPartnerR\x1dbrandSafetyIntegrationPartner\"\x90\x02\n" +
	"-CustomerThirdPartyBrandLiftIntegrationPartner\x12\xb4\x01\n" +
	"\x1ebrand_lift_integration_partner\x18\x01 \x01(\x0e2o.google.ads.googleads.v22.enums.ThirdPartyBrandLiftIntegrationPartnerEnum.ThirdPartyBrandLiftIntegrationPartnerR\x1bbrandLiftIntegrationPartner\x12(\n" +
	"\x10allow_share_cost\x18\x02 \x01(\bR\x0eallowShareCost\"\xfb\x01\n" +
	")CustomerThirdPartyReachIntegrationPartner\x12\xa3\x01\n" +
	"\x19reach_integration_partner\x18\x01 \x01(\x0e2g.google.ads.googleads.v22.enums.ThirdPartyReachIntegrationPartnerEnum.ThirdPartyReachIntegrationPartnerR\x17reachIntegrationPartner\x12(\n" +
	"\x10allow_share_cost\x18\x02 \x01(\bR\x0eallowShareCost\"\x85\x05\n" +
	"%CampaignThirdPartyIntegrationPartners\x12\x9a\x01\n" +
	" viewability_integration_partners\x18\x01 \x03(\v2P.google.ads.googleads.v22.common.CampaignThirdPartyViewabilityIntegrationPartnerR\x1eviewabilityIntegrationPartners\x12\x95\x01\n" +
	"\x1fbrand_lift_integration_partners\x18\x02 \x03(\v2N.google.ads.googleads.v22.common.CampaignThirdPartyBrandLiftIntegrationPartnerR\x1cbrandLiftIntegrationPartners\x12\x9b\x01\n" +
	"!brand_safety_integration_partners\x18\x03 \x03(\v2P.google.ads.googleads.v22.common.CampaignThirdPartyBrandSafetyIntegrationPartnerR\x1ebrandSafetyIntegrationPartners\x12\x88\x01\n" +
	"\x1areach_integration_partners\x18\x04 \x03(\v2J.google.ads.googleads.v22.common.CampaignThirdPartyReachIntegrationPartnerR\x18reachIntegrationPartners\"\xa3\x03\n" +
	"/CampaignThirdPartyViewabilityIntegrationPartner\x12\xbb\x01\n" +
	"\x1fviewability_integration_partner\x18\x01 \x01(\x0e2s.google.ads.googleads.v22.enums.ThirdPartyViewabilityIntegrationPartnerEnum.ThirdPartyViewabilityIntegrationPartnerR\x1dviewabilityIntegrationPartner\x12\x92\x01\n" +
	"$viewability_integration_partner_data\x18\x02 \x01(\v2A.google.ads.googleads.v22.common.ThirdPartyIntegrationPartnerDataR!viewabilityIntegrationPartnerData\x12\x1d\n" +
	"\n" +
	"share_cost\x18\x03 \x01(\bR\tshareCost\"\x86\x03\n" +
	"/CampaignThirdPartyBrandSafetyIntegrationPartner\x12\xbc\x01\n" +
	" brand_safety_integration_partner\x18\x01 \x01(\x0e2s.google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum.ThirdPartyBrandSafetyIntegrationPartnerR\x1dbrandSafetyIntegrationPartner\x12\x93\x01\n" +
	"%brand_safety_integration_partner_data\x18\x02 \x01(\v2A.google.ads.googleads.v22.common.ThirdPartyIntegrationPartnerDataR!brandSafetyIntegrationPartnerData\"\x97\x03\n" +
	"-CampaignThirdPartyBrandLiftIntegrationPartner\x12\xb4\x01\n" +
	"\x1ebrand_lift_integration_partner\x18\x01 \x01(\x0e2o.google.ads.googleads.v22.enums.ThirdPartyBrandLiftIntegrationPartnerEnum.ThirdPartyBrandLiftIntegrationPartnerR\x1bbrandLiftIntegrationPartner\x12\x8f\x01\n" +
	"#brand_lift_integration_partner_data\x18\x02 \x01(\v2A.google.ads.googleads.v22.common.ThirdPartyIntegrationPartnerDataR\x1fbrandLiftIntegrationPartnerData\x12\x1d\n" +
	"\n" +
	"share_cost\x18\x03 \x01(\bR\tshareCost\"\xf9\x02\n" +
	")CampaignThirdPartyReachIntegrationPartner\x12\xa3\x01\n" +
	"\x19reach_integration_partner\x18\x01 \x01(\x0e2g.google.ads.googleads.v22.enums.ThirdPartyReachIntegrationPartnerEnum.ThirdPartyReachIntegrationPartnerR\x17reachIntegrationPartner\x12\x86\x01\n" +
	"\x1ereach_integration_partner_data\x18\x02 \x01(\v2A.google.ads.googleads.v22.common.ThirdPartyIntegrationPartnerDataR\x1breachIntegrationPartnerData\x12\x1d\n" +
	"\n" +
	"share_cost\x18\x03 \x01(\bR\tshareCost\"x\n" +
	" ThirdPartyIntegrationPartnerData\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x127\n" +
	"\x18third_party_placement_id\x18\x02 \x01(\tR\x15thirdPartyPlacementIdB\x82\x02\n" +
	"#com.google.ads.googleads.v22.commonB\"ThirdPartyIntegrationPartnersProtoP\x01ZEgithub.com/Optable/google-ads-pb/protogen/common;common\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V22.Common\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V22\\Common\xea\x02#Google::Ads::GoogleAds::V22::Commonb\x06proto3"

var (
	file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDesc), len(file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDescData
}

var file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_google_ads_googleads_v22_common_third_party_integration_partners_proto_goTypes = []any{
	(*CustomerThirdPartyIntegrationPartners)(nil),                                                  // 0: google.ads.googleads.v22.common.CustomerThirdPartyIntegrationPartners
	(*CustomerThirdPartyViewabilityIntegrationPartner)(nil),                                        // 1: google.ads.googleads.v22.common.CustomerThirdPartyViewabilityIntegrationPartner
	(*CustomerThirdPartyBrandSafetyIntegrationPartner)(nil),                                        // 2: google.ads.googleads.v22.common.CustomerThirdPartyBrandSafetyIntegrationPartner
	(*CustomerThirdPartyBrandLiftIntegrationPartner)(nil),                                          // 3: google.ads.googleads.v22.common.CustomerThirdPartyBrandLiftIntegrationPartner
	(*CustomerThirdPartyReachIntegrationPartner)(nil),                                              // 4: google.ads.googleads.v22.common.CustomerThirdPartyReachIntegrationPartner
	(*CampaignThirdPartyIntegrationPartners)(nil),                                                  // 5: google.ads.googleads.v22.common.CampaignThirdPartyIntegrationPartners
	(*CampaignThirdPartyViewabilityIntegrationPartner)(nil),                                        // 6: google.ads.googleads.v22.common.CampaignThirdPartyViewabilityIntegrationPartner
	(*CampaignThirdPartyBrandSafetyIntegrationPartner)(nil),                                        // 7: google.ads.googleads.v22.common.CampaignThirdPartyBrandSafetyIntegrationPartner
	(*CampaignThirdPartyBrandLiftIntegrationPartner)(nil),                                          // 8: google.ads.googleads.v22.common.CampaignThirdPartyBrandLiftIntegrationPartner
	(*CampaignThirdPartyReachIntegrationPartner)(nil),                                              // 9: google.ads.googleads.v22.common.CampaignThirdPartyReachIntegrationPartner
	(*ThirdPartyIntegrationPartnerData)(nil),                                                       // 10: google.ads.googleads.v22.common.ThirdPartyIntegrationPartnerData
	(enums.ThirdPartyViewabilityIntegrationPartnerEnum_ThirdPartyViewabilityIntegrationPartner)(0), // 11: google.ads.googleads.v22.enums.ThirdPartyViewabilityIntegrationPartnerEnum.ThirdPartyViewabilityIntegrationPartner
	(enums.ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner)(0), // 12: google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum.ThirdPartyBrandSafetyIntegrationPartner
	(enums.ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner)(0),     // 13: google.ads.googleads.v22.enums.ThirdPartyBrandLiftIntegrationPartnerEnum.ThirdPartyBrandLiftIntegrationPartner
	(enums.ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner)(0),             // 14: google.ads.googleads.v22.enums.ThirdPartyReachIntegrationPartnerEnum.ThirdPartyReachIntegrationPartner
}
var file_google_ads_googleads_v22_common_third_party_integration_partners_proto_depIdxs = []int32{
	1,  // 0: google.ads.googleads.v22.common.CustomerThirdPartyIntegrationPartners.viewability_integration_partners:type_name -> google.ads.googleads.v22.common.CustomerThirdPartyViewabilityIntegrationPartner
	3,  // 1: google.ads.googleads.v22.common.CustomerThirdPartyIntegrationPartners.brand_lift_integration_partners:type_name -> google.ads.googleads.v22.common.CustomerThirdPartyBrandLiftIntegrationPartner
	2,  // 2: google.ads.googleads.v22.common.CustomerThirdPartyIntegrationPartners.brand_safety_integration_partners:type_name -> google.ads.googleads.v22.common.CustomerThirdPartyBrandSafetyIntegrationPartner
	4,  // 3: google.ads.googleads.v22.common.CustomerThirdPartyIntegrationPartners.reach_integration_partners:type_name -> google.ads.googleads.v22.common.CustomerThirdPartyReachIntegrationPartner
	11, // 4: google.ads.googleads.v22.common.CustomerThirdPartyViewabilityIntegrationPartner.viewability_integration_partner:type_name -> google.ads.googleads.v22.enums.ThirdPartyViewabilityIntegrationPartnerEnum.ThirdPartyViewabilityIntegrationPartner
	12, // 5: google.ads.googleads.v22.common.CustomerThirdPartyBrandSafetyIntegrationPartner.brand_safety_integration_partner:type_name -> google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum.ThirdPartyBrandSafetyIntegrationPartner
	13, // 6: google.ads.googleads.v22.common.CustomerThirdPartyBrandLiftIntegrationPartner.brand_lift_integration_partner:type_name -> google.ads.googleads.v22.enums.ThirdPartyBrandLiftIntegrationPartnerEnum.ThirdPartyBrandLiftIntegrationPartner
	14, // 7: google.ads.googleads.v22.common.CustomerThirdPartyReachIntegrationPartner.reach_integration_partner:type_name -> google.ads.googleads.v22.enums.ThirdPartyReachIntegrationPartnerEnum.ThirdPartyReachIntegrationPartner
	6,  // 8: google.ads.googleads.v22.common.CampaignThirdPartyIntegrationPartners.viewability_integration_partners:type_name -> google.ads.googleads.v22.common.CampaignThirdPartyViewabilityIntegrationPartner
	8,  // 9: google.ads.googleads.v22.common.CampaignThirdPartyIntegrationPartners.brand_lift_integration_partners:type_name -> google.ads.googleads.v22.common.CampaignThirdPartyBrandLiftIntegrationPartner
	7,  // 10: google.ads.googleads.v22.common.CampaignThirdPartyIntegrationPartners.brand_safety_integration_partners:type_name -> google.ads.googleads.v22.common.CampaignThirdPartyBrandSafetyIntegrationPartner
	9,  // 11: google.ads.googleads.v22.common.CampaignThirdPartyIntegrationPartners.reach_integration_partners:type_name -> google.ads.googleads.v22.common.CampaignThirdPartyReachIntegrationPartner
	11, // 12: google.ads.googleads.v22.common.CampaignThirdPartyViewabilityIntegrationPartner.viewability_integration_partner:type_name -> google.ads.googleads.v22.enums.ThirdPartyViewabilityIntegrationPartnerEnum.ThirdPartyViewabilityIntegrationPartner
	10, // 13: google.ads.googleads.v22.common.CampaignThirdPartyViewabilityIntegrationPartner.viewability_integration_partner_data:type_name -> google.ads.googleads.v22.common.ThirdPartyIntegrationPartnerData
	12, // 14: google.ads.googleads.v22.common.CampaignThirdPartyBrandSafetyIntegrationPartner.brand_safety_integration_partner:type_name -> google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum.ThirdPartyBrandSafetyIntegrationPartner
	10, // 15: google.ads.googleads.v22.common.CampaignThirdPartyBrandSafetyIntegrationPartner.brand_safety_integration_partner_data:type_name -> google.ads.googleads.v22.common.ThirdPartyIntegrationPartnerData
	13, // 16: google.ads.googleads.v22.common.CampaignThirdPartyBrandLiftIntegrationPartner.brand_lift_integration_partner:type_name -> google.ads.googleads.v22.enums.ThirdPartyBrandLiftIntegrationPartnerEnum.ThirdPartyBrandLiftIntegrationPartner
	10, // 17: google.ads.googleads.v22.common.CampaignThirdPartyBrandLiftIntegrationPartner.brand_lift_integration_partner_data:type_name -> google.ads.googleads.v22.common.ThirdPartyIntegrationPartnerData
	14, // 18: google.ads.googleads.v22.common.CampaignThirdPartyReachIntegrationPartner.reach_integration_partner:type_name -> google.ads.googleads.v22.enums.ThirdPartyReachIntegrationPartnerEnum.ThirdPartyReachIntegrationPartner
	10, // 19: google.ads.googleads.v22.common.CampaignThirdPartyReachIntegrationPartner.reach_integration_partner_data:type_name -> google.ads.googleads.v22.common.ThirdPartyIntegrationPartnerData
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_common_third_party_integration_partners_proto_init() }
func file_google_ads_googleads_v22_common_third_party_integration_partners_proto_init() {
	if File_google_ads_googleads_v22_common_third_party_integration_partners_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDesc), len(file_google_ads_googleads_v22_common_third_party_integration_partners_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_common_third_party_integration_partners_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_common_third_party_integration_partners_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_common_third_party_integration_partners_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_common_third_party_integration_partners_proto = out.File
	file_google_ads_googleads_v22_common_third_party_integration_partners_proto_goTypes = nil
	file_google_ads_googleads_v22_common_third_party_integration_partners_proto_depIdxs = nil
}
