// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/enums/goal_type.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The possible value of goal types.
type GoalTypeEnum_GoalType int32

const (
	// Not specified.
	GoalTypeEnum_UNSPECIFIED GoalTypeEnum_GoalType = 0
	// Used for return value only. Represents value unknown in this version.
	GoalTypeEnum_UNKNOWN GoalTypeEnum_GoalType = 1
	// Retention goal, which allows advertisers to optimize campaigns to win
	// back lapsed customers.
	// (https://support.google.com/google-ads/answer/14792043?hl=en)
	GoalTypeEnum_CUSTOMER_RETENTION GoalTypeEnum_GoalType = 3
)

// Enum value maps for GoalTypeEnum_GoalType.
var (
	GoalTypeEnum_GoalType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		3: "CUSTOMER_RETENTION",
	}
	GoalTypeEnum_GoalType_value = map[string]int32{
		"UNSPECIFIED":        0,
		"UNKNOWN":            1,
		"CUSTOMER_RETENTION": 3,
	}
)

func (x GoalTypeEnum_GoalType) Enum() *GoalTypeEnum_GoalType {
	p := new(GoalTypeEnum_GoalType)
	*p = x
	return p
}

func (x GoalTypeEnum_GoalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoalTypeEnum_GoalType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_enums_goal_type_proto_enumTypes[0].Descriptor()
}

func (GoalTypeEnum_GoalType) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_enums_goal_type_proto_enumTypes[0]
}

func (x GoalTypeEnum_GoalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoalTypeEnum_GoalType.Descriptor instead.
func (GoalTypeEnum_GoalType) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_goal_type_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing goal types.
type GoalTypeEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalTypeEnum) Reset() {
	*x = GoalTypeEnum{}
	mi := &file_google_ads_googleads_v22_enums_goal_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalTypeEnum) ProtoMessage() {}

func (x *GoalTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_enums_goal_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalTypeEnum.ProtoReflect.Descriptor instead.
func (*GoalTypeEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_goal_type_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_enums_goal_type_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_enums_goal_type_proto_rawDesc = "" +
	"\n" +
	".google/ads/googleads/v22/enums/goal_type.proto\x12\x1egoogle.ads.googleads.v22.enums\"P\n" +
	"\fGoalTypeEnum\"@\n" +
	"\bGoalType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\x16\n" +
	"\x12CUSTOMER_RETENTION\x10\x03B\xe7\x01\n" +
	"\"com.google.ads.googleads.v22.enumsB\rGoalTypeProtoP\x01ZCgithub.com/Optable/google-ads-pb/protogen/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v22_enums_goal_type_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_enums_goal_type_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_enums_goal_type_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_enums_goal_type_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_enums_goal_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_goal_type_proto_rawDesc), len(file_google_ads_googleads_v22_enums_goal_type_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_enums_goal_type_proto_rawDescData
}

var file_google_ads_googleads_v22_enums_goal_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_enums_goal_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_enums_goal_type_proto_goTypes = []any{
	(GoalTypeEnum_GoalType)(0), // 0: google.ads.googleads.v22.enums.GoalTypeEnum.GoalType
	(*GoalTypeEnum)(nil),       // 1: google.ads.googleads.v22.enums.GoalTypeEnum
}
var file_google_ads_googleads_v22_enums_goal_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_enums_goal_type_proto_init() }
func file_google_ads_googleads_v22_enums_goal_type_proto_init() {
	if File_google_ads_googleads_v22_enums_goal_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_goal_type_proto_rawDesc), len(file_google_ads_googleads_v22_enums_goal_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_enums_goal_type_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_enums_goal_type_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_enums_goal_type_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_enums_goal_type_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_enums_goal_type_proto = out.File
	file_google_ads_googleads_v22_enums_goal_type_proto_goTypes = nil
	file_google_ads_googleads_v22_enums_goal_type_proto_depIdxs = nil
}
