// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/enums/goal_optimization_eligibility.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The possible goal optimization eligibility.
type GoalOptimizationEligibilityEnum_GoalOptimizationEligibility int32

const (
	// The goal optimization status has not been specified.
	GoalOptimizationEligibilityEnum_UNSPECIFIED GoalOptimizationEligibilityEnum_GoalOptimizationEligibility = 0
	// The goal optimization status is not known in this version.
	GoalOptimizationEligibilityEnum_UNKNOWN GoalOptimizationEligibilityEnum_GoalOptimizationEligibility = 1
	// The goal is eligible for campaign optimization.
	GoalOptimizationEligibilityEnum_ELIGIBLE GoalOptimizationEligibilityEnum_GoalOptimizationEligibility = 2
	// The goal is not eligible for campaign optimization.
	GoalOptimizationEligibilityEnum_INELIGIBLE GoalOptimizationEligibilityEnum_GoalOptimizationEligibility = 3
)

// Enum value maps for GoalOptimizationEligibilityEnum_GoalOptimizationEligibility.
var (
	GoalOptimizationEligibilityEnum_GoalOptimizationEligibility_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "ELIGIBLE",
		3: "INELIGIBLE",
	}
	GoalOptimizationEligibilityEnum_GoalOptimizationEligibility_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNKNOWN":     1,
		"ELIGIBLE":    2,
		"INELIGIBLE":  3,
	}
)

func (x GoalOptimizationEligibilityEnum_GoalOptimizationEligibility) Enum() *GoalOptimizationEligibilityEnum_GoalOptimizationEligibility {
	p := new(GoalOptimizationEligibilityEnum_GoalOptimizationEligibility)
	*p = x
	return p
}

func (x GoalOptimizationEligibilityEnum_GoalOptimizationEligibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoalOptimizationEligibilityEnum_GoalOptimizationEligibility) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_enumTypes[0].Descriptor()
}

func (GoalOptimizationEligibilityEnum_GoalOptimizationEligibility) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_enumTypes[0]
}

func (x GoalOptimizationEligibilityEnum_GoalOptimizationEligibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoalOptimizationEligibilityEnum_GoalOptimizationEligibility.Descriptor instead.
func (GoalOptimizationEligibilityEnum_GoalOptimizationEligibility) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing possible goal optimization eligibility.
type GoalOptimizationEligibilityEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalOptimizationEligibilityEnum) Reset() {
	*x = GoalOptimizationEligibilityEnum{}
	mi := &file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalOptimizationEligibilityEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalOptimizationEligibilityEnum) ProtoMessage() {}

func (x *GoalOptimizationEligibilityEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalOptimizationEligibilityEnum.ProtoReflect.Descriptor instead.
func (*GoalOptimizationEligibilityEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDesc = "" +
	"\n" +
	"Bgoogle/ads/googleads/v22/enums/goal_optimization_eligibility.proto\x12\x1egoogle.ads.googleads.v22.enums\"|\n" +
	"\x1fGoalOptimizationEligibilityEnum\"Y\n" +
	"\x1bGoalOptimizationEligibility\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\f\n" +
	"\bELIGIBLE\x10\x02\x12\x0e\n" +
	"\n" +
	"INELIGIBLE\x10\x03B\xfa\x01\n" +
	"\"com.google.ads.googleads.v22.enumsB GoalOptimizationEligibilityProtoP\x01ZCgithub.com/Optable/google-ads-pb/protogen/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDesc), len(file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDescData
}

var file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_goTypes = []any{
	(GoalOptimizationEligibilityEnum_GoalOptimizationEligibility)(0), // 0: google.ads.googleads.v22.enums.GoalOptimizationEligibilityEnum.GoalOptimizationEligibility
	(*GoalOptimizationEligibilityEnum)(nil),                          // 1: google.ads.googleads.v22.enums.GoalOptimizationEligibilityEnum
}
var file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_init() }
func file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_init() {
	if File_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDesc), len(file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto = out.File
	file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_goTypes = nil
	file_google_ads_googleads_v22_enums_goal_optimization_eligibility_proto_depIdxs = nil
}
