// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/enums/promotion_barcode_type.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A promotion barcode type.
type PromotionBarcodeTypeEnum_PromotionBarcodeType int32

const (
	// Not specified.
	PromotionBarcodeTypeEnum_UNSPECIFIED PromotionBarcodeTypeEnum_PromotionBarcodeType = 0
	// Used for return value only. Represents value unknown in this version.
	PromotionBarcodeTypeEnum_UNKNOWN PromotionBarcodeTypeEnum_PromotionBarcodeType = 1
	// Aztec 2D barcode format.
	// Max 350 characters and no links
	PromotionBarcodeTypeEnum_AZTEC PromotionBarcodeTypeEnum_PromotionBarcodeType = 2
	// CODABAR 1D format.
	// Max 12 characters and no links. Supported characters include
	// 0123456789-$:/.+ and optional start and end guards from ABCD.
	PromotionBarcodeTypeEnum_CODABAR PromotionBarcodeTypeEnum_PromotionBarcodeType = 3
	// Code 39 1D format.
	// Max 8 characters and no links. Supported characters include
	// 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ-. *$/+%.
	PromotionBarcodeTypeEnum_CODE39 PromotionBarcodeTypeEnum_PromotionBarcodeType = 4
	// Code 128 1D format.
	// Max 18 ASCII characters only and no links
	PromotionBarcodeTypeEnum_CODE128 PromotionBarcodeTypeEnum_PromotionBarcodeType = 5
	// Data Matrix 2D barcode format.
	// Max 525 ISO-8859-1 characters only and no links
	PromotionBarcodeTypeEnum_DATA_MATRIX PromotionBarcodeTypeEnum_PromotionBarcodeType = 6
	// EAN-8 1D format.
	// The barcode value should be 7 digits (the check digit will be computed
	// automatically) or 8 digits (if you are providing your own check digit).
	PromotionBarcodeTypeEnum_EAN8 PromotionBarcodeTypeEnum_PromotionBarcodeType = 7
	// EAN-13 1D format.
	// The barcode value should be 12 digits (the check digit will be computed
	// automatically) or 13 digits (if you are providing your own check digit).
	PromotionBarcodeTypeEnum_EAN13 PromotionBarcodeTypeEnum_PromotionBarcodeType = 8
	// ITF (Interleaved Two of Five) 1D format.
	// Must be 14 digits long
	PromotionBarcodeTypeEnum_ITF PromotionBarcodeTypeEnum_PromotionBarcodeType = 9
	// PDF417 format.
	// Max 140 characters and no links
	PromotionBarcodeTypeEnum_PDF417 PromotionBarcodeTypeEnum_PromotionBarcodeType = 10
	// UPC-A 1D format.
	// The barcode value should be 11 digits (the check digit will be computed
	// automatically) or 12 digits (if you are providing your own check digit).
	PromotionBarcodeTypeEnum_UPC_A PromotionBarcodeTypeEnum_PromotionBarcodeType = 11
)

// Enum value maps for PromotionBarcodeTypeEnum_PromotionBarcodeType.
var (
	PromotionBarcodeTypeEnum_PromotionBarcodeType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "UNKNOWN",
		2:  "AZTEC",
		3:  "CODABAR",
		4:  "CODE39",
		5:  "CODE128",
		6:  "DATA_MATRIX",
		7:  "EAN8",
		8:  "EAN13",
		9:  "ITF",
		10: "PDF417",
		11: "UPC_A",
	}
	PromotionBarcodeTypeEnum_PromotionBarcodeType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNKNOWN":     1,
		"AZTEC":       2,
		"CODABAR":     3,
		"CODE39":      4,
		"CODE128":     5,
		"DATA_MATRIX": 6,
		"EAN8":        7,
		"EAN13":       8,
		"ITF":         9,
		"PDF417":      10,
		"UPC_A":       11,
	}
)

func (x PromotionBarcodeTypeEnum_PromotionBarcodeType) Enum() *PromotionBarcodeTypeEnum_PromotionBarcodeType {
	p := new(PromotionBarcodeTypeEnum_PromotionBarcodeType)
	*p = x
	return p
}

func (x PromotionBarcodeTypeEnum_PromotionBarcodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PromotionBarcodeTypeEnum_PromotionBarcodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_enumTypes[0].Descriptor()
}

func (PromotionBarcodeTypeEnum_PromotionBarcodeType) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_enumTypes[0]
}

func (x PromotionBarcodeTypeEnum_PromotionBarcodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PromotionBarcodeTypeEnum_PromotionBarcodeType.Descriptor instead.
func (PromotionBarcodeTypeEnum_PromotionBarcodeType) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing a promotion barcode type.
type PromotionBarcodeTypeEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionBarcodeTypeEnum) Reset() {
	*x = PromotionBarcodeTypeEnum{}
	mi := &file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionBarcodeTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionBarcodeTypeEnum) ProtoMessage() {}

func (x *PromotionBarcodeTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionBarcodeTypeEnum.ProtoReflect.Descriptor instead.
func (*PromotionBarcodeTypeEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_enums_promotion_barcode_type_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDesc = "" +
	"\n" +
	";google/ads/googleads/v22/enums/promotion_barcode_type.proto\x12\x1egoogle.ads.googleads.v22.enums\"\xc8\x01\n" +
	"\x18PromotionBarcodeTypeEnum\"\xab\x01\n" +
	"\x14PromotionBarcodeType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\t\n" +
	"\x05AZTEC\x10\x02\x12\v\n" +
	"\aCODABAR\x10\x03\x12\n" +
	"\n" +
	"\x06CODE39\x10\x04\x12\v\n" +
	"\aCODE128\x10\x05\x12\x0f\n" +
	"\vDATA_MATRIX\x10\x06\x12\b\n" +
	"\x04EAN8\x10\a\x12\t\n" +
	"\x05EAN13\x10\b\x12\a\n" +
	"\x03ITF\x10\t\x12\n" +
	"\n" +
	"\x06PDF417\x10\n" +
	"\x12\t\n" +
	"\x05UPC_A\x10\vB\xf3\x01\n" +
	"\"com.google.ads.googleads.v22.enumsB\x19PromotionBarcodeTypeProtoP\x01ZCgithub.com/Optable/google-ads-pb/protogen/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDesc), len(file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDescData
}

var file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_goTypes = []any{
	(PromotionBarcodeTypeEnum_PromotionBarcodeType)(0), // 0: google.ads.googleads.v22.enums.PromotionBarcodeTypeEnum.PromotionBarcodeType
	(*PromotionBarcodeTypeEnum)(nil),                   // 1: google.ads.googleads.v22.enums.PromotionBarcodeTypeEnum
}
var file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_init() }
func file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_init() {
	if File_google_ads_googleads_v22_enums_promotion_barcode_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDesc), len(file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_enums_promotion_barcode_type_proto = out.File
	file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_goTypes = nil
	file_google_ads_googleads_v22_enums_promotion_barcode_type_proto_depIdxs = nil
}
