// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/enums/search_term_match_source.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The search term match sources.
type SearchTermMatchSourceEnum_SearchTermMatchSource int32

const (
	// Not specified.
	SearchTermMatchSourceEnum_UNSPECIFIED SearchTermMatchSourceEnum_SearchTermMatchSource = 0
	// Used for return value only. Represents value unknown in this version.
	SearchTermMatchSourceEnum_UNKNOWN SearchTermMatchSourceEnum_SearchTermMatchSource = 1
	// The match is from a user-provided keyword.
	SearchTermMatchSourceEnum_ADVERTISER_PROVIDED_KEYWORD SearchTermMatchSourceEnum_SearchTermMatchSource = 2
	// The match is from the keywordless expansion portion of AI Max.
	SearchTermMatchSourceEnum_AI_MAX_KEYWORDLESS SearchTermMatchSourceEnum_SearchTermMatchSource = 3
	// The match is from the broad match expansion portion of AI Max.
	SearchTermMatchSourceEnum_AI_MAX_BROAD_MATCH SearchTermMatchSourceEnum_SearchTermMatchSource = 4
	// The match is from a Dynamic Search Ad.
	SearchTermMatchSourceEnum_DYNAMIC_SEARCH_ADS SearchTermMatchSourceEnum_SearchTermMatchSource = 5
	// The match is from the search term matching functionality in PMax.
	SearchTermMatchSourceEnum_PERFORMANCE_MAX SearchTermMatchSourceEnum_SearchTermMatchSource = 6
)

// Enum value maps for SearchTermMatchSourceEnum_SearchTermMatchSource.
var (
	SearchTermMatchSourceEnum_SearchTermMatchSource_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "ADVERTISER_PROVIDED_KEYWORD",
		3: "AI_MAX_KEYWORDLESS",
		4: "AI_MAX_BROAD_MATCH",
		5: "DYNAMIC_SEARCH_ADS",
		6: "PERFORMANCE_MAX",
	}
	SearchTermMatchSourceEnum_SearchTermMatchSource_value = map[string]int32{
		"UNSPECIFIED":                 0,
		"UNKNOWN":                     1,
		"ADVERTISER_PROVIDED_KEYWORD": 2,
		"AI_MAX_KEYWORDLESS":          3,
		"AI_MAX_BROAD_MATCH":          4,
		"DYNAMIC_SEARCH_ADS":          5,
		"PERFORMANCE_MAX":             6,
	}
)

func (x SearchTermMatchSourceEnum_SearchTermMatchSource) Enum() *SearchTermMatchSourceEnum_SearchTermMatchSource {
	p := new(SearchTermMatchSourceEnum_SearchTermMatchSource)
	*p = x
	return p
}

func (x SearchTermMatchSourceEnum_SearchTermMatchSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchTermMatchSourceEnum_SearchTermMatchSource) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_enums_search_term_match_source_proto_enumTypes[0].Descriptor()
}

func (SearchTermMatchSourceEnum_SearchTermMatchSource) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_enums_search_term_match_source_proto_enumTypes[0]
}

func (x SearchTermMatchSourceEnum_SearchTermMatchSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchTermMatchSourceEnum_SearchTermMatchSource.Descriptor instead.
func (SearchTermMatchSourceEnum_SearchTermMatchSource) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing the source for search term matches in the
// search term report.
type SearchTermMatchSourceEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTermMatchSourceEnum) Reset() {
	*x = SearchTermMatchSourceEnum{}
	mi := &file_google_ads_googleads_v22_enums_search_term_match_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTermMatchSourceEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTermMatchSourceEnum) ProtoMessage() {}

func (x *SearchTermMatchSourceEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_enums_search_term_match_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTermMatchSourceEnum.ProtoReflect.Descriptor instead.
func (*SearchTermMatchSourceEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_enums_search_term_match_source_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDesc = "" +
	"\n" +
	"=google/ads/googleads/v22/enums/search_term_match_source.proto\x12\x1egoogle.ads.googleads.v22.enums\"\xd1\x01\n" +
	"\x19SearchTermMatchSourceEnum\"\xb3\x01\n" +
	"\x15SearchTermMatchSource\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\x1f\n" +
	"\x1bADVERTISER_PROVIDED_KEYWORD\x10\x02\x12\x16\n" +
	"\x12AI_MAX_KEYWORDLESS\x10\x03\x12\x16\n" +
	"\x12AI_MAX_BROAD_MATCH\x10\x04\x12\x16\n" +
	"\x12DYNAMIC_SEARCH_ADS\x10\x05\x12\x13\n" +
	"\x0fPERFORMANCE_MAX\x10\x06B\xf4\x01\n" +
	"\"com.google.ads.googleads.v22.enumsB\x1aSearchTermMatchSourceProtoP\x01ZCgithub.com/Optable/google-ads-pb/protogen/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDesc), len(file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDescData
}

var file_google_ads_googleads_v22_enums_search_term_match_source_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_enums_search_term_match_source_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_enums_search_term_match_source_proto_goTypes = []any{
	(SearchTermMatchSourceEnum_SearchTermMatchSource)(0), // 0: google.ads.googleads.v22.enums.SearchTermMatchSourceEnum.SearchTermMatchSource
	(*SearchTermMatchSourceEnum)(nil),                    // 1: google.ads.googleads.v22.enums.SearchTermMatchSourceEnum
}
var file_google_ads_googleads_v22_enums_search_term_match_source_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_enums_search_term_match_source_proto_init() }
func file_google_ads_googleads_v22_enums_search_term_match_source_proto_init() {
	if File_google_ads_googleads_v22_enums_search_term_match_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDesc), len(file_google_ads_googleads_v22_enums_search_term_match_source_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_enums_search_term_match_source_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_enums_search_term_match_source_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_enums_search_term_match_source_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_enums_search_term_match_source_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_enums_search_term_match_source_proto = out.File
	file_google_ads_googleads_v22_enums_search_term_match_source_proto_goTypes = nil
	file_google_ads_googleads_v22_enums_search_term_match_source_proto_depIdxs = nil
}
