// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/enums/third_party_brand_lift_integration_partner.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing available third party integration partners for Brand Lift
// verification.
type ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner int32

const (
	// Not specified.
	ThirdPartyBrandLiftIntegrationPartnerEnum_UNSPECIFIED ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner = 0
	// Used for return value only. Represents value unknown in this version.
	ThirdPartyBrandLiftIntegrationPartnerEnum_UNKNOWN ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner = 1
	// Kantar
	ThirdPartyBrandLiftIntegrationPartnerEnum_KANTAR_MILLWARD_BROWN ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner = 2
	// Dynata
	ThirdPartyBrandLiftIntegrationPartnerEnum_DYNATA ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner = 3
	// Intage
	ThirdPartyBrandLiftIntegrationPartnerEnum_INTAGE ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner = 4
	// Macromill
	ThirdPartyBrandLiftIntegrationPartnerEnum_MACROMILL ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner = 5
)

// Enum value maps for ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner.
var (
	ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "KANTAR_MILLWARD_BROWN",
		3: "DYNATA",
		4: "INTAGE",
		5: "MACROMILL",
	}
	ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner_value = map[string]int32{
		"UNSPECIFIED":           0,
		"UNKNOWN":               1,
		"KANTAR_MILLWARD_BROWN": 2,
		"DYNATA":                3,
		"INTAGE":                4,
		"MACROMILL":             5,
	}
)

func (x ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner) Enum() *ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner {
	p := new(ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner)
	*p = x
	return p
}

func (x ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_enumTypes[0].Descriptor()
}

func (ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_enumTypes[0]
}

func (x ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner.Descriptor instead.
func (ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing available third party integration partners for
// Brand Lift verification.
type ThirdPartyBrandLiftIntegrationPartnerEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyBrandLiftIntegrationPartnerEnum) Reset() {
	*x = ThirdPartyBrandLiftIntegrationPartnerEnum{}
	mi := &file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyBrandLiftIntegrationPartnerEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyBrandLiftIntegrationPartnerEnum) ProtoMessage() {}

func (x *ThirdPartyBrandLiftIntegrationPartnerEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyBrandLiftIntegrationPartnerEnum.ProtoReflect.Descriptor instead.
func (*ThirdPartyBrandLiftIntegrationPartnerEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDesc = "" +
	"\n" +
	"Ogoogle/ads/googleads/v22/enums/third_party_brand_lift_integration_partner.proto\x12\x1egoogle.ads.googleads.v22.enums\"\xb5\x01\n" +
	")ThirdPartyBrandLiftIntegrationPartnerEnum\"\x87\x01\n" +
	"%ThirdPartyBrandLiftIntegrationPartner\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\x19\n" +
	"\x15KANTAR_MILLWARD_BROWN\x10\x02\x12\n" +
	"\n" +
	"\x06DYNATA\x10\x03\x12\n" +
	"\n" +
	"\x06INTAGE\x10\x04\x12\r\n" +
	"\tMACROMILL\x10\x05B\x84\x02\n" +
	"\"com.google.ads.googleads.v22.enumsB*ThirdPartyBrandLiftIntegrationPartnerProtoP\x01ZCgithub.com/Optable/google-ads-pb/protogen/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDesc), len(file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDescData
}

var file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_goTypes = []any{
	(ThirdPartyBrandLiftIntegrationPartnerEnum_ThirdPartyBrandLiftIntegrationPartner)(0), // 0: google.ads.googleads.v22.enums.ThirdPartyBrandLiftIntegrationPartnerEnum.ThirdPartyBrandLiftIntegrationPartner
	(*ThirdPartyBrandLiftIntegrationPartnerEnum)(nil),                                    // 1: google.ads.googleads.v22.enums.ThirdPartyBrandLiftIntegrationPartnerEnum
}
var file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_init()
}
func file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_init() {
	if File_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDesc), len(file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto = out.File
	file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_goTypes = nil
	file_google_ads_googleads_v22_enums_third_party_brand_lift_integration_partner_proto_depIdxs = nil
}
