// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/enums/third_party_brand_safety_integration_partner.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing available third party integration partners for brand safety
// verification.
type ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner int32

const (
	// Not specified.
	ThirdPartyBrandSafetyIntegrationPartnerEnum_UNSPECIFIED ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner = 0
	// Used for return value only. Represents value unknown in this version.
	ThirdPartyBrandSafetyIntegrationPartnerEnum_UNKNOWN ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner = 1
	// DoubleVerify.
	ThirdPartyBrandSafetyIntegrationPartnerEnum_DOUBLE_VERIFY ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner = 2
	// Integral Ad Science.
	ThirdPartyBrandSafetyIntegrationPartnerEnum_INTEGRAL_AD_SCIENCE ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner = 3
	// Zefr.
	ThirdPartyBrandSafetyIntegrationPartnerEnum_ZEFR ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner = 4
)

// Enum value maps for ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner.
var (
	ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "DOUBLE_VERIFY",
		3: "INTEGRAL_AD_SCIENCE",
		4: "ZEFR",
	}
	ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner_value = map[string]int32{
		"UNSPECIFIED":         0,
		"UNKNOWN":             1,
		"DOUBLE_VERIFY":       2,
		"INTEGRAL_AD_SCIENCE": 3,
		"ZEFR":                4,
	}
)

func (x ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner) Enum() *ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner {
	p := new(ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner)
	*p = x
	return p
}

func (x ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_enumTypes[0].Descriptor()
}

func (ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_enumTypes[0]
}

func (x ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner.Descriptor instead.
func (ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing available third party integration partners for
// brand safety verification.
type ThirdPartyBrandSafetyIntegrationPartnerEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyBrandSafetyIntegrationPartnerEnum) Reset() {
	*x = ThirdPartyBrandSafetyIntegrationPartnerEnum{}
	mi := &file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyBrandSafetyIntegrationPartnerEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyBrandSafetyIntegrationPartnerEnum) ProtoMessage() {}

func (x *ThirdPartyBrandSafetyIntegrationPartnerEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyBrandSafetyIntegrationPartnerEnum.ProtoReflect.Descriptor instead.
func (*ThirdPartyBrandSafetyIntegrationPartnerEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDesc = "" +
	"\n" +
	"Qgoogle/ads/googleads/v22/enums/third_party_brand_safety_integration_partner.proto\x12\x1egoogle.ads.googleads.v22.enums\"\xac\x01\n" +
	"+ThirdPartyBrandSafetyIntegrationPartnerEnum\"}\n" +
	"'ThirdPartyBrandSafetyIntegrationPartner\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\x11\n" +
	"\rDOUBLE_VERIFY\x10\x02\x12\x17\n" +
	"\x13INTEGRAL_AD_SCIENCE\x10\x03\x12\b\n" +
	"\x04ZEFR\x10\x04B\x86\x02\n" +
	"\"com.google.ads.googleads.v22.enumsB,ThirdPartyBrandSafetyIntegrationPartnerProtoP\x01ZCgithub.com/Optable/google-ads-pb/protogen/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDesc), len(file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDescData
}

var file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_goTypes = []any{
	(ThirdPartyBrandSafetyIntegrationPartnerEnum_ThirdPartyBrandSafetyIntegrationPartner)(0), // 0: google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum.ThirdPartyBrandSafetyIntegrationPartner
	(*ThirdPartyBrandSafetyIntegrationPartnerEnum)(nil),                                      // 1: google.ads.googleads.v22.enums.ThirdPartyBrandSafetyIntegrationPartnerEnum
}
var file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_init()
}
func file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_init() {
	if File_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDesc), len(file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto = out.File
	file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_goTypes = nil
	file_google_ads_googleads_v22_enums_third_party_brand_safety_integration_partner_proto_depIdxs = nil
}
