// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/enums/third_party_reach_integration_partner.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing available third party integration partners for reach
// verification.
type ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner int32

const (
	// Not specified.
	ThirdPartyReachIntegrationPartnerEnum_UNSPECIFIED ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 0
	// Used for return value only. Represents value unknown in this version.
	ThirdPartyReachIntegrationPartnerEnum_UNKNOWN ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 1
	// Nielsen.
	ThirdPartyReachIntegrationPartnerEnum_NIELSEN ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 2
	// Comscore.
	ThirdPartyReachIntegrationPartnerEnum_COMSCORE ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 3
	// Kantar.
	ThirdPartyReachIntegrationPartnerEnum_KANTAR_MILLWARD_BROWN ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 4
	// Video Research.
	ThirdPartyReachIntegrationPartnerEnum_VIDEO_RESEARCH ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 5
	// Gemius.
	ThirdPartyReachIntegrationPartnerEnum_GEMIUS ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 6
	// MediaScope.
	ThirdPartyReachIntegrationPartnerEnum_MEDIA_SCOPE ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 7
	// AudienceProject
	ThirdPartyReachIntegrationPartnerEnum_AUDIENCE_PROJECT ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 8
	// VideoAmp
	ThirdPartyReachIntegrationPartnerEnum_VIDEO_AMP ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 9
	// iSpot.tv
	ThirdPartyReachIntegrationPartnerEnum_ISPOT_TV ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner = 10
)

// Enum value maps for ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner.
var (
	ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "UNKNOWN",
		2:  "NIELSEN",
		3:  "COMSCORE",
		4:  "KANTAR_MILLWARD_BROWN",
		5:  "VIDEO_RESEARCH",
		6:  "GEMIUS",
		7:  "MEDIA_SCOPE",
		8:  "AUDIENCE_PROJECT",
		9:  "VIDEO_AMP",
		10: "ISPOT_TV",
	}
	ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner_value = map[string]int32{
		"UNSPECIFIED":           0,
		"UNKNOWN":               1,
		"NIELSEN":               2,
		"COMSCORE":              3,
		"KANTAR_MILLWARD_BROWN": 4,
		"VIDEO_RESEARCH":        5,
		"GEMIUS":                6,
		"MEDIA_SCOPE":           7,
		"AUDIENCE_PROJECT":      8,
		"VIDEO_AMP":             9,
		"ISPOT_TV":              10,
	}
)

func (x ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner) Enum() *ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner {
	p := new(ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner)
	*p = x
	return p
}

func (x ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_enumTypes[0].Descriptor()
}

func (ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_enumTypes[0]
}

func (x ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner.Descriptor instead.
func (ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing available third party integration partners for
// reach verification.
type ThirdPartyReachIntegrationPartnerEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThirdPartyReachIntegrationPartnerEnum) Reset() {
	*x = ThirdPartyReachIntegrationPartnerEnum{}
	mi := &file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThirdPartyReachIntegrationPartnerEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPartyReachIntegrationPartnerEnum) ProtoMessage() {}

func (x *ThirdPartyReachIntegrationPartnerEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPartyReachIntegrationPartnerEnum.ProtoReflect.Descriptor instead.
func (*ThirdPartyReachIntegrationPartnerEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDesc = "" +
	"\n" +
	"Jgoogle/ads/googleads/v22/enums/third_party_reach_integration_partner.proto\x12\x1egoogle.ads.googleads.v22.enums\"\x85\x02\n" +
	"%ThirdPartyReachIntegrationPartnerEnum\"\xdb\x01\n" +
	"!ThirdPartyReachIntegrationPartner\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\v\n" +
	"\aNIELSEN\x10\x02\x12\f\n" +
	"\bCOMSCORE\x10\x03\x12\x19\n" +
	"\x15KANTAR_MILLWARD_BROWN\x10\x04\x12\x12\n" +
	"\x0eVIDEO_RESEARCH\x10\x05\x12\n" +
	"\n" +
	"\x06GEMIUS\x10\x06\x12\x0f\n" +
	"\vMEDIA_SCOPE\x10\a\x12\x14\n" +
	"\x10AUDIENCE_PROJECT\x10\b\x12\r\n" +
	"\tVIDEO_AMP\x10\t\x12\f\n" +
	"\bISPOT_TV\x10\n" +
	"B\x80\x02\n" +
	"\"com.google.ads.googleads.v22.enumsB&ThirdPartyReachIntegrationPartnerProtoP\x01ZCgithub.com/Optable/google-ads-pb/protogen/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDesc), len(file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDescData
}

var file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_goTypes = []any{
	(ThirdPartyReachIntegrationPartnerEnum_ThirdPartyReachIntegrationPartner)(0), // 0: google.ads.googleads.v22.enums.ThirdPartyReachIntegrationPartnerEnum.ThirdPartyReachIntegrationPartner
	(*ThirdPartyReachIntegrationPartnerEnum)(nil),                                // 1: google.ads.googleads.v22.enums.ThirdPartyReachIntegrationPartnerEnum
}
var file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_init() }
func file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_init() {
	if File_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDesc), len(file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto = out.File
	file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_goTypes = nil
	file_google_ads_googleads_v22_enums_third_party_reach_integration_partner_proto_depIdxs = nil
}
