// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/enums/video_ad_sequence_interaction_type.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing an interaction between a viewer and a video in a video ad
// sequence.
type VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType int32

const (
	// Not specified.
	VideoAdSequenceInteractionTypeEnum_UNSPECIFIED VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType = 0
	// Used for return value only. Represents value unknown in this version.
	VideoAdSequenceInteractionTypeEnum_UNKNOWN VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType = 1
	// The viewer engaged with or watched at least 30 seconds of the ad (or the
	// entire ad, if it was less than 30 seconds). Only available for campaigns
	// using Target CPM as the bidding strategy and skippable in-stream ads as
	// the ad format.
	VideoAdSequenceInteractionTypeEnum_PAID_VIEW VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType = 2
	// The viewer skipped the ad. Only available for campaigns using Target CPM
	// as the bidding strategy and skippable in-stream ads as the ad format.
	VideoAdSequenceInteractionTypeEnum_SKIP VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType = 3
	// The ad was shown to the viewer.
	VideoAdSequenceInteractionTypeEnum_IMPRESSION VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType = 4
	// An ad impression that was not immediately skipped, but didn't reach the
	// billable event either.
	VideoAdSequenceInteractionTypeEnum_ENGAGED_IMPRESSION VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType = 5
)

// Enum value maps for VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType.
var (
	VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "PAID_VIEW",
		3: "SKIP",
		4: "IMPRESSION",
		5: "ENGAGED_IMPRESSION",
	}
	VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType_value = map[string]int32{
		"UNSPECIFIED":        0,
		"UNKNOWN":            1,
		"PAID_VIEW":          2,
		"SKIP":               3,
		"IMPRESSION":         4,
		"ENGAGED_IMPRESSION": 5,
	}
)

func (x VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType) Enum() *VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType {
	p := new(VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType)
	*p = x
	return p
}

func (x VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_enumTypes[0].Descriptor()
}

func (VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_enumTypes[0]
}

func (x VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType.Descriptor instead.
func (VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing an interaction between a viewer and a video in
// a video ad sequence.
type VideoAdSequenceInteractionTypeEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoAdSequenceInteractionTypeEnum) Reset() {
	*x = VideoAdSequenceInteractionTypeEnum{}
	mi := &file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoAdSequenceInteractionTypeEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoAdSequenceInteractionTypeEnum) ProtoMessage() {}

func (x *VideoAdSequenceInteractionTypeEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoAdSequenceInteractionTypeEnum.ProtoReflect.Descriptor instead.
func (*VideoAdSequenceInteractionTypeEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDesc = "" +
	"\n" +
	"Ggoogle/ads/googleads/v22/enums/video_ad_sequence_interaction_type.proto\x12\x1egoogle.ads.googleads.v22.enums\"\xa5\x01\n" +
	"\"VideoAdSequenceInteractionTypeEnum\"\x7f\n" +
	"\x1eVideoAdSequenceInteractionType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\r\n" +
	"\tPAID_VIEW\x10\x02\x12\b\n" +
	"\x04SKIP\x10\x03\x12\x0e\n" +
	"\n" +
	"IMPRESSION\x10\x04\x12\x16\n" +
	"\x12ENGAGED_IMPRESSION\x10\x05B\xfd\x01\n" +
	"\"com.google.ads.googleads.v22.enumsB#VideoAdSequenceInteractionTypeProtoP\x01ZCgithub.com/Optable/google-ads-pb/protogen/enums;enums\xa2\x02\x03GAA\xaa\x02\x1eGoogle.Ads.GoogleAds.V22.Enums\xca\x02\x1eGoogle\\Ads\\GoogleAds\\V22\\Enums\xea\x02\"Google::Ads::GoogleAds::V22::Enumsb\x06proto3"

var (
	file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDesc), len(file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDescData
}

var file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_goTypes = []any{
	(VideoAdSequenceInteractionTypeEnum_VideoAdSequenceInteractionType)(0), // 0: google.ads.googleads.v22.enums.VideoAdSequenceInteractionTypeEnum.VideoAdSequenceInteractionType
	(*VideoAdSequenceInteractionTypeEnum)(nil),                             // 1: google.ads.googleads.v22.enums.VideoAdSequenceInteractionTypeEnum
}
var file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_init() }
func file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_init() {
	if File_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDesc), len(file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto = out.File
	file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_goTypes = nil
	file_google_ads_googleads_v22_enums_video_ad_sequence_interaction_type_proto_depIdxs = nil
}
