// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/services/asset_generation_service.proto

package services

import (
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [AssetGenerationService.GenerateText][google.ads.googleads.v22.services.AssetGenerationService.GenerateText]
type GenerateTextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the customer to generate assets for. Required.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Required. Which field types text is being generated for. Supported values
	// are: HEADLINE, LONG_HEADLINE, DESCRIPTION. Required.
	AssetFieldTypes []enums.AssetFieldTypeEnum_AssetFieldType `protobuf:"varint,2,rep,packed,name=asset_field_types,json=assetFieldTypes,proto3,enum=google.ads.googleads.v22.enums.AssetFieldTypeEnum_AssetFieldType" json:"asset_field_types,omitempty"`
	// Optional. Final url to use as a source for generating assets.
	// Required if existing_generation_context is not provided
	// or does not have a final url associated with it.
	FinalUrl string `protobuf:"bytes,5,opt,name=final_url,json=finalUrl,proto3" json:"final_url,omitempty"`
	// Optional. A freeform description of what assets should be generated.
	// The string length must be between 1 and 1500, inclusive.
	FreeformPrompt string `protobuf:"bytes,6,opt,name=freeform_prompt,json=freeformPrompt,proto3" json:"freeform_prompt,omitempty"`
	// Optional. A freeform list of keywords that are relevant,
	// used to inform asset generation.
	Keywords []string `protobuf:"bytes,7,rep,name=keywords,proto3" json:"keywords,omitempty"`
	// Additional context to guide the generation process.
	//
	// Types that are valid to be assigned to Context:
	//
	//	*GenerateTextRequest_ExistingGenerationContext
	//	*GenerateTextRequest_AdvertisingChannelType
	Context       isGenerateTextRequest_Context `protobuf_oneof:"context"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTextRequest) Reset() {
	*x = GenerateTextRequest{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextRequest) ProtoMessage() {}

func (x *GenerateTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextRequest.ProtoReflect.Descriptor instead.
func (*GenerateTextRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTextRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GenerateTextRequest) GetAssetFieldTypes() []enums.AssetFieldTypeEnum_AssetFieldType {
	if x != nil {
		return x.AssetFieldTypes
	}
	return nil
}

func (x *GenerateTextRequest) GetFinalUrl() string {
	if x != nil {
		return x.FinalUrl
	}
	return ""
}

func (x *GenerateTextRequest) GetFreeformPrompt() string {
	if x != nil {
		return x.FreeformPrompt
	}
	return ""
}

func (x *GenerateTextRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *GenerateTextRequest) GetContext() isGenerateTextRequest_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GenerateTextRequest) GetExistingGenerationContext() *AssetGenerationExistingContext {
	if x != nil {
		if x, ok := x.Context.(*GenerateTextRequest_ExistingGenerationContext); ok {
			return x.ExistingGenerationContext
		}
	}
	return nil
}

func (x *GenerateTextRequest) GetAdvertisingChannelType() enums.AdvertisingChannelTypeEnum_AdvertisingChannelType {
	if x != nil {
		if x, ok := x.Context.(*GenerateTextRequest_AdvertisingChannelType); ok {
			return x.AdvertisingChannelType
		}
	}
	return enums.AdvertisingChannelTypeEnum_AdvertisingChannelType(0)
}

type isGenerateTextRequest_Context interface {
	isGenerateTextRequest_Context()
}

type GenerateTextRequest_ExistingGenerationContext struct {
	// Optional. The setting for which assets are being generated, such as an
	// existing AssetGroup or AdGroupAd.
	ExistingGenerationContext *AssetGenerationExistingContext `protobuf:"bytes,3,opt,name=existing_generation_context,json=existingGenerationContext,proto3,oneof"`
}

type GenerateTextRequest_AdvertisingChannelType struct {
	// Optional. The advertising channel for which to generate assets. Required
	// if existing_context is not provided.
	//
	// Supported channel types:
	// SEARCH, PERFORMANCE_MAX, DISPLAY, and DEMAND_GEN
	AdvertisingChannelType enums.AdvertisingChannelTypeEnum_AdvertisingChannelType `protobuf:"varint,4,opt,name=advertising_channel_type,json=advertisingChannelType,proto3,enum=google.ads.googleads.v22.enums.AdvertisingChannelTypeEnum_AdvertisingChannelType,oneof"`
}

func (*GenerateTextRequest_ExistingGenerationContext) isGenerateTextRequest_Context() {}

func (*GenerateTextRequest_AdvertisingChannelType) isGenerateTextRequest_Context() {}

// Response message for
// [AssetGenerationService.GenerateText][google.ads.googleads.v22.services.AssetGenerationService.GenerateText]
type GenerateTextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of text that was generated and the field type to use it as.
	GeneratedText []*GeneratedText `protobuf:"bytes,1,rep,name=generated_text,json=generatedText,proto3" json:"generated_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTextResponse) Reset() {
	*x = GenerateTextResponse{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTextResponse) ProtoMessage() {}

func (x *GenerateTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTextResponse.ProtoReflect.Descriptor instead.
func (*GenerateTextResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTextResponse) GetGeneratedText() []*GeneratedText {
	if x != nil {
		return x.GeneratedText
	}
	return nil
}

// Data and metadata about a piece of generated text.
type GeneratedText struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A string of text that was generated.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// The type of asset this text is intended to be used as.
	AssetFieldType enums.AssetFieldTypeEnum_AssetFieldType `protobuf:"varint,2,opt,name=asset_field_type,json=assetFieldType,proto3,enum=google.ads.googleads.v22.enums.AssetFieldTypeEnum_AssetFieldType" json:"asset_field_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GeneratedText) Reset() {
	*x = GeneratedText{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedText) ProtoMessage() {}

func (x *GeneratedText) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedText.ProtoReflect.Descriptor instead.
func (*GeneratedText) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{2}
}

func (x *GeneratedText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GeneratedText) GetAssetFieldType() enums.AssetFieldTypeEnum_AssetFieldType {
	if x != nil {
		return x.AssetFieldType
	}
	return enums.AssetFieldTypeEnum_AssetFieldType(0)
}

// Request message for
// [AssetGenerationService.GenerateImages][google.ads.googleads.v22.services.AssetGenerationService.GenerateImages]
type GenerateImagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the customer for whom the images are being generated.
	// Required.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Optional. Output field types for generated images. Supported values are
	// MARKETING_IMAGE, SQUARE_MARKETING_IMAGE, PORTRAIT_MARKETING_IMAGE, and
	// TALL_PORTRAIT_MARKETING_IMAGE. All specified field types must be
	// compatible with the `advertising_channel_type` or
	// `existing_generation_context` (whichever is set). If no field types are
	// provided, images will be generated for all compatible field types.
	AssetFieldTypes []enums.AssetFieldTypeEnum_AssetFieldType `protobuf:"varint,4,rep,packed,name=asset_field_types,json=assetFieldTypes,proto3,enum=google.ads.googleads.v22.enums.AssetFieldTypeEnum_AssetFieldType" json:"asset_field_types,omitempty"`
	// Additional context to guide image generation.
	//
	// Types that are valid to be assigned to Context:
	//
	//	*GenerateImagesRequest_AdvertisingChannelType
	Context isGenerateImagesRequest_Context `protobuf_oneof:"context"`
	// Type of image generation to apply. Required.
	//
	// Types that are valid to be assigned to GenerationType:
	//
	//	*GenerateImagesRequest_FinalUrlGeneration
	//	*GenerateImagesRequest_FreeformGeneration
	//	*GenerateImagesRequest_ProductRecontextGeneration
	GenerationType isGenerateImagesRequest_GenerationType `protobuf_oneof:"generation_type"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateImagesRequest) Reset() {
	*x = GenerateImagesRequest{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImagesRequest) ProtoMessage() {}

func (x *GenerateImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImagesRequest.ProtoReflect.Descriptor instead.
func (*GenerateImagesRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateImagesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GenerateImagesRequest) GetAssetFieldTypes() []enums.AssetFieldTypeEnum_AssetFieldType {
	if x != nil {
		return x.AssetFieldTypes
	}
	return nil
}

func (x *GenerateImagesRequest) GetContext() isGenerateImagesRequest_Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GenerateImagesRequest) GetAdvertisingChannelType() enums.AdvertisingChannelTypeEnum_AdvertisingChannelType {
	if x != nil {
		if x, ok := x.Context.(*GenerateImagesRequest_AdvertisingChannelType); ok {
			return x.AdvertisingChannelType
		}
	}
	return enums.AdvertisingChannelTypeEnum_AdvertisingChannelType(0)
}

func (x *GenerateImagesRequest) GetGenerationType() isGenerateImagesRequest_GenerationType {
	if x != nil {
		return x.GenerationType
	}
	return nil
}

func (x *GenerateImagesRequest) GetFinalUrlGeneration() *FinalUrlImageGenerationInput {
	if x != nil {
		if x, ok := x.GenerationType.(*GenerateImagesRequest_FinalUrlGeneration); ok {
			return x.FinalUrlGeneration
		}
	}
	return nil
}

func (x *GenerateImagesRequest) GetFreeformGeneration() *FreeformImageGenerationInput {
	if x != nil {
		if x, ok := x.GenerationType.(*GenerateImagesRequest_FreeformGeneration); ok {
			return x.FreeformGeneration
		}
	}
	return nil
}

func (x *GenerateImagesRequest) GetProductRecontextGeneration() *ProductRecontextGenerationImageInput {
	if x != nil {
		if x, ok := x.GenerationType.(*GenerateImagesRequest_ProductRecontextGeneration); ok {
			return x.ProductRecontextGeneration
		}
	}
	return nil
}

type isGenerateImagesRequest_Context interface {
	isGenerateImagesRequest_Context()
}

type GenerateImagesRequest_AdvertisingChannelType struct {
	// Optional. The advertising channel type for which the images are being
	// generated. This field is required if `existing_generation_context` is not
	// provided. Supported channel types include SEARCH, PERFORMANCE_MAX,
	// DISPLAY, and DEMAND_GEN.
	AdvertisingChannelType enums.AdvertisingChannelTypeEnum_AdvertisingChannelType `protobuf:"varint,2,opt,name=advertising_channel_type,json=advertisingChannelType,proto3,enum=google.ads.googleads.v22.enums.AdvertisingChannelTypeEnum_AdvertisingChannelType,oneof"`
}

func (*GenerateImagesRequest_AdvertisingChannelType) isGenerateImagesRequest_Context() {}

type isGenerateImagesRequest_GenerationType interface {
	isGenerateImagesRequest_GenerationType()
}

type GenerateImagesRequest_FinalUrlGeneration struct {
	// Optional. Generate images from a final url.
	FinalUrlGeneration *FinalUrlImageGenerationInput `protobuf:"bytes,5,opt,name=final_url_generation,json=finalUrlGeneration,proto3,oneof"`
}

type GenerateImagesRequest_FreeformGeneration struct {
	// Optional. Generate images from a freeform prompt.
	FreeformGeneration *FreeformImageGenerationInput `protobuf:"bytes,6,opt,name=freeform_generation,json=freeformGeneration,proto3,oneof"`
}

type GenerateImagesRequest_ProductRecontextGeneration struct {
	// Optional. Generate new images by recontextualizing existing product
	// images.
	ProductRecontextGeneration *ProductRecontextGenerationImageInput `protobuf:"bytes,7,opt,name=product_recontext_generation,json=productRecontextGeneration,proto3,oneof"`
}

func (*GenerateImagesRequest_FinalUrlGeneration) isGenerateImagesRequest_GenerationType() {}

func (*GenerateImagesRequest_FreeformGeneration) isGenerateImagesRequest_GenerationType() {}

func (*GenerateImagesRequest_ProductRecontextGeneration) isGenerateImagesRequest_GenerationType() {}

// Input for guiding image asset generation with a final url.
type FinalUrlImageGenerationInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. A final url to guide the image generation process. Required.
	FinalUrl      string `protobuf:"bytes,1,opt,name=final_url,json=finalUrl,proto3" json:"final_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalUrlImageGenerationInput) Reset() {
	*x = FinalUrlImageGenerationInput{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalUrlImageGenerationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalUrlImageGenerationInput) ProtoMessage() {}

func (x *FinalUrlImageGenerationInput) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalUrlImageGenerationInput.ProtoReflect.Descriptor instead.
func (*FinalUrlImageGenerationInput) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{4}
}

func (x *FinalUrlImageGenerationInput) GetFinalUrl() string {
	if x != nil {
		return x.FinalUrl
	}
	return ""
}

// Input for guiding image asset generation with a freeform prompt.
type FreeformImageGenerationInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. A freeform text description to guide the image generation
	// process. The maximum length is 1500 characters. Required.
	FreeformPrompt string `protobuf:"bytes,1,opt,name=freeform_prompt,json=freeformPrompt,proto3" json:"freeform_prompt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FreeformImageGenerationInput) Reset() {
	*x = FreeformImageGenerationInput{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeformImageGenerationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeformImageGenerationInput) ProtoMessage() {}

func (x *FreeformImageGenerationInput) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeformImageGenerationInput.ProtoReflect.Descriptor instead.
func (*FreeformImageGenerationInput) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{5}
}

func (x *FreeformImageGenerationInput) GetFreeformPrompt() string {
	if x != nil {
		return x.FreeformPrompt
	}
	return ""
}

// Input for generating new images by recontextualizing existing product images.
type ProductRecontextGenerationImageInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. A freeform description of the assets to be generated.
	// Maximum character limit is 1500.
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Required. Product images to use for generating new images.
	// 1-3 images must be provided.
	SourceImages  []*SourceImage `protobuf:"bytes,2,rep,name=source_images,json=sourceImages,proto3" json:"source_images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductRecontextGenerationImageInput) Reset() {
	*x = ProductRecontextGenerationImageInput{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductRecontextGenerationImageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductRecontextGenerationImageInput) ProtoMessage() {}

func (x *ProductRecontextGenerationImageInput) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductRecontextGenerationImageInput.ProtoReflect.Descriptor instead.
func (*ProductRecontextGenerationImageInput) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{6}
}

func (x *ProductRecontextGenerationImageInput) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ProductRecontextGenerationImageInput) GetSourceImages() []*SourceImage {
	if x != nil {
		return x.SourceImages
	}
	return nil
}

// Response message for
// [AssetGenerationService.GenerateImages][google.ads.googleads.v22.services.AssetGenerationService.GenerateImages]
type GenerateImagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Successfully generated images.
	GeneratedImages []*GeneratedImage `protobuf:"bytes,1,rep,name=generated_images,json=generatedImages,proto3" json:"generated_images,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateImagesResponse) Reset() {
	*x = GenerateImagesResponse{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImagesResponse) ProtoMessage() {}

func (x *GenerateImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImagesResponse.ProtoReflect.Descriptor instead.
func (*GenerateImagesResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateImagesResponse) GetGeneratedImages() []*GeneratedImage {
	if x != nil {
		return x.GeneratedImages
	}
	return nil
}

// A source image to be used in the generation process.
type SourceImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The image to be used as a source.
	//
	// Types that are valid to be assigned to Image:
	//
	//	*SourceImage_ImageData
	Image         isSourceImage_Image `protobuf_oneof:"image"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceImage) Reset() {
	*x = SourceImage{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceImage) ProtoMessage() {}

func (x *SourceImage) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceImage.ProtoReflect.Descriptor instead.
func (*SourceImage) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{8}
}

func (x *SourceImage) GetImage() isSourceImage_Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *SourceImage) GetImageData() []byte {
	if x != nil {
		if x, ok := x.Image.(*SourceImage_ImageData); ok {
			return x.ImageData
		}
	}
	return nil
}

type isSourceImage_Image interface {
	isSourceImage_Image()
}

type SourceImage_ImageData struct {
	// Optional. Raw bytes of the image to use.
	ImageData []byte `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3,oneof"`
}

func (*SourceImage_ImageData) isSourceImage_Image() {}

// Generated image data and metadata.
type GeneratedImage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A temporary URL for the generated image.
	ImageTemporaryUrl string `protobuf:"bytes,1,opt,name=image_temporary_url,json=imageTemporaryUrl,proto3" json:"image_temporary_url,omitempty"`
	// The intended field type for this generated image.
	AssetFieldType enums.AssetFieldTypeEnum_AssetFieldType `protobuf:"varint,2,opt,name=asset_field_type,json=assetFieldType,proto3,enum=google.ads.googleads.v22.enums.AssetFieldTypeEnum_AssetFieldType" json:"asset_field_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GeneratedImage) Reset() {
	*x = GeneratedImage{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedImage) ProtoMessage() {}

func (x *GeneratedImage) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedImage.ProtoReflect.Descriptor instead.
func (*GeneratedImage) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{9}
}

func (x *GeneratedImage) GetImageTemporaryUrl() string {
	if x != nil {
		return x.ImageTemporaryUrl
	}
	return ""
}

func (x *GeneratedImage) GetAssetFieldType() enums.AssetFieldTypeEnum_AssetFieldType {
	if x != nil {
		return x.AssetFieldType
	}
	return enums.AssetFieldTypeEnum_AssetFieldType(0)
}

// The context for which assets are being generated, such as an existing
// AssetGroup or AdGroupAd.
type AssetGenerationExistingContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An existing context to generate assets for.
	//
	// Types that are valid to be assigned to ExistingContext:
	//
	//	*AssetGenerationExistingContext_ExistingAssetGroup
	//	*AssetGenerationExistingContext_ExistingAdGroupAd
	ExistingContext isAssetGenerationExistingContext_ExistingContext `protobuf_oneof:"existing_context"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssetGenerationExistingContext) Reset() {
	*x = AssetGenerationExistingContext{}
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetGenerationExistingContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetGenerationExistingContext) ProtoMessage() {}

func (x *AssetGenerationExistingContext) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetGenerationExistingContext.ProtoReflect.Descriptor instead.
func (*AssetGenerationExistingContext) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP(), []int{10}
}

func (x *AssetGenerationExistingContext) GetExistingContext() isAssetGenerationExistingContext_ExistingContext {
	if x != nil {
		return x.ExistingContext
	}
	return nil
}

func (x *AssetGenerationExistingContext) GetExistingAssetGroup() string {
	if x != nil {
		if x, ok := x.ExistingContext.(*AssetGenerationExistingContext_ExistingAssetGroup); ok {
			return x.ExistingAssetGroup
		}
	}
	return ""
}

func (x *AssetGenerationExistingContext) GetExistingAdGroupAd() string {
	if x != nil {
		if x, ok := x.ExistingContext.(*AssetGenerationExistingContext_ExistingAdGroupAd); ok {
			return x.ExistingAdGroupAd
		}
	}
	return ""
}

type isAssetGenerationExistingContext_ExistingContext interface {
	isAssetGenerationExistingContext_ExistingContext()
}

type AssetGenerationExistingContext_ExistingAssetGroup struct {
	// Resource name of an existing AssetGroup for which these assets are being
	// generated.
	ExistingAssetGroup string `protobuf:"bytes,1,opt,name=existing_asset_group,json=existingAssetGroup,proto3,oneof"`
}

type AssetGenerationExistingContext_ExistingAdGroupAd struct {
	// Resource name of an existing AdGroupAd for which these assets are being
	// generated.
	ExistingAdGroupAd string `protobuf:"bytes,2,opt,name=existing_ad_group_ad,json=existingAdGroupAd,proto3,oneof"`
}

func (*AssetGenerationExistingContext_ExistingAssetGroup) isAssetGenerationExistingContext_ExistingContext() {
}

func (*AssetGenerationExistingContext_ExistingAdGroupAd) isAssetGenerationExistingContext_ExistingContext() {
}

var File_google_ads_googleads_v22_services_asset_generation_service_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDesc = "" +
	"\n" +
	"@google/ads/googleads/v22/services/asset_generation_service.proto\x12!google.ads.googleads.v22.services\x1a=google/ads/googleads/v22/enums/advertising_channel_type.proto\x1a5google/ads/googleads/v22/enums/asset_field_type.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xcb\x04\n" +
	"\x13GenerateTextRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12r\n" +
	"\x11asset_field_types\x18\x02 \x03(\x0e2A.google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldTypeB\x03\xe0A\x02R\x0fassetFieldTypes\x12 \n" +
	"\tfinal_url\x18\x05 \x01(\tB\x03\xe0A\x01R\bfinalUrl\x12,\n" +
	"\x0ffreeform_prompt\x18\x06 \x01(\tB\x03\xe0A\x01R\x0efreeformPrompt\x12\x1f\n" +
	"\bkeywords\x18\a \x03(\tB\x03\xe0A\x01R\bkeywords\x12\x88\x01\n" +
	"\x1bexisting_generation_context\x18\x03 \x01(\v2A.google.ads.googleads.v22.services.AssetGenerationExistingContextB\x03\xe0A\x01H\x00R\x19existingGenerationContext\x12\x92\x01\n" +
	"\x18advertising_channel_type\x18\x04 \x01(\x0e2Q.google.ads.googleads.v22.enums.AdvertisingChannelTypeEnum.AdvertisingChannelTypeB\x03\xe0A\x01H\x00R\x16advertisingChannelTypeB\t\n" +
	"\acontext\"o\n" +
	"\x14GenerateTextResponse\x12W\n" +
	"\x0egenerated_text\x18\x01 \x03(\v20.google.ads.googleads.v22.services.GeneratedTextR\rgeneratedText\"\x90\x01\n" +
	"\rGeneratedText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12k\n" +
	"\x10asset_field_type\x18\x02 \x01(\x0e2A.google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldTypeR\x0eassetFieldType\"\xea\x05\n" +
	"\x15GenerateImagesRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12r\n" +
	"\x11asset_field_types\x18\x04 \x03(\x0e2A.google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldTypeB\x03\xe0A\x01R\x0fassetFieldTypes\x12\x92\x01\n" +
	"\x18advertising_channel_type\x18\x02 \x01(\x0e2Q.google.ads.googleads.v22.enums.AdvertisingChannelTypeEnum.AdvertisingChannelTypeB\x03\xe0A\x01H\x00R\x16advertisingChannelType\x12x\n" +
	"\x14final_url_generation\x18\x05 \x01(\v2?.google.ads.googleads.v22.services.FinalUrlImageGenerationInputB\x03\xe0A\x01H\x01R\x12finalUrlGeneration\x12w\n" +
	"\x13freeform_generation\x18\x06 \x01(\v2?.google.ads.googleads.v22.services.FreeformImageGenerationInputB\x03\xe0A\x01H\x01R\x12freeformGeneration\x12\x90\x01\n" +
	"\x1cproduct_recontext_generation\x18\a \x01(\v2G.google.ads.googleads.v22.services.ProductRecontextGenerationImageInputB\x03\xe0A\x01H\x01R\x1aproductRecontextGenerationB\t\n" +
	"\acontextB\x11\n" +
	"\x0fgeneration_type\"@\n" +
	"\x1cFinalUrlImageGenerationInput\x12 \n" +
	"\tfinal_url\x18\x01 \x01(\tB\x03\xe0A\x02R\bfinalUrl\"L\n" +
	"\x1cFreeformImageGenerationInput\x12,\n" +
	"\x0ffreeform_prompt\x18\x01 \x01(\tB\x03\xe0A\x02R\x0efreeformPrompt\"\x9d\x01\n" +
	"$ProductRecontextGenerationImageInput\x12\x1b\n" +
	"\x06prompt\x18\x01 \x01(\tB\x03\xe0A\x01R\x06prompt\x12X\n" +
	"\rsource_images\x18\x02 \x03(\v2..google.ads.googleads.v22.services.SourceImageB\x03\xe0A\x02R\fsourceImages\"v\n" +
	"\x16GenerateImagesResponse\x12\\\n" +
	"\x10generated_images\x18\x01 \x03(\v21.google.ads.googleads.v22.services.GeneratedImageR\x0fgeneratedImages\"<\n" +
	"\vSourceImage\x12$\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fB\x03\xe0A\x01H\x00R\timageDataB\a\n" +
	"\x05image\"\xad\x01\n" +
	"\x0eGeneratedImage\x12.\n" +
	"\x13image_temporary_url\x18\x01 \x01(\tR\x11imageTemporaryUrl\x12k\n" +
	"\x10asset_field_type\x18\x02 \x01(\x0e2A.google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldTypeR\x0eassetFieldType\"\xee\x01\n" +
	"\x1eAssetGenerationExistingContext\x12\\\n" +
	"\x14existing_asset_group\x18\x01 \x01(\tB(\xfaA%\n" +
	"#googleads.googleapis.com/AssetGroupH\x00R\x12existingAssetGroup\x12Z\n" +
	"\x14existing_ad_group_ad\x18\x02 \x01(\tB'\xfaA$\n" +
	"\"googleads.googleapis.com/AdGroupAdH\x00R\x11existingAdGroupAdB\x12\n" +
	"\x10existing_context2\xfd\x03\n" +
	"\x16AssetGenerationService\x12\xc8\x01\n" +
	"\fGenerateText\x126.google.ads.googleads.v22.services.GenerateTextRequest\x1a7.google.ads.googleads.v22.services.GenerateTextResponse\"G\x82\xd3\xe4\x93\x02A:\x01*\"</v22/customers/{customer_id=*}/assetGenerations:generateText\x12\xd0\x01\n" +
	"\x0eGenerateImages\x128.google.ads.googleads.v22.services.GenerateImagesRequest\x1a9.google.ads.googleads.v22.services.GenerateImagesResponse\"I\x82\xd3\xe4\x93\x02C:\x01*\">/v22/customers/{customer_id=*}/assetGenerations:generateImages\x1aE\xcaA\x18googleads.googleapis.com\xd2A'https://www.googleapis.com/auth/adwordsB\x87\x02\n" +
	"%com.google.ads.googleads.v22.servicesB\x1bAssetGenerationServiceProtoP\x01ZIgithub.com/Optable/google-ads-pb/protogen/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V22.Services\xca\x02!Google\\Ads\\GoogleAds\\V22\\Services\xea\x02%Google::Ads::GoogleAds::V22::Servicesb\x06proto3"

var (
	file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDesc), len(file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDescData
}

var file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_google_ads_googleads_v22_services_asset_generation_service_proto_goTypes = []any{
	(*GenerateTextRequest)(nil),                                  // 0: google.ads.googleads.v22.services.GenerateTextRequest
	(*GenerateTextResponse)(nil),                                 // 1: google.ads.googleads.v22.services.GenerateTextResponse
	(*GeneratedText)(nil),                                        // 2: google.ads.googleads.v22.services.GeneratedText
	(*GenerateImagesRequest)(nil),                                // 3: google.ads.googleads.v22.services.GenerateImagesRequest
	(*FinalUrlImageGenerationInput)(nil),                         // 4: google.ads.googleads.v22.services.FinalUrlImageGenerationInput
	(*FreeformImageGenerationInput)(nil),                         // 5: google.ads.googleads.v22.services.FreeformImageGenerationInput
	(*ProductRecontextGenerationImageInput)(nil),                 // 6: google.ads.googleads.v22.services.ProductRecontextGenerationImageInput
	(*GenerateImagesResponse)(nil),                               // 7: google.ads.googleads.v22.services.GenerateImagesResponse
	(*SourceImage)(nil),                                          // 8: google.ads.googleads.v22.services.SourceImage
	(*GeneratedImage)(nil),                                       // 9: google.ads.googleads.v22.services.GeneratedImage
	(*AssetGenerationExistingContext)(nil),                       // 10: google.ads.googleads.v22.services.AssetGenerationExistingContext
	(enums.AssetFieldTypeEnum_AssetFieldType)(0),                 // 11: google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	(enums.AdvertisingChannelTypeEnum_AdvertisingChannelType)(0), // 12: google.ads.googleads.v22.enums.AdvertisingChannelTypeEnum.AdvertisingChannelType
}
var file_google_ads_googleads_v22_services_asset_generation_service_proto_depIdxs = []int32{
	11, // 0: google.ads.googleads.v22.services.GenerateTextRequest.asset_field_types:type_name -> google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	10, // 1: google.ads.googleads.v22.services.GenerateTextRequest.existing_generation_context:type_name -> google.ads.googleads.v22.services.AssetGenerationExistingContext
	12, // 2: google.ads.googleads.v22.services.GenerateTextRequest.advertising_channel_type:type_name -> google.ads.googleads.v22.enums.AdvertisingChannelTypeEnum.AdvertisingChannelType
	2,  // 3: google.ads.googleads.v22.services.GenerateTextResponse.generated_text:type_name -> google.ads.googleads.v22.services.GeneratedText
	11, // 4: google.ads.googleads.v22.services.GeneratedText.asset_field_type:type_name -> google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	11, // 5: google.ads.googleads.v22.services.GenerateImagesRequest.asset_field_types:type_name -> google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	12, // 6: google.ads.googleads.v22.services.GenerateImagesRequest.advertising_channel_type:type_name -> google.ads.googleads.v22.enums.AdvertisingChannelTypeEnum.AdvertisingChannelType
	4,  // 7: google.ads.googleads.v22.services.GenerateImagesRequest.final_url_generation:type_name -> google.ads.googleads.v22.services.FinalUrlImageGenerationInput
	5,  // 8: google.ads.googleads.v22.services.GenerateImagesRequest.freeform_generation:type_name -> google.ads.googleads.v22.services.FreeformImageGenerationInput
	6,  // 9: google.ads.googleads.v22.services.GenerateImagesRequest.product_recontext_generation:type_name -> google.ads.googleads.v22.services.ProductRecontextGenerationImageInput
	8,  // 10: google.ads.googleads.v22.services.ProductRecontextGenerationImageInput.source_images:type_name -> google.ads.googleads.v22.services.SourceImage
	9,  // 11: google.ads.googleads.v22.services.GenerateImagesResponse.generated_images:type_name -> google.ads.googleads.v22.services.GeneratedImage
	11, // 12: google.ads.googleads.v22.services.GeneratedImage.asset_field_type:type_name -> google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	0,  // 13: google.ads.googleads.v22.services.AssetGenerationService.GenerateText:input_type -> google.ads.googleads.v22.services.GenerateTextRequest
	3,  // 14: google.ads.googleads.v22.services.AssetGenerationService.GenerateImages:input_type -> google.ads.googleads.v22.services.GenerateImagesRequest
	1,  // 15: google.ads.googleads.v22.services.AssetGenerationService.GenerateText:output_type -> google.ads.googleads.v22.services.GenerateTextResponse
	7,  // 16: google.ads.googleads.v22.services.AssetGenerationService.GenerateImages:output_type -> google.ads.googleads.v22.services.GenerateImagesResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_services_asset_generation_service_proto_init() }
func file_google_ads_googleads_v22_services_asset_generation_service_proto_init() {
	if File_google_ads_googleads_v22_services_asset_generation_service_proto != nil {
		return
	}
	file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[0].OneofWrappers = []any{
		(*GenerateTextRequest_ExistingGenerationContext)(nil),
		(*GenerateTextRequest_AdvertisingChannelType)(nil),
	}
	file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[3].OneofWrappers = []any{
		(*GenerateImagesRequest_AdvertisingChannelType)(nil),
		(*GenerateImagesRequest_FinalUrlGeneration)(nil),
		(*GenerateImagesRequest_FreeformGeneration)(nil),
		(*GenerateImagesRequest_ProductRecontextGeneration)(nil),
	}
	file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[8].OneofWrappers = []any{
		(*SourceImage_ImageData)(nil),
	}
	file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes[10].OneofWrappers = []any{
		(*AssetGenerationExistingContext_ExistingAssetGroup)(nil),
		(*AssetGenerationExistingContext_ExistingAdGroupAd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDesc), len(file_google_ads_googleads_v22_services_asset_generation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_googleads_v22_services_asset_generation_service_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_services_asset_generation_service_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_services_asset_generation_service_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_services_asset_generation_service_proto = out.File
	file_google_ads_googleads_v22_services_asset_generation_service_proto_goTypes = nil
	file_google_ads_googleads_v22_services_asset_generation_service_proto_depIdxs = nil
}
