// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/services/automatically_created_asset_removal_service.proto

package services

import (
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [AutomaticallyCreatedAssetRemovalService.RemoveCampaignAutomaticallyCreatedAsset][google.ads.googleads.v22.services.AutomaticallyCreatedAssetRemovalService.RemoveCampaignAutomaticallyCreatedAsset].
type RemoveCampaignAutomaticallyCreatedAssetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the customer whose assets are being removed.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Required. The list of operations.
	Operations []*RemoveCampaignAutomaticallyCreatedAssetOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// Required. If true, successful operations will be carried out and invalid
	// operations will return errors. If false, all operations will be carried
	// out in one transaction if and only if they are all valid.
	PartialFailure bool `protobuf:"varint,3,opt,name=partial_failure,json=partialFailure,proto3" json:"partial_failure,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveCampaignAutomaticallyCreatedAssetRequest) Reset() {
	*x = RemoveCampaignAutomaticallyCreatedAssetRequest{}
	mi := &file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCampaignAutomaticallyCreatedAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCampaignAutomaticallyCreatedAssetRequest) ProtoMessage() {}

func (x *RemoveCampaignAutomaticallyCreatedAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCampaignAutomaticallyCreatedAssetRequest.ProtoReflect.Descriptor instead.
func (*RemoveCampaignAutomaticallyCreatedAssetRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveCampaignAutomaticallyCreatedAssetRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *RemoveCampaignAutomaticallyCreatedAssetRequest) GetOperations() []*RemoveCampaignAutomaticallyCreatedAssetOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *RemoveCampaignAutomaticallyCreatedAssetRequest) GetPartialFailure() bool {
	if x != nil {
		return x.PartialFailure
	}
	return false
}

// A single operation to remove an automatically created asset from a campaign.
type RemoveCampaignAutomaticallyCreatedAssetOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The resource name of the campaign.
	Campaign string `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	// Required. The resource name of the asset to remove.
	Asset string `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	// Required. The field type of the asset to remove.
	FieldType     enums.AssetFieldTypeEnum_AssetFieldType `protobuf:"varint,3,opt,name=field_type,json=fieldType,proto3,enum=google.ads.googleads.v22.enums.AssetFieldTypeEnum_AssetFieldType" json:"field_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCampaignAutomaticallyCreatedAssetOperation) Reset() {
	*x = RemoveCampaignAutomaticallyCreatedAssetOperation{}
	mi := &file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCampaignAutomaticallyCreatedAssetOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCampaignAutomaticallyCreatedAssetOperation) ProtoMessage() {}

func (x *RemoveCampaignAutomaticallyCreatedAssetOperation) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCampaignAutomaticallyCreatedAssetOperation.ProtoReflect.Descriptor instead.
func (*RemoveCampaignAutomaticallyCreatedAssetOperation) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveCampaignAutomaticallyCreatedAssetOperation) GetCampaign() string {
	if x != nil {
		return x.Campaign
	}
	return ""
}

func (x *RemoveCampaignAutomaticallyCreatedAssetOperation) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *RemoveCampaignAutomaticallyCreatedAssetOperation) GetFieldType() enums.AssetFieldTypeEnum_AssetFieldType {
	if x != nil {
		return x.FieldType
	}
	return enums.AssetFieldTypeEnum_AssetFieldType(0)
}

// Response message for
// [AutomaticallyCreatedAssetRemovalService.RemoveCampaignAutomaticallyCreatedAsset][google.ads.googleads.v22.services.AutomaticallyCreatedAssetRemovalService.RemoveCampaignAutomaticallyCreatedAsset].
type RemoveCampaignAutomaticallyCreatedAssetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Errors that pertain to AutomaticallyCreatedAssetRemoval failures in the
	// partial failure mode. Returned when all errors occur inside the operations.
	// If any errors occur outside the operations (for example, auth errors), RPC
	// level error will be returned. See
	// https://developers.google.com/google-ads/api/docs/best-practices/partial-failures
	// for more information about partial failure.
	PartialFailureError *status.Status `protobuf:"bytes,1,opt,name=partial_failure_error,json=partialFailureError,proto3" json:"partial_failure_error,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RemoveCampaignAutomaticallyCreatedAssetResponse) Reset() {
	*x = RemoveCampaignAutomaticallyCreatedAssetResponse{}
	mi := &file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCampaignAutomaticallyCreatedAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCampaignAutomaticallyCreatedAssetResponse) ProtoMessage() {}

func (x *RemoveCampaignAutomaticallyCreatedAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCampaignAutomaticallyCreatedAssetResponse.ProtoReflect.Descriptor instead.
func (*RemoveCampaignAutomaticallyCreatedAssetResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveCampaignAutomaticallyCreatedAssetResponse) GetPartialFailureError() *status.Status {
	if x != nil {
		return x.PartialFailureError
	}
	return nil
}

var File_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDesc = "" +
	"\n" +
	"Sgoogle/ads/googleads/v22/services/automatically_created_asset_removal_service.proto\x12!google.ads.googleads.v22.services\x1a5google/ads/googleads/v22/enums/asset_field_type.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x17google/rpc/status.proto\"\xfe\x01\n" +
	".RemoveCampaignAutomaticallyCreatedAssetRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12x\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2S.google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetOperationB\x03\xe0A\x02R\n" +
	"operations\x12,\n" +
	"\x0fpartial_failure\x18\x03 \x01(\bB\x03\xe0A\x02R\x0epartialFailure\"\xd5\x01\n" +
	"0RemoveCampaignAutomaticallyCreatedAssetOperation\x12\x1f\n" +
	"\bcampaign\x18\x01 \x01(\tB\x03\xe0A\x02R\bcampaign\x12\x19\n" +
	"\x05asset\x18\x02 \x01(\tB\x03\xe0A\x02R\x05asset\x12e\n" +
	"\n" +
	"field_type\x18\x03 \x01(\x0e2A.google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldTypeB\x03\xe0A\x02R\tfieldType\"y\n" +
	"/RemoveCampaignAutomaticallyCreatedAssetResponse\x12F\n" +
	"\x15partial_failure_error\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x13partialFailureError2\xbf\x03\n" +
	"'AutomaticallyCreatedAssetRemovalService\x12\xcc\x02\n" +
	"'RemoveCampaignAutomaticallyCreatedAsset\x12Q.google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetRequest\x1aR.google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetResponse\"z\xdaA&customer_id,operations,partial_failure\x82\xd3\xe4\x93\x02K:\x01*\"F/v22/customers/{customer_id=*}:removeCampaignAutomaticallyCreatedAsset\x1aE\xcaA\x18googleads.googleapis.com\xd2A'https://www.googleapis.com/auth/adwordsB\x98\x02\n" +
	"%com.google.ads.googleads.v22.servicesB,AutomaticallyCreatedAssetRemovalServiceProtoP\x01ZIgithub.com/Optable/google-ads-pb/protogen/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V22.Services\xca\x02!Google\\Ads\\GoogleAds\\V22\\Services\xea\x02%Google::Ads::GoogleAds::V22::Servicesb\x06proto3"

var (
	file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDesc), len(file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDescData
}

var file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_goTypes = []any{
	(*RemoveCampaignAutomaticallyCreatedAssetRequest)(nil),   // 0: google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetRequest
	(*RemoveCampaignAutomaticallyCreatedAssetOperation)(nil), // 1: google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetOperation
	(*RemoveCampaignAutomaticallyCreatedAssetResponse)(nil),  // 2: google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetResponse
	(enums.AssetFieldTypeEnum_AssetFieldType)(0),             // 3: google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	(*status.Status)(nil),                                    // 4: google.rpc.Status
}
var file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetRequest.operations:type_name -> google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetOperation
	3, // 1: google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetOperation.field_type:type_name -> google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	4, // 2: google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetResponse.partial_failure_error:type_name -> google.rpc.Status
	0, // 3: google.ads.googleads.v22.services.AutomaticallyCreatedAssetRemovalService.RemoveCampaignAutomaticallyCreatedAsset:input_type -> google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetRequest
	2, // 4: google.ads.googleads.v22.services.AutomaticallyCreatedAssetRemovalService.RemoveCampaignAutomaticallyCreatedAsset:output_type -> google.ads.googleads.v22.services.RemoveCampaignAutomaticallyCreatedAssetResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_init()
}
func file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_init() {
	if File_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDesc), len(file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto = out.File
	file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_goTypes = nil
	file_google_ads_googleads_v22_services_automatically_created_asset_removal_service_proto_depIdxs = nil
}
