// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/services/campaign_goal_config_service.proto

package services

import (
	resources "github.com/Optable/google-ads-pb/protogen/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [CampaignGoalConfigService.MutateCampaignGoalConfigs][google.ads.googleads.v22.services.CampaignGoalConfigService.MutateCampaignGoalConfigs].
type MutateCampaignGoalConfigsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the customer whose campaign goal configs are being
	// modified.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Required. The list of operations to perform on the campaign goal configs.
	Operations []*CampaignGoalConfigOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// Optional. If true, successful operations will be carried out and invalid
	// operations will return errors. If false, all operations will be carried
	// out in one transaction if and only if they are all valid.
	// Default is false.
	PartialFailure bool `protobuf:"varint,3,opt,name=partial_failure,json=partialFailure,proto3" json:"partial_failure,omitempty"`
	// Optional. If true, the request is validated but not executed. Only errors
	// are returned, not results.
	ValidateOnly  bool `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateCampaignGoalConfigsRequest) Reset() {
	*x = MutateCampaignGoalConfigsRequest{}
	mi := &file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateCampaignGoalConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateCampaignGoalConfigsRequest) ProtoMessage() {}

func (x *MutateCampaignGoalConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateCampaignGoalConfigsRequest.ProtoReflect.Descriptor instead.
func (*MutateCampaignGoalConfigsRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescGZIP(), []int{0}
}

func (x *MutateCampaignGoalConfigsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *MutateCampaignGoalConfigsRequest) GetOperations() []*CampaignGoalConfigOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *MutateCampaignGoalConfigsRequest) GetPartialFailure() bool {
	if x != nil {
		return x.PartialFailure
	}
	return false
}

func (x *MutateCampaignGoalConfigsRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

// A single mutate operation on the campaign goal config.
type CampaignGoalConfigOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FieldMask that determines which fields are modified in an update.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// The mutate operation.
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*CampaignGoalConfigOperation_Create
	//	*CampaignGoalConfigOperation_Update
	//	*CampaignGoalConfigOperation_Remove
	Operation     isCampaignGoalConfigOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignGoalConfigOperation) Reset() {
	*x = CampaignGoalConfigOperation{}
	mi := &file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignGoalConfigOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignGoalConfigOperation) ProtoMessage() {}

func (x *CampaignGoalConfigOperation) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignGoalConfigOperation.ProtoReflect.Descriptor instead.
func (*CampaignGoalConfigOperation) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescGZIP(), []int{1}
}

func (x *CampaignGoalConfigOperation) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *CampaignGoalConfigOperation) GetOperation() isCampaignGoalConfigOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *CampaignGoalConfigOperation) GetCreate() *resources.CampaignGoalConfig {
	if x != nil {
		if x, ok := x.Operation.(*CampaignGoalConfigOperation_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *CampaignGoalConfigOperation) GetUpdate() *resources.CampaignGoalConfig {
	if x != nil {
		if x, ok := x.Operation.(*CampaignGoalConfigOperation_Update); ok {
			return x.Update
		}
	}
	return nil
}

func (x *CampaignGoalConfigOperation) GetRemove() string {
	if x != nil {
		if x, ok := x.Operation.(*CampaignGoalConfigOperation_Remove); ok {
			return x.Remove
		}
	}
	return ""
}

type isCampaignGoalConfigOperation_Operation interface {
	isCampaignGoalConfigOperation_Operation()
}

type CampaignGoalConfigOperation_Create struct {
	// Create a new campaign goal config.
	Create *resources.CampaignGoalConfig `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type CampaignGoalConfigOperation_Update struct {
	// Update an existing campaign goal config.
	Update *resources.CampaignGoalConfig `protobuf:"bytes,3,opt,name=update,proto3,oneof"`
}

type CampaignGoalConfigOperation_Remove struct {
	// Remove an existing campaign goal config.
	Remove string `protobuf:"bytes,2,opt,name=remove,proto3,oneof"`
}

func (*CampaignGoalConfigOperation_Create) isCampaignGoalConfigOperation_Operation() {}

func (*CampaignGoalConfigOperation_Update) isCampaignGoalConfigOperation_Operation() {}

func (*CampaignGoalConfigOperation_Remove) isCampaignGoalConfigOperation_Operation() {}

// Response message for a campaign goal config mutate.
type MutateCampaignGoalConfigsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Errors that pertain to operation failures in the partial failure mode.
	PartialFailureError *status.Status `protobuf:"bytes,1,opt,name=partial_failure_error,json=partialFailureError,proto3" json:"partial_failure_error,omitempty"`
	// All results for the mutate.
	Results       []*MutateCampaignGoalConfigResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateCampaignGoalConfigsResponse) Reset() {
	*x = MutateCampaignGoalConfigsResponse{}
	mi := &file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateCampaignGoalConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateCampaignGoalConfigsResponse) ProtoMessage() {}

func (x *MutateCampaignGoalConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateCampaignGoalConfigsResponse.ProtoReflect.Descriptor instead.
func (*MutateCampaignGoalConfigsResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescGZIP(), []int{2}
}

func (x *MutateCampaignGoalConfigsResponse) GetPartialFailureError() *status.Status {
	if x != nil {
		return x.PartialFailureError
	}
	return nil
}

func (x *MutateCampaignGoalConfigsResponse) GetResults() []*MutateCampaignGoalConfigResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// The result for the campaign goal config mutate.
type MutateCampaignGoalConfigResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returned for successful operations.
	ResourceName  string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateCampaignGoalConfigResult) Reset() {
	*x = MutateCampaignGoalConfigResult{}
	mi := &file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateCampaignGoalConfigResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateCampaignGoalConfigResult) ProtoMessage() {}

func (x *MutateCampaignGoalConfigResult) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateCampaignGoalConfigResult.ProtoReflect.Descriptor instead.
func (*MutateCampaignGoalConfigResult) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescGZIP(), []int{3}
}

func (x *MutateCampaignGoalConfigResult) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

var File_google_ads_googleads_v22_services_campaign_goal_config_service_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDesc = "" +
	"\n" +
	"Dgoogle/ads/googleads/v22/services/campaign_goal_config_service.proto\x12!google.ads.googleads.v22.services\x1a=google/ads/googleads/v22/resources/campaign_goal_config.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x17google/rpc/status.proto\"\x85\x02\n" +
	" MutateCampaignGoalConfigsRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12c\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2>.google.ads.googleads.v22.services.CampaignGoalConfigOperationB\x03\xe0A\x02R\n" +
	"operations\x12,\n" +
	"\x0fpartial_failure\x18\x03 \x01(\bB\x03\xe0A\x01R\x0epartialFailure\x12(\n" +
	"\rvalidate_only\x18\x04 \x01(\bB\x03\xe0A\x01R\fvalidateOnly\"\xd7\x02\n" +
	"\x1bCampaignGoalConfigOperation\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12P\n" +
	"\x06create\x18\x01 \x01(\v26.google.ads.googleads.v22.resources.CampaignGoalConfigH\x00R\x06create\x12P\n" +
	"\x06update\x18\x03 \x01(\v26.google.ads.googleads.v22.resources.CampaignGoalConfigH\x00R\x06update\x12J\n" +
	"\x06remove\x18\x02 \x01(\tB0\xfaA-\n" +
	"+googleads.googleapis.com/CampaignGoalConfigH\x00R\x06removeB\v\n" +
	"\toperation\"\xc8\x01\n" +
	"!MutateCampaignGoalConfigsResponse\x12F\n" +
	"\x15partial_failure_error\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x13partialFailureError\x12[\n" +
	"\aresults\x18\x02 \x03(\v2A.google.ads.googleads.v22.services.MutateCampaignGoalConfigResultR\aresults\"w\n" +
	"\x1eMutateCampaignGoalConfigResult\x12U\n" +
	"\rresource_name\x18\x01 \x01(\tB0\xfaA-\n" +
	"+googleads.googleapis.com/CampaignGoalConfigR\fresourceName2\xea\x02\n" +
	"\x19CampaignGoalConfigService\x12\x85\x02\n" +
	"\x19MutateCampaignGoalConfigs\x12C.google.ads.googleads.v22.services.MutateCampaignGoalConfigsRequest\x1aD.google.ads.googleads.v22.services.MutateCampaignGoalConfigsResponse\"]\xdaA\x16customer_id,operations\x82\xd3\xe4\x93\x02>:\x01*\"9/v22/customers/{customer_id=*}/CampaignGoalConfigs:mutate\x1aE\xcaA\x18googleads.googleapis.com\xd2A'https://www.googleapis.com/auth/adwordsB\x8a\x02\n" +
	"%com.google.ads.googleads.v22.servicesB\x1eCampaignGoalConfigServiceProtoP\x01ZIgithub.com/Optable/google-ads-pb/protogen/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V22.Services\xca\x02!Google\\Ads\\GoogleAds\\V22\\Services\xea\x02%Google::Ads::GoogleAds::V22::Servicesb\x06proto3"

var (
	file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDesc), len(file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDescData
}

var file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_goTypes = []any{
	(*MutateCampaignGoalConfigsRequest)(nil),  // 0: google.ads.googleads.v22.services.MutateCampaignGoalConfigsRequest
	(*CampaignGoalConfigOperation)(nil),       // 1: google.ads.googleads.v22.services.CampaignGoalConfigOperation
	(*MutateCampaignGoalConfigsResponse)(nil), // 2: google.ads.googleads.v22.services.MutateCampaignGoalConfigsResponse
	(*MutateCampaignGoalConfigResult)(nil),    // 3: google.ads.googleads.v22.services.MutateCampaignGoalConfigResult
	(*fieldmaskpb.FieldMask)(nil),             // 4: google.protobuf.FieldMask
	(*resources.CampaignGoalConfig)(nil),      // 5: google.ads.googleads.v22.resources.CampaignGoalConfig
	(*status.Status)(nil),                     // 6: google.rpc.Status
}
var file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v22.services.MutateCampaignGoalConfigsRequest.operations:type_name -> google.ads.googleads.v22.services.CampaignGoalConfigOperation
	4, // 1: google.ads.googleads.v22.services.CampaignGoalConfigOperation.update_mask:type_name -> google.protobuf.FieldMask
	5, // 2: google.ads.googleads.v22.services.CampaignGoalConfigOperation.create:type_name -> google.ads.googleads.v22.resources.CampaignGoalConfig
	5, // 3: google.ads.googleads.v22.services.CampaignGoalConfigOperation.update:type_name -> google.ads.googleads.v22.resources.CampaignGoalConfig
	6, // 4: google.ads.googleads.v22.services.MutateCampaignGoalConfigsResponse.partial_failure_error:type_name -> google.rpc.Status
	3, // 5: google.ads.googleads.v22.services.MutateCampaignGoalConfigsResponse.results:type_name -> google.ads.googleads.v22.services.MutateCampaignGoalConfigResult
	0, // 6: google.ads.googleads.v22.services.CampaignGoalConfigService.MutateCampaignGoalConfigs:input_type -> google.ads.googleads.v22.services.MutateCampaignGoalConfigsRequest
	2, // 7: google.ads.googleads.v22.services.CampaignGoalConfigService.MutateCampaignGoalConfigs:output_type -> google.ads.googleads.v22.services.MutateCampaignGoalConfigsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_init() }
func file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_init() {
	if File_google_ads_googleads_v22_services_campaign_goal_config_service_proto != nil {
		return
	}
	file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes[1].OneofWrappers = []any{
		(*CampaignGoalConfigOperation_Create)(nil),
		(*CampaignGoalConfigOperation_Update)(nil),
		(*CampaignGoalConfigOperation_Remove)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDesc), len(file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_services_campaign_goal_config_service_proto = out.File
	file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_goTypes = nil
	file_google_ads_googleads_v22_services_campaign_goal_config_service_proto_depIdxs = nil
}
