// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/services/goal_service.proto

package services

import (
	resources "github.com/Optable/google-ads-pb/protogen/resources"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for
// [GoalService.MutateGoals][google.ads.googleads.v22.services.GoalService.MutateGoals].
type MutateGoalsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The ID of the customer whose goals are being modified.
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Required. The list of operations to perform on the goals.
	Operations []*GoalOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// Optional. If true, successful operations will be carried out and invalid
	// operations will return errors. If false, all operations will be carried
	// out in one transaction if and only if they are all valid.
	// Default is false.
	PartialFailure bool `protobuf:"varint,3,opt,name=partial_failure,json=partialFailure,proto3" json:"partial_failure,omitempty"`
	// Optional. If true, the request is validated but not executed. Only errors
	// are returned, not results.
	ValidateOnly  bool `protobuf:"varint,4,opt,name=validate_only,json=validateOnly,proto3" json:"validate_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateGoalsRequest) Reset() {
	*x = MutateGoalsRequest{}
	mi := &file_google_ads_googleads_v22_services_goal_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateGoalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateGoalsRequest) ProtoMessage() {}

func (x *MutateGoalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_goal_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateGoalsRequest.ProtoReflect.Descriptor instead.
func (*MutateGoalsRequest) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_goal_service_proto_rawDescGZIP(), []int{0}
}

func (x *MutateGoalsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *MutateGoalsRequest) GetOperations() []*GoalOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *MutateGoalsRequest) GetPartialFailure() bool {
	if x != nil {
		return x.PartialFailure
	}
	return false
}

func (x *MutateGoalsRequest) GetValidateOnly() bool {
	if x != nil {
		return x.ValidateOnly
	}
	return false
}

// A single mutate operation on the goal.
type GoalOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FieldMask that determines which resource fields are modified in an update.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// The mutate operation.
	//
	// Types that are valid to be assigned to Operation:
	//
	//	*GoalOperation_Create
	//	*GoalOperation_Update
	Operation     isGoalOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoalOperation) Reset() {
	*x = GoalOperation{}
	mi := &file_google_ads_googleads_v22_services_goal_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoalOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoalOperation) ProtoMessage() {}

func (x *GoalOperation) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_goal_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoalOperation.ProtoReflect.Descriptor instead.
func (*GoalOperation) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_goal_service_proto_rawDescGZIP(), []int{1}
}

func (x *GoalOperation) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *GoalOperation) GetOperation() isGoalOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *GoalOperation) GetCreate() *resources.Goal {
	if x != nil {
		if x, ok := x.Operation.(*GoalOperation_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *GoalOperation) GetUpdate() *resources.Goal {
	if x != nil {
		if x, ok := x.Operation.(*GoalOperation_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isGoalOperation_Operation interface {
	isGoalOperation_Operation()
}

type GoalOperation_Create struct {
	// Create a new goal.
	Create *resources.Goal `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type GoalOperation_Update struct {
	// Update an existing goal.
	Update *resources.Goal `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

func (*GoalOperation_Create) isGoalOperation_Operation() {}

func (*GoalOperation_Update) isGoalOperation_Operation() {}

// Response message for a goal mutate.
type MutateGoalsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Errors that pertain to operation failures in the partial failure mode.
	PartialFailureError *status.Status `protobuf:"bytes,1,opt,name=partial_failure_error,json=partialFailureError,proto3" json:"partial_failure_error,omitempty"`
	// All results for the mutate.
	Results       []*MutateGoalResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateGoalsResponse) Reset() {
	*x = MutateGoalsResponse{}
	mi := &file_google_ads_googleads_v22_services_goal_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateGoalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateGoalsResponse) ProtoMessage() {}

func (x *MutateGoalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_goal_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateGoalsResponse.ProtoReflect.Descriptor instead.
func (*MutateGoalsResponse) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_goal_service_proto_rawDescGZIP(), []int{2}
}

func (x *MutateGoalsResponse) GetPartialFailureError() *status.Status {
	if x != nil {
		return x.PartialFailureError
	}
	return nil
}

func (x *MutateGoalsResponse) GetResults() []*MutateGoalResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// The result for the goal mutate.
type MutateGoalResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returned for successful operations.
	ResourceName  string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateGoalResult) Reset() {
	*x = MutateGoalResult{}
	mi := &file_google_ads_googleads_v22_services_goal_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateGoalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateGoalResult) ProtoMessage() {}

func (x *MutateGoalResult) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_services_goal_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateGoalResult.ProtoReflect.Descriptor instead.
func (*MutateGoalResult) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_services_goal_service_proto_rawDescGZIP(), []int{3}
}

func (x *MutateGoalResult) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

var File_google_ads_googleads_v22_services_goal_service_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_services_goal_service_proto_rawDesc = "" +
	"\n" +
	"4google/ads/googleads/v22/services/goal_service.proto\x12!google.ads.googleads.v22.services\x1a-google/ads/googleads/v22/resources/goal.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\x1a google/protobuf/field_mask.proto\x1a\x17google/rpc/status.proto\"\xe9\x01\n" +
	"\x12MutateGoalsRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12U\n" +
	"\n" +
	"operations\x18\x02 \x03(\v20.google.ads.googleads.v22.services.GoalOperationB\x03\xe0A\x02R\n" +
	"operations\x12,\n" +
	"\x0fpartial_failure\x18\x03 \x01(\bB\x03\xe0A\x01R\x0epartialFailure\x12(\n" +
	"\rvalidate_only\x18\x04 \x01(\bB\x03\xe0A\x01R\fvalidateOnly\"\xe1\x01\n" +
	"\rGoalOperation\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12B\n" +
	"\x06create\x18\x01 \x01(\v2(.google.ads.googleads.v22.resources.GoalH\x00R\x06create\x12B\n" +
	"\x06update\x18\x02 \x01(\v2(.google.ads.googleads.v22.resources.GoalH\x00R\x06updateB\v\n" +
	"\toperation\"\xac\x01\n" +
	"\x13MutateGoalsResponse\x12F\n" +
	"\x15partial_failure_error\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x13partialFailureError\x12M\n" +
	"\aresults\x18\x02 \x03(\v23.google.ads.googleads.v22.services.MutateGoalResultR\aresults\"[\n" +
	"\x10MutateGoalResult\x12G\n" +
	"\rresource_name\x18\x01 \x01(\tB\"\xfaA\x1f\n" +
	"\x1dgoogleads.googleapis.com/GoalR\fresourceName2\xa4\x02\n" +
	"\vGoalService\x12\xcd\x01\n" +
	"\vMutateGoals\x125.google.ads.googleads.v22.services.MutateGoalsRequest\x1a6.google.ads.googleads.v22.services.MutateGoalsResponse\"O\xdaA\x16customer_id,operations\x82\xd3\xe4\x93\x020:\x01*\"+/v22/customers/{customer_id=*}/Goals:mutate\x1aE\xcaA\x18googleads.googleapis.com\xd2A'https://www.googleapis.com/auth/adwordsB\xfc\x01\n" +
	"%com.google.ads.googleads.v22.servicesB\x10GoalServiceProtoP\x01ZIgithub.com/Optable/google-ads-pb/protogen/services;services\xa2\x02\x03GAA\xaa\x02!Google.Ads.GoogleAds.V22.Services\xca\x02!Google\\Ads\\GoogleAds\\V22\\Services\xea\x02%Google::Ads::GoogleAds::V22::Servicesb\x06proto3"

var (
	file_google_ads_googleads_v22_services_goal_service_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_services_goal_service_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_services_goal_service_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_services_goal_service_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_services_goal_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_services_goal_service_proto_rawDesc), len(file_google_ads_googleads_v22_services_goal_service_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_services_goal_service_proto_rawDescData
}

var file_google_ads_googleads_v22_services_goal_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_ads_googleads_v22_services_goal_service_proto_goTypes = []any{
	(*MutateGoalsRequest)(nil),    // 0: google.ads.googleads.v22.services.MutateGoalsRequest
	(*GoalOperation)(nil),         // 1: google.ads.googleads.v22.services.GoalOperation
	(*MutateGoalsResponse)(nil),   // 2: google.ads.googleads.v22.services.MutateGoalsResponse
	(*MutateGoalResult)(nil),      // 3: google.ads.googleads.v22.services.MutateGoalResult
	(*fieldmaskpb.FieldMask)(nil), // 4: google.protobuf.FieldMask
	(*resources.Goal)(nil),        // 5: google.ads.googleads.v22.resources.Goal
	(*status.Status)(nil),         // 6: google.rpc.Status
}
var file_google_ads_googleads_v22_services_goal_service_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v22.services.MutateGoalsRequest.operations:type_name -> google.ads.googleads.v22.services.GoalOperation
	4, // 1: google.ads.googleads.v22.services.GoalOperation.update_mask:type_name -> google.protobuf.FieldMask
	5, // 2: google.ads.googleads.v22.services.GoalOperation.create:type_name -> google.ads.googleads.v22.resources.Goal
	5, // 3: google.ads.googleads.v22.services.GoalOperation.update:type_name -> google.ads.googleads.v22.resources.Goal
	6, // 4: google.ads.googleads.v22.services.MutateGoalsResponse.partial_failure_error:type_name -> google.rpc.Status
	3, // 5: google.ads.googleads.v22.services.MutateGoalsResponse.results:type_name -> google.ads.googleads.v22.services.MutateGoalResult
	0, // 6: google.ads.googleads.v22.services.GoalService.MutateGoals:input_type -> google.ads.googleads.v22.services.MutateGoalsRequest
	2, // 7: google.ads.googleads.v22.services.GoalService.MutateGoals:output_type -> google.ads.googleads.v22.services.MutateGoalsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_services_goal_service_proto_init() }
func file_google_ads_googleads_v22_services_goal_service_proto_init() {
	if File_google_ads_googleads_v22_services_goal_service_proto != nil {
		return
	}
	file_google_ads_googleads_v22_services_goal_service_proto_msgTypes[1].OneofWrappers = []any{
		(*GoalOperation_Create)(nil),
		(*GoalOperation_Update)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_services_goal_service_proto_rawDesc), len(file_google_ads_googleads_v22_services_goal_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_ads_googleads_v22_services_goal_service_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_services_goal_service_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_services_goal_service_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_services_goal_service_proto = out.File
	file_google_ads_googleads_v22_services_goal_service_proto_goTypes = nil
	file_google_ads_googleads_v22_services_goal_service_proto_depIdxs = nil
}
