// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/resources/ad_group.proto

package resources

import (
	common "github.com/Optable/google-ads-pb/protogen/common"
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An ad group.
type AdGroup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Immutable. The resource name of the ad group.
	// Ad group resource names have the form:
	//
	// `customers/{customer_id}/adGroups/{ad_group_id}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Output only. The ID of the ad group.
	Id *int64 `protobuf:"varint,34,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// The name of the ad group.
	//
	// This field is required and should not be empty when creating new ad
	// groups.
	//
	// It must contain fewer than 255 UTF-8 full-width characters.
	//
	// It must not contain any null (code point 0x0), NL line feed
	// (code point 0xA) or carriage return (code point 0xD) characters.
	Name *string `protobuf:"bytes,35,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// The status of the ad group.
	Status enums.AdGroupStatusEnum_AdGroupStatus `protobuf:"varint,5,opt,name=status,proto3,enum=google.ads.googleads.v22.enums.AdGroupStatusEnum_AdGroupStatus" json:"status,omitempty"`
	// Immutable. The type of the ad group.
	Type enums.AdGroupTypeEnum_AdGroupType `protobuf:"varint,12,opt,name=type,proto3,enum=google.ads.googleads.v22.enums.AdGroupTypeEnum_AdGroupType" json:"type,omitempty"`
	// The ad rotation mode of the ad group.
	AdRotationMode enums.AdGroupAdRotationModeEnum_AdGroupAdRotationMode `protobuf:"varint,22,opt,name=ad_rotation_mode,json=adRotationMode,proto3,enum=google.ads.googleads.v22.enums.AdGroupAdRotationModeEnum_AdGroupAdRotationMode" json:"ad_rotation_mode,omitempty"`
	// Output only. For draft or experiment ad groups, this field is the resource
	// name of the base ad group from which this ad group was created. If a draft
	// or experiment ad group does not have a base ad group, then this field is
	// null.
	//
	// For base ad groups, this field equals the ad group resource name.
	//
	// This field is read-only.
	BaseAdGroup *string `protobuf:"bytes,36,opt,name=base_ad_group,json=baseAdGroup,proto3,oneof" json:"base_ad_group,omitempty"`
	// The URL template for constructing a tracking URL.
	TrackingUrlTemplate *string `protobuf:"bytes,37,opt,name=tracking_url_template,json=trackingUrlTemplate,proto3,oneof" json:"tracking_url_template,omitempty"`
	// The list of mappings used to substitute custom parameter tags in a
	// `tracking_url_template`, `final_urls`, or `mobile_final_urls`.
	UrlCustomParameters []*common.CustomParameter `protobuf:"bytes,6,rep,name=url_custom_parameters,json=urlCustomParameters,proto3" json:"url_custom_parameters,omitempty"`
	// Immutable. The campaign to which the ad group belongs.
	Campaign *string `protobuf:"bytes,38,opt,name=campaign,proto3,oneof" json:"campaign,omitempty"`
	// The maximum CPC (cost-per-click) bid.
	CpcBidMicros *int64 `protobuf:"varint,39,opt,name=cpc_bid_micros,json=cpcBidMicros,proto3,oneof" json:"cpc_bid_micros,omitempty"`
	// Output only. Value will be same as that of the CPC (cost-per-click) bid
	// value when the bidding strategy is one of manual cpc, enhanced cpc, page
	// one promoted or target outrank share, otherwise the value will be null.
	EffectiveCpcBidMicros *int64 `protobuf:"varint,57,opt,name=effective_cpc_bid_micros,json=effectiveCpcBidMicros,proto3,oneof" json:"effective_cpc_bid_micros,omitempty"`
	// The maximum CPM (cost-per-thousand viewable impressions) bid.
	CpmBidMicros *int64 `protobuf:"varint,40,opt,name=cpm_bid_micros,json=cpmBidMicros,proto3,oneof" json:"cpm_bid_micros,omitempty"`
	// The target CPA (cost-per-acquisition). If the ad group's campaign
	// bidding strategy is TargetCpa or MaximizeConversions (with its target_cpa
	// field set), then this field overrides the target CPA specified in the
	// campaign's bidding strategy.
	// Otherwise, this value is ignored.
	TargetCpaMicros *int64 `protobuf:"varint,41,opt,name=target_cpa_micros,json=targetCpaMicros,proto3,oneof" json:"target_cpa_micros,omitempty"`
	// The CPV (cost-per-view) bid.
	CpvBidMicros *int64 `protobuf:"varint,42,opt,name=cpv_bid_micros,json=cpvBidMicros,proto3,oneof" json:"cpv_bid_micros,omitempty"`
	// Average amount in micros that the advertiser is willing to pay for every
	// thousand times the ad is shown.
	TargetCpmMicros *int64 `protobuf:"varint,43,opt,name=target_cpm_micros,json=targetCpmMicros,proto3,oneof" json:"target_cpm_micros,omitempty"`
	// The target ROAS (return-on-ad-spend) override. If the ad group's campaign
	// bidding strategy is TargetRoas or MaximizeConversionValue (with its
	// target_roas field set), then this field overrides the target ROAS specified
	// in the campaign's bidding strategy.
	// Otherwise, this value is ignored.
	TargetRoas *float64 `protobuf:"fixed64,44,opt,name=target_roas,json=targetRoas,proto3,oneof" json:"target_roas,omitempty"`
	// The percent cpc bid amount, expressed as a fraction of the advertised price
	// for some good or service. The valid range for the fraction is [0,1) and the
	// value stored here is 1,000,000 * [fraction].
	PercentCpcBidMicros *int64 `protobuf:"varint,45,opt,name=percent_cpc_bid_micros,json=percentCpcBidMicros,proto3,oneof" json:"percent_cpc_bid_micros,omitempty"`
	// The fixed amount in micros that the advertiser pays for every thousand
	// impressions of the ad.
	FixedCpmMicros *int64 `protobuf:"varint,64,opt,name=fixed_cpm_micros,json=fixedCpmMicros,proto3,oneof" json:"fixed_cpm_micros,omitempty"`
	// Average amount in micros that the advertiser is willing to pay for every ad
	// view.
	TargetCpvMicros *int64 `protobuf:"varint,65,opt,name=target_cpv_micros,json=targetCpvMicros,proto3,oneof" json:"target_cpv_micros,omitempty"`
	// Average amount in micros that the advertiser is willing to pay for every ad
	// click. Overrides the target CPC configured at the campaign level.
	TargetCpcMicros *int64 `protobuf:"varint,68,opt,name=target_cpc_micros,json=targetCpcMicros,proto3,oneof" json:"target_cpc_micros,omitempty"`
	// True if optimized targeting is enabled. Optimized Targeting is the
	// replacement for Audience Expansion.
	OptimizedTargetingEnabled bool `protobuf:"varint,59,opt,name=optimized_targeting_enabled,json=optimizedTargetingEnabled,proto3" json:"optimized_targeting_enabled,omitempty"`
	// When this value is true, demographics will be excluded from the types of
	// targeting which are expanded when optimized_targeting_enabled is true.
	// When optimized_targeting_enabled is false, this field is ignored. Default
	// is false.
	ExcludeDemographicExpansion bool `protobuf:"varint,67,opt,name=exclude_demographic_expansion,json=excludeDemographicExpansion,proto3" json:"exclude_demographic_expansion,omitempty"`
	// Allows advertisers to specify a targeting dimension on which to place
	// absolute bids. This is only applicable for campaigns that target only the
	// display network and not search.
	DisplayCustomBidDimension enums.TargetingDimensionEnum_TargetingDimension `protobuf:"varint,23,opt,name=display_custom_bid_dimension,json=displayCustomBidDimension,proto3,enum=google.ads.googleads.v22.enums.TargetingDimensionEnum_TargetingDimension" json:"display_custom_bid_dimension,omitempty"`
	// URL template for appending params to Final URL.
	FinalUrlSuffix *string `protobuf:"bytes,46,opt,name=final_url_suffix,json=finalUrlSuffix,proto3,oneof" json:"final_url_suffix,omitempty"`
	// Setting for targeting related features.
	TargetingSetting *common.TargetingSetting `protobuf:"bytes,25,opt,name=targeting_setting,json=targetingSetting,proto3" json:"targeting_setting,omitempty"`
	// Immutable. Setting for audience related features.
	AudienceSetting *AdGroup_AudienceSetting `protobuf:"bytes,56,opt,name=audience_setting,json=audienceSetting,proto3" json:"audience_setting,omitempty"`
	// Output only. The effective target CPA (cost-per-acquisition).
	// This field is read-only.
	EffectiveTargetCpaMicros *int64 `protobuf:"varint,47,opt,name=effective_target_cpa_micros,json=effectiveTargetCpaMicros,proto3,oneof" json:"effective_target_cpa_micros,omitempty"`
	// Output only. Source of the effective target CPA.
	// This field is read-only.
	EffectiveTargetCpaSource enums.BiddingSourceEnum_BiddingSource `protobuf:"varint,29,opt,name=effective_target_cpa_source,json=effectiveTargetCpaSource,proto3,enum=google.ads.googleads.v22.enums.BiddingSourceEnum_BiddingSource" json:"effective_target_cpa_source,omitempty"`
	// Output only. The effective target ROAS (return-on-ad-spend).
	// This field is read-only.
	EffectiveTargetRoas *float64 `protobuf:"fixed64,48,opt,name=effective_target_roas,json=effectiveTargetRoas,proto3,oneof" json:"effective_target_roas,omitempty"`
	// Output only. Source of the effective target ROAS.
	// This field is read-only.
	EffectiveTargetRoasSource enums.BiddingSourceEnum_BiddingSource `protobuf:"varint,32,opt,name=effective_target_roas_source,json=effectiveTargetRoasSource,proto3,enum=google.ads.googleads.v22.enums.BiddingSourceEnum_BiddingSource" json:"effective_target_roas_source,omitempty"`
	// Output only. The effective target CPC (cost-per-click).
	// This field is read-only.
	EffectiveTargetCpc *int64 `protobuf:"varint,69,opt,name=effective_target_cpc,json=effectiveTargetCpc,proto3,oneof" json:"effective_target_cpc,omitempty"`
	// Output only. Source of the effective target CPC.
	// This field is read-only.
	EffectiveTargetCpcSource enums.BiddingSourceEnum_BiddingSource `protobuf:"varint,70,opt,name=effective_target_cpc_source,json=effectiveTargetCpcSource,proto3,enum=google.ads.googleads.v22.enums.BiddingSourceEnum_BiddingSource" json:"effective_target_cpc_source,omitempty"`
	// Output only. The resource names of labels attached to this ad group.
	Labels []string `protobuf:"bytes,49,rep,name=labels,proto3" json:"labels,omitempty"`
	// The asset field types that should be excluded from this ad group. Asset
	// links with these field types will not be inherited by this ad group from
	// the upper levels.
	ExcludedParentAssetFieldTypes []enums.AssetFieldTypeEnum_AssetFieldType `protobuf:"varint,54,rep,packed,name=excluded_parent_asset_field_types,json=excludedParentAssetFieldTypes,proto3,enum=google.ads.googleads.v22.enums.AssetFieldTypeEnum_AssetFieldType" json:"excluded_parent_asset_field_types,omitempty"`
	// The asset set types that should be excluded from this ad group. Asset set
	// links with these types will not be inherited by this ad group from the
	// upper levels.
	// Location group types (GMB_DYNAMIC_LOCATION_GROUP,
	// CHAIN_DYNAMIC_LOCATION_GROUP, and STATIC_LOCATION_GROUP) are child types of
	// LOCATION_SYNC. Therefore, if LOCATION_SYNC is set for this field, all
	// location group asset sets are not allowed to be linked to this ad group,
	// and all Location Extension (LE) and Affiliate Location Extensions (ALE)
	// will not be served under this ad group.
	// Only LOCATION_SYNC is currently supported.
	ExcludedParentAssetSetTypes []enums.AssetSetTypeEnum_AssetSetType `protobuf:"varint,58,rep,packed,name=excluded_parent_asset_set_types,json=excludedParentAssetSetTypes,proto3,enum=google.ads.googleads.v22.enums.AssetSetTypeEnum_AssetSetType" json:"excluded_parent_asset_set_types,omitempty"`
	// Output only. Provides aggregated view into why an ad group is not serving
	// or not serving optimally.
	PrimaryStatus enums.AdGroupPrimaryStatusEnum_AdGroupPrimaryStatus `protobuf:"varint,62,opt,name=primary_status,json=primaryStatus,proto3,enum=google.ads.googleads.v22.enums.AdGroupPrimaryStatusEnum_AdGroupPrimaryStatus" json:"primary_status,omitempty"`
	// Output only. Provides reasons for why an ad group is not serving or not
	// serving optimally.
	PrimaryStatusReasons []enums.AdGroupPrimaryStatusReasonEnum_AdGroupPrimaryStatusReason `protobuf:"varint,63,rep,packed,name=primary_status_reasons,json=primaryStatusReasons,proto3,enum=google.ads.googleads.v22.enums.AdGroupPrimaryStatusReasonEnum_AdGroupPrimaryStatusReason" json:"primary_status_reasons,omitempty"`
	// Settings for Demand Gen ad groups.
	DemandGenAdGroupSettings *AdGroup_DemandGenAdGroupSettings `protobuf:"bytes,91,opt,name=demand_gen_ad_group_settings,json=demandGenAdGroupSettings,proto3" json:"demand_gen_ad_group_settings,omitempty"`
	// Settings for video ad groups.
	VideoAdGroupSettings *AdGroup_VideoAdGroupSettings `protobuf:"bytes,92,opt,name=video_ad_group_settings,json=videoAdGroupSettings,proto3" json:"video_ad_group_settings,omitempty"`
	// Settings for AI Max feature in standard search adgroups.
	AiMaxAdGroupSetting *AdGroup_AiMaxAdGroupSetting `protobuf:"bytes,71,opt,name=ai_max_ad_group_setting,json=aiMaxAdGroupSetting,proto3" json:"ai_max_ad_group_setting,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AdGroup) Reset() {
	*x = AdGroup{}
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroup) ProtoMessage() {}

func (x *AdGroup) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroup.ProtoReflect.Descriptor instead.
func (*AdGroup) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_ad_group_proto_rawDescGZIP(), []int{0}
}

func (x *AdGroup) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *AdGroup) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *AdGroup) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *AdGroup) GetStatus() enums.AdGroupStatusEnum_AdGroupStatus {
	if x != nil {
		return x.Status
	}
	return enums.AdGroupStatusEnum_AdGroupStatus(0)
}

func (x *AdGroup) GetType() enums.AdGroupTypeEnum_AdGroupType {
	if x != nil {
		return x.Type
	}
	return enums.AdGroupTypeEnum_AdGroupType(0)
}

func (x *AdGroup) GetAdRotationMode() enums.AdGroupAdRotationModeEnum_AdGroupAdRotationMode {
	if x != nil {
		return x.AdRotationMode
	}
	return enums.AdGroupAdRotationModeEnum_AdGroupAdRotationMode(0)
}

func (x *AdGroup) GetBaseAdGroup() string {
	if x != nil && x.BaseAdGroup != nil {
		return *x.BaseAdGroup
	}
	return ""
}

func (x *AdGroup) GetTrackingUrlTemplate() string {
	if x != nil && x.TrackingUrlTemplate != nil {
		return *x.TrackingUrlTemplate
	}
	return ""
}

func (x *AdGroup) GetUrlCustomParameters() []*common.CustomParameter {
	if x != nil {
		return x.UrlCustomParameters
	}
	return nil
}

func (x *AdGroup) GetCampaign() string {
	if x != nil && x.Campaign != nil {
		return *x.Campaign
	}
	return ""
}

func (x *AdGroup) GetCpcBidMicros() int64 {
	if x != nil && x.CpcBidMicros != nil {
		return *x.CpcBidMicros
	}
	return 0
}

func (x *AdGroup) GetEffectiveCpcBidMicros() int64 {
	if x != nil && x.EffectiveCpcBidMicros != nil {
		return *x.EffectiveCpcBidMicros
	}
	return 0
}

func (x *AdGroup) GetCpmBidMicros() int64 {
	if x != nil && x.CpmBidMicros != nil {
		return *x.CpmBidMicros
	}
	return 0
}

func (x *AdGroup) GetTargetCpaMicros() int64 {
	if x != nil && x.TargetCpaMicros != nil {
		return *x.TargetCpaMicros
	}
	return 0
}

func (x *AdGroup) GetCpvBidMicros() int64 {
	if x != nil && x.CpvBidMicros != nil {
		return *x.CpvBidMicros
	}
	return 0
}

func (x *AdGroup) GetTargetCpmMicros() int64 {
	if x != nil && x.TargetCpmMicros != nil {
		return *x.TargetCpmMicros
	}
	return 0
}

func (x *AdGroup) GetTargetRoas() float64 {
	if x != nil && x.TargetRoas != nil {
		return *x.TargetRoas
	}
	return 0
}

func (x *AdGroup) GetPercentCpcBidMicros() int64 {
	if x != nil && x.PercentCpcBidMicros != nil {
		return *x.PercentCpcBidMicros
	}
	return 0
}

func (x *AdGroup) GetFixedCpmMicros() int64 {
	if x != nil && x.FixedCpmMicros != nil {
		return *x.FixedCpmMicros
	}
	return 0
}

func (x *AdGroup) GetTargetCpvMicros() int64 {
	if x != nil && x.TargetCpvMicros != nil {
		return *x.TargetCpvMicros
	}
	return 0
}

func (x *AdGroup) GetTargetCpcMicros() int64 {
	if x != nil && x.TargetCpcMicros != nil {
		return *x.TargetCpcMicros
	}
	return 0
}

func (x *AdGroup) GetOptimizedTargetingEnabled() bool {
	if x != nil {
		return x.OptimizedTargetingEnabled
	}
	return false
}

func (x *AdGroup) GetExcludeDemographicExpansion() bool {
	if x != nil {
		return x.ExcludeDemographicExpansion
	}
	return false
}

func (x *AdGroup) GetDisplayCustomBidDimension() enums.TargetingDimensionEnum_TargetingDimension {
	if x != nil {
		return x.DisplayCustomBidDimension
	}
	return enums.TargetingDimensionEnum_TargetingDimension(0)
}

func (x *AdGroup) GetFinalUrlSuffix() string {
	if x != nil && x.FinalUrlSuffix != nil {
		return *x.FinalUrlSuffix
	}
	return ""
}

func (x *AdGroup) GetTargetingSetting() *common.TargetingSetting {
	if x != nil {
		return x.TargetingSetting
	}
	return nil
}

func (x *AdGroup) GetAudienceSetting() *AdGroup_AudienceSetting {
	if x != nil {
		return x.AudienceSetting
	}
	return nil
}

func (x *AdGroup) GetEffectiveTargetCpaMicros() int64 {
	if x != nil && x.EffectiveTargetCpaMicros != nil {
		return *x.EffectiveTargetCpaMicros
	}
	return 0
}

func (x *AdGroup) GetEffectiveTargetCpaSource() enums.BiddingSourceEnum_BiddingSource {
	if x != nil {
		return x.EffectiveTargetCpaSource
	}
	return enums.BiddingSourceEnum_BiddingSource(0)
}

func (x *AdGroup) GetEffectiveTargetRoas() float64 {
	if x != nil && x.EffectiveTargetRoas != nil {
		return *x.EffectiveTargetRoas
	}
	return 0
}

func (x *AdGroup) GetEffectiveTargetRoasSource() enums.BiddingSourceEnum_BiddingSource {
	if x != nil {
		return x.EffectiveTargetRoasSource
	}
	return enums.BiddingSourceEnum_BiddingSource(0)
}

func (x *AdGroup) GetEffectiveTargetCpc() int64 {
	if x != nil && x.EffectiveTargetCpc != nil {
		return *x.EffectiveTargetCpc
	}
	return 0
}

func (x *AdGroup) GetEffectiveTargetCpcSource() enums.BiddingSourceEnum_BiddingSource {
	if x != nil {
		return x.EffectiveTargetCpcSource
	}
	return enums.BiddingSourceEnum_BiddingSource(0)
}

func (x *AdGroup) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AdGroup) GetExcludedParentAssetFieldTypes() []enums.AssetFieldTypeEnum_AssetFieldType {
	if x != nil {
		return x.ExcludedParentAssetFieldTypes
	}
	return nil
}

func (x *AdGroup) GetExcludedParentAssetSetTypes() []enums.AssetSetTypeEnum_AssetSetType {
	if x != nil {
		return x.ExcludedParentAssetSetTypes
	}
	return nil
}

func (x *AdGroup) GetPrimaryStatus() enums.AdGroupPrimaryStatusEnum_AdGroupPrimaryStatus {
	if x != nil {
		return x.PrimaryStatus
	}
	return enums.AdGroupPrimaryStatusEnum_AdGroupPrimaryStatus(0)
}

func (x *AdGroup) GetPrimaryStatusReasons() []enums.AdGroupPrimaryStatusReasonEnum_AdGroupPrimaryStatusReason {
	if x != nil {
		return x.PrimaryStatusReasons
	}
	return nil
}

func (x *AdGroup) GetDemandGenAdGroupSettings() *AdGroup_DemandGenAdGroupSettings {
	if x != nil {
		return x.DemandGenAdGroupSettings
	}
	return nil
}

func (x *AdGroup) GetVideoAdGroupSettings() *AdGroup_VideoAdGroupSettings {
	if x != nil {
		return x.VideoAdGroupSettings
	}
	return nil
}

func (x *AdGroup) GetAiMaxAdGroupSetting() *AdGroup_AiMaxAdGroupSetting {
	if x != nil {
		return x.AiMaxAdGroupSetting
	}
	return nil
}

// Settings for the audience targeting.
type AdGroup_AudienceSetting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Immutable. If true, this ad group uses an Audience resource for audience
	// targeting. If false, this ad group may use audience segment criteria
	// instead.
	UseAudienceGrouped bool `protobuf:"varint,1,opt,name=use_audience_grouped,json=useAudienceGrouped,proto3" json:"use_audience_grouped,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdGroup_AudienceSetting) Reset() {
	*x = AdGroup_AudienceSetting{}
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroup_AudienceSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroup_AudienceSetting) ProtoMessage() {}

func (x *AdGroup_AudienceSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroup_AudienceSetting.ProtoReflect.Descriptor instead.
func (*AdGroup_AudienceSetting) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_ad_group_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AdGroup_AudienceSetting) GetUseAudienceGrouped() bool {
	if x != nil {
		return x.UseAudienceGrouped
	}
	return false
}

// Settings for Demand Gen ad groups.
type AdGroup_DemandGenAdGroupSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel controls for Demand Gen ad groups.
	ChannelControls *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls `protobuf:"bytes,1,opt,name=channel_controls,json=channelControls,proto3" json:"channel_controls,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdGroup_DemandGenAdGroupSettings) Reset() {
	*x = AdGroup_DemandGenAdGroupSettings{}
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroup_DemandGenAdGroupSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroup_DemandGenAdGroupSettings) ProtoMessage() {}

func (x *AdGroup_DemandGenAdGroupSettings) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroup_DemandGenAdGroupSettings.ProtoReflect.Descriptor instead.
func (*AdGroup_DemandGenAdGroupSettings) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_ad_group_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AdGroup_DemandGenAdGroupSettings) GetChannelControls() *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls {
	if x != nil {
		return x.ChannelControls
	}
	return nil
}

// Settings for video ad groups.
type AdGroup_VideoAdGroupSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The video ads sequence step settings containing step ID.
	VideoAdSequence *AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting `protobuf:"bytes,1,opt,name=video_ad_sequence,json=videoAdSequence,proto3" json:"video_ad_sequence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdGroup_VideoAdGroupSettings) Reset() {
	*x = AdGroup_VideoAdGroupSettings{}
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroup_VideoAdGroupSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroup_VideoAdGroupSettings) ProtoMessage() {}

func (x *AdGroup_VideoAdGroupSettings) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroup_VideoAdGroupSettings.ProtoReflect.Descriptor instead.
func (*AdGroup_VideoAdGroupSettings) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_ad_group_proto_rawDescGZIP(), []int{0, 2}
}

func (x *AdGroup_VideoAdGroupSettings) GetVideoAdSequence() *AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting {
	if x != nil {
		return x.VideoAdSequence
	}
	return nil
}

// Settings for AI Max feature in standard search adgroups.
type AdGroup_AiMaxAdGroupSetting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Disable search term matching for this adgroup when AI Max is enabled.
	// Search term matching uses broad match, asset-based, and landing
	// page-based technology to improve reach.
	DisableSearchTermMatching *bool `protobuf:"varint,1,opt,name=disable_search_term_matching,json=disableSearchTermMatching,proto3,oneof" json:"disable_search_term_matching,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AdGroup_AiMaxAdGroupSetting) Reset() {
	*x = AdGroup_AiMaxAdGroupSetting{}
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroup_AiMaxAdGroupSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroup_AiMaxAdGroupSetting) ProtoMessage() {}

func (x *AdGroup_AiMaxAdGroupSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroup_AiMaxAdGroupSetting.ProtoReflect.Descriptor instead.
func (*AdGroup_AiMaxAdGroupSetting) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_ad_group_proto_rawDescGZIP(), []int{0, 3}
}

func (x *AdGroup_AiMaxAdGroupSetting) GetDisableSearchTermMatching() bool {
	if x != nil && x.DisableSearchTermMatching != nil {
		return *x.DisableSearchTermMatching
	}
	return false
}

// Channel controls for Demand Gen ad groups.
type AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. Channel configuration reflecting which field in the oneof
	// is populated.
	ChannelConfig enums.DemandGenChannelConfigEnum_DemandGenChannelConfig `protobuf:"varint,1,opt,name=channel_config,json=channelConfig,proto3,enum=google.ads.googleads.v22.enums.DemandGenChannelConfigEnum_DemandGenChannelConfig" json:"channel_config,omitempty"`
	// Oneof between the different channel control configuration options.
	//
	// Types that are valid to be assigned to ChannelConfiguration:
	//
	//	*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelStrategy
	//	*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_SelectedChannels
	ChannelConfiguration isAdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelConfiguration `protobuf_oneof:"channel_configuration"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls) Reset() {
	*x = AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls{}
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls) ProtoMessage() {}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls.ProtoReflect.Descriptor instead.
func (*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_ad_group_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls) GetChannelConfig() enums.DemandGenChannelConfigEnum_DemandGenChannelConfig {
	if x != nil {
		return x.ChannelConfig
	}
	return enums.DemandGenChannelConfigEnum_DemandGenChannelConfig(0)
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls) GetChannelConfiguration() isAdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelConfiguration {
	if x != nil {
		return x.ChannelConfiguration
	}
	return nil
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls) GetChannelStrategy() enums.DemandGenChannelStrategyEnum_DemandGenChannelStrategy {
	if x != nil {
		if x, ok := x.ChannelConfiguration.(*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelStrategy); ok {
			return x.ChannelStrategy
		}
	}
	return enums.DemandGenChannelStrategyEnum_DemandGenChannelStrategy(0)
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls) GetSelectedChannels() *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels {
	if x != nil {
		if x, ok := x.ChannelConfiguration.(*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_SelectedChannels); ok {
			return x.SelectedChannels
		}
	}
	return nil
}

type isAdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelConfiguration interface {
	isAdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelConfiguration()
}

type AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelStrategy struct {
	// High level channel strategy.
	ChannelStrategy enums.DemandGenChannelStrategyEnum_DemandGenChannelStrategy `protobuf:"varint,2,opt,name=channel_strategy,json=channelStrategy,proto3,enum=google.ads.googleads.v22.enums.DemandGenChannelStrategyEnum_DemandGenChannelStrategy,oneof"`
}

type AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_SelectedChannels struct {
	// Explicitly selected channels. This field should be set with at
	// least one true value when present.
	SelectedChannels *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels `protobuf:"bytes,3,opt,name=selected_channels,json=selectedChannels,proto3,oneof"`
}

func (*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelStrategy) isAdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelConfiguration() {
}

func (*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_SelectedChannels) isAdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelConfiguration() {
}

// Explicitly selected channels for channel controls in Demand Gen ad
// groups.
type AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to enable ads on the YouTube In-Stream channel.
	YoutubeInStream bool `protobuf:"varint,1,opt,name=youtube_in_stream,json=youtubeInStream,proto3" json:"youtube_in_stream,omitempty"`
	// Whether to enable ads on the YouTube In-Feed channel.
	YoutubeInFeed bool `protobuf:"varint,2,opt,name=youtube_in_feed,json=youtubeInFeed,proto3" json:"youtube_in_feed,omitempty"`
	// Whether to enable ads on the YouTube Shorts channel.
	YoutubeShorts bool `protobuf:"varint,3,opt,name=youtube_shorts,json=youtubeShorts,proto3" json:"youtube_shorts,omitempty"`
	// Whether to enable ads on the Discover channel.
	Discover bool `protobuf:"varint,4,opt,name=discover,proto3" json:"discover,omitempty"`
	// Whether to enable ads on the Gmail channel.
	Gmail bool `protobuf:"varint,5,opt,name=gmail,proto3" json:"gmail,omitempty"`
	// Whether to enable ads on the Display channel.
	Display       bool `protobuf:"varint,6,opt,name=display,proto3" json:"display,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) Reset() {
	*x = AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels{}
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) ProtoMessage() {
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels.ProtoReflect.Descriptor instead.
func (*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_ad_group_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) GetYoutubeInStream() bool {
	if x != nil {
		return x.YoutubeInStream
	}
	return false
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) GetYoutubeInFeed() bool {
	if x != nil {
		return x.YoutubeInFeed
	}
	return false
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) GetYoutubeShorts() bool {
	if x != nil {
		return x.YoutubeShorts
	}
	return false
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) GetDiscover() bool {
	if x != nil {
		return x.Discover
	}
	return false
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) GetGmail() bool {
	if x != nil {
		return x.Gmail
	}
	return false
}

func (x *AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels) GetDisplay() bool {
	if x != nil {
		return x.Display
	}
	return false
}

// The video ads sequence step settings containing step ID.
type AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of this sequence step from an existing
	// `campaign.video_campaign_settings.video_ad_sequence` definition. Only
	// one Ad Group can point to a given `step_id`.
	StepId        int64 `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting) Reset() {
	*x = AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting{}
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting) ProtoMessage() {}

func (x *AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting.ProtoReflect.Descriptor instead.
func (*AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_ad_group_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting) GetStepId() int64 {
	if x != nil {
		return x.StepId
	}
	return 0
}

var File_google_ads_googleads_v22_resources_ad_group_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_resources_ad_group_proto_rawDesc = "" +
	"\n" +
	"1google/ads/googleads/v22/resources/ad_group.proto\x12\"google.ads.googleads.v22.resources\x1a6google/ads/googleads/v22/common/custom_parameter.proto\x1a7google/ads/googleads/v22/common/targeting_setting.proto\x1a>google/ads/googleads/v22/enums/ad_group_ad_rotation_mode.proto\x1a<google/ads/googleads/v22/enums/ad_group_primary_status.proto\x1aCgoogle/ads/googleads/v22/enums/ad_group_primary_status_reason.proto\x1a4google/ads/googleads/v22/enums/ad_group_status.proto\x1a2google/ads/googleads/v22/enums/ad_group_type.proto\x1a5google/ads/googleads/v22/enums/asset_field_type.proto\x1a3google/ads/googleads/v22/enums/asset_set_type.proto\x1a3google/ads/googleads/v22/enums/bidding_source.proto\x1a>google/ads/googleads/v22/enums/demand_gen_channel_config.proto\x1a@google/ads/googleads/v22/enums/demand_gen_channel_strategy.proto\x1a8google/ads/googleads/v22/enums/targeting_dimension.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xda(\n" +
	"\aAdGroup\x12M\n" +
	"\rresource_name\x18\x01 \x01(\tB(\xe0A\x05\xfaA\"\n" +
	" googleads.googleapis.com/AdGroupR\fresourceName\x12\x18\n" +
	"\x02id\x18\" \x01(\x03B\x03\xe0A\x03H\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18# \x01(\tH\x01R\x04name\x88\x01\x01\x12W\n" +
	"\x06status\x18\x05 \x01(\x0e2?.google.ads.googleads.v22.enums.AdGroupStatusEnum.AdGroupStatusR\x06status\x12T\n" +
	"\x04type\x18\f \x01(\x0e2;.google.ads.googleads.v22.enums.AdGroupTypeEnum.AdGroupTypeB\x03\xe0A\x05R\x04type\x12y\n" +
	"\x10ad_rotation_mode\x18\x16 \x01(\x0e2O.google.ads.googleads.v22.enums.AdGroupAdRotationModeEnum.AdGroupAdRotationModeR\x0eadRotationMode\x12Q\n" +
	"\rbase_ad_group\x18$ \x01(\tB(\xe0A\x03\xfaA\"\n" +
	" googleads.googleapis.com/AdGroupH\x02R\vbaseAdGroup\x88\x01\x01\x127\n" +
	"\x15tracking_url_template\x18% \x01(\tH\x03R\x13trackingUrlTemplate\x88\x01\x01\x12d\n" +
	"\x15url_custom_parameters\x18\x06 \x03(\v20.google.ads.googleads.v22.common.CustomParameterR\x13urlCustomParameters\x12J\n" +
	"\bcampaign\x18& \x01(\tB)\xe0A\x05\xfaA#\n" +
	"!googleads.googleapis.com/CampaignH\x04R\bcampaign\x88\x01\x01\x12)\n" +
	"\x0ecpc_bid_micros\x18' \x01(\x03H\x05R\fcpcBidMicros\x88\x01\x01\x12A\n" +
	"\x18effective_cpc_bid_micros\x189 \x01(\x03B\x03\xe0A\x03H\x06R\x15effectiveCpcBidMicros\x88\x01\x01\x12)\n" +
	"\x0ecpm_bid_micros\x18( \x01(\x03H\aR\fcpmBidMicros\x88\x01\x01\x12/\n" +
	"\x11target_cpa_micros\x18) \x01(\x03H\bR\x0ftargetCpaMicros\x88\x01\x01\x12)\n" +
	"\x0ecpv_bid_micros\x18* \x01(\x03H\tR\fcpvBidMicros\x88\x01\x01\x12/\n" +
	"\x11target_cpm_micros\x18+ \x01(\x03H\n" +
	"R\x0ftargetCpmMicros\x88\x01\x01\x12$\n" +
	"\vtarget_roas\x18, \x01(\x01H\vR\n" +
	"targetRoas\x88\x01\x01\x128\n" +
	"\x16percent_cpc_bid_micros\x18- \x01(\x03H\fR\x13percentCpcBidMicros\x88\x01\x01\x12-\n" +
	"\x10fixed_cpm_micros\x18@ \x01(\x03H\rR\x0efixedCpmMicros\x88\x01\x01\x12/\n" +
	"\x11target_cpv_micros\x18A \x01(\x03H\x0eR\x0ftargetCpvMicros\x88\x01\x01\x12/\n" +
	"\x11target_cpc_micros\x18D \x01(\x03H\x0fR\x0ftargetCpcMicros\x88\x01\x01\x12>\n" +
	"\x1boptimized_targeting_enabled\x18; \x01(\bR\x19optimizedTargetingEnabled\x12B\n" +
	"\x1dexclude_demographic_expansion\x18C \x01(\bR\x1bexcludeDemographicExpansion\x12\x8a\x01\n" +
	"\x1cdisplay_custom_bid_dimension\x18\x17 \x01(\x0e2I.google.ads.googleads.v22.enums.TargetingDimensionEnum.TargetingDimensionR\x19displayCustomBidDimension\x12-\n" +
	"\x10final_url_suffix\x18. \x01(\tH\x10R\x0efinalUrlSuffix\x88\x01\x01\x12^\n" +
	"\x11targeting_setting\x18\x19 \x01(\v21.google.ads.googleads.v22.common.TargetingSettingR\x10targetingSetting\x12k\n" +
	"\x10audience_setting\x188 \x01(\v2;.google.ads.googleads.v22.resources.AdGroup.AudienceSettingB\x03\xe0A\x05R\x0faudienceSetting\x12G\n" +
	"\x1beffective_target_cpa_micros\x18/ \x01(\x03B\x03\xe0A\x03H\x11R\x18effectiveTargetCpaMicros\x88\x01\x01\x12\x83\x01\n" +
	"\x1beffective_target_cpa_source\x18\x1d \x01(\x0e2?.google.ads.googleads.v22.enums.BiddingSourceEnum.BiddingSourceB\x03\xe0A\x03R\x18effectiveTargetCpaSource\x12<\n" +
	"\x15effective_target_roas\x180 \x01(\x01B\x03\xe0A\x03H\x12R\x13effectiveTargetRoas\x88\x01\x01\x12\x85\x01\n" +
	"\x1ceffective_target_roas_source\x18  \x01(\x0e2?.google.ads.googleads.v22.enums.BiddingSourceEnum.BiddingSourceB\x03\xe0A\x03R\x19effectiveTargetRoasSource\x12:\n" +
	"\x14effective_target_cpc\x18E \x01(\x03B\x03\xe0A\x03H\x13R\x12effectiveTargetCpc\x88\x01\x01\x12\x83\x01\n" +
	"\x1beffective_target_cpc_source\x18F \x01(\x0e2?.google.ads.googleads.v22.enums.BiddingSourceEnum.BiddingSourceB\x03\xe0A\x03R\x18effectiveTargetCpcSource\x12E\n" +
	"\x06labels\x181 \x03(\tB-\xe0A\x03\xfaA'\n" +
	"%googleads.googleapis.com/AdGroupLabelR\x06labels\x12\x8b\x01\n" +
	"!excluded_parent_asset_field_types\x186 \x03(\x0e2A.google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldTypeR\x1dexcludedParentAssetFieldTypes\x12\x83\x01\n" +
	"\x1fexcluded_parent_asset_set_types\x18: \x03(\x0e2=.google.ads.googleads.v22.enums.AssetSetTypeEnum.AssetSetTypeR\x1bexcludedParentAssetSetTypes\x12y\n" +
	"\x0eprimary_status\x18> \x01(\x0e2M.google.ads.googleads.v22.enums.AdGroupPrimaryStatusEnum.AdGroupPrimaryStatusB\x03\xe0A\x03R\rprimaryStatus\x12\x94\x01\n" +
	"\x16primary_status_reasons\x18? \x03(\x0e2Y.google.ads.googleads.v22.enums.AdGroupPrimaryStatusReasonEnum.AdGroupPrimaryStatusReasonB\x03\xe0A\x03R\x14primaryStatusReasons\x12\x84\x01\n" +
	"\x1cdemand_gen_ad_group_settings\x18[ \x01(\v2D.google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettingsR\x18demandGenAdGroupSettings\x12w\n" +
	"\x17video_ad_group_settings\x18\\ \x01(\v2@.google.ads.googleads.v22.resources.AdGroup.VideoAdGroupSettingsR\x14videoAdGroupSettings\x12u\n" +
	"\x17ai_max_ad_group_setting\x18G \x01(\v2?.google.ads.googleads.v22.resources.AdGroup.AiMaxAdGroupSettingR\x13aiMaxAdGroupSetting\x1aH\n" +
	"\x0fAudienceSetting\x125\n" +
	"\x14use_audience_grouped\x18\x01 \x01(\bB\x03\xe0A\x05R\x12useAudienceGrouped\x1a\xed\x06\n" +
	"\x18DemandGenAdGroupSettings\x12\x88\x01\n" +
	"\x10channel_controls\x18\x01 \x01(\v2].google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.DemandGenChannelControlsR\x0fchannelControls\x1a\xc5\x05\n" +
	"\x18DemandGenChannelControls\x12}\n" +
	"\x0echannel_config\x18\x01 \x01(\x0e2Q.google.ads.googleads.v22.enums.DemandGenChannelConfigEnum.DemandGenChannelConfigB\x03\xe0A\x03R\rchannelConfig\x12\x82\x01\n" +
	"\x10channel_strategy\x18\x02 \x01(\x0e2U.google.ads.googleads.v22.enums.DemandGenChannelStrategyEnum.DemandGenChannelStrategyH\x00R\x0fchannelStrategy\x12\xa6\x01\n" +
	"\x11selected_channels\x18\x03 \x01(\v2w.google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.DemandGenChannelControls.DemandGenSelectedChannelsH\x00R\x10selectedChannels\x1a\xe2\x01\n" +
	"\x19DemandGenSelectedChannels\x12*\n" +
	"\x11youtube_in_stream\x18\x01 \x01(\bR\x0fyoutubeInStream\x12&\n" +
	"\x0fyoutube_in_feed\x18\x02 \x01(\bR\ryoutubeInFeed\x12%\n" +
	"\x0eyoutube_shorts\x18\x03 \x01(\bR\ryoutubeShorts\x12\x1a\n" +
	"\bdiscover\x18\x04 \x01(\bR\bdiscover\x12\x14\n" +
	"\x05gmail\x18\x05 \x01(\bR\x05gmail\x12\x18\n" +
	"\adisplay\x18\x06 \x01(\bR\adisplayB\x17\n" +
	"\x15channel_configuration\x1a\xd7\x01\n" +
	"\x14VideoAdGroupSettings\x12\x87\x01\n" +
	"\x11video_ad_sequence\x18\x01 \x01(\v2[.google.ads.googleads.v22.resources.AdGroup.VideoAdGroupSettings.VideoAdSequenceStepSettingR\x0fvideoAdSequence\x1a5\n" +
	"\x1aVideoAdSequenceStepSetting\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\x03R\x06stepId\x1a|\n" +
	"\x13AiMaxAdGroupSetting\x12D\n" +
	"\x1cdisable_search_term_matching\x18\x01 \x01(\bH\x00R\x19disableSearchTermMatching\x88\x01\x01B\x1f\n" +
	"\x1d_disable_search_term_matching:U\xeaAR\n" +
	" googleads.googleapis.com/AdGroup\x12.customers/{customer_id}/adGroups/{ad_group_id}B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\x10\n" +
	"\x0e_base_ad_groupB\x18\n" +
	"\x16_tracking_url_templateB\v\n" +
	"\t_campaignB\x11\n" +
	"\x0f_cpc_bid_microsB\x1b\n" +
	"\x19_effective_cpc_bid_microsB\x11\n" +
	"\x0f_cpm_bid_microsB\x14\n" +
	"\x12_target_cpa_microsB\x11\n" +
	"\x0f_cpv_bid_microsB\x14\n" +
	"\x12_target_cpm_microsB\x0e\n" +
	"\f_target_roasB\x19\n" +
	"\x17_percent_cpc_bid_microsB\x13\n" +
	"\x11_fixed_cpm_microsB\x14\n" +
	"\x12_target_cpv_microsB\x14\n" +
	"\x12_target_cpc_microsB\x13\n" +
	"\x11_final_url_suffixB\x1e\n" +
	"\x1c_effective_target_cpa_microsB\x18\n" +
	"\x16_effective_target_roasB\x17\n" +
	"\x15_effective_target_cpcB\xfe\x01\n" +
	"&com.google.ads.googleads.v22.resourcesB\fAdGroupProtoP\x01ZKgithub.com/Optable/google-ads-pb/protogen/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V22.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V22\\Resources\xea\x02&Google::Ads::GoogleAds::V22::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v22_resources_ad_group_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_resources_ad_group_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_resources_ad_group_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_resources_ad_group_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_resources_ad_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_ad_group_proto_rawDesc), len(file_google_ads_googleads_v22_resources_ad_group_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_resources_ad_group_proto_rawDescData
}

var file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_google_ads_googleads_v22_resources_ad_group_proto_goTypes = []any{
	(*AdGroup)(nil),                                                   // 0: google.ads.googleads.v22.resources.AdGroup
	(*AdGroup_AudienceSetting)(nil),                                   // 1: google.ads.googleads.v22.resources.AdGroup.AudienceSetting
	(*AdGroup_DemandGenAdGroupSettings)(nil),                          // 2: google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings
	(*AdGroup_VideoAdGroupSettings)(nil),                              // 3: google.ads.googleads.v22.resources.AdGroup.VideoAdGroupSettings
	(*AdGroup_AiMaxAdGroupSetting)(nil),                               // 4: google.ads.googleads.v22.resources.AdGroup.AiMaxAdGroupSetting
	(*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls)(nil), // 5: google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.DemandGenChannelControls
	(*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_DemandGenSelectedChannels)(nil), // 6: google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.DemandGenChannelControls.DemandGenSelectedChannels
	(*AdGroup_VideoAdGroupSettings_VideoAdSequenceStepSetting)(nil),                             // 7: google.ads.googleads.v22.resources.AdGroup.VideoAdGroupSettings.VideoAdSequenceStepSetting
	(enums.AdGroupStatusEnum_AdGroupStatus)(0),                                                  // 8: google.ads.googleads.v22.enums.AdGroupStatusEnum.AdGroupStatus
	(enums.AdGroupTypeEnum_AdGroupType)(0),                                                      // 9: google.ads.googleads.v22.enums.AdGroupTypeEnum.AdGroupType
	(enums.AdGroupAdRotationModeEnum_AdGroupAdRotationMode)(0),                                  // 10: google.ads.googleads.v22.enums.AdGroupAdRotationModeEnum.AdGroupAdRotationMode
	(*common.CustomParameter)(nil),                                                              // 11: google.ads.googleads.v22.common.CustomParameter
	(enums.TargetingDimensionEnum_TargetingDimension)(0),                                        // 12: google.ads.googleads.v22.enums.TargetingDimensionEnum.TargetingDimension
	(*common.TargetingSetting)(nil),                                                             // 13: google.ads.googleads.v22.common.TargetingSetting
	(enums.BiddingSourceEnum_BiddingSource)(0),                                                  // 14: google.ads.googleads.v22.enums.BiddingSourceEnum.BiddingSource
	(enums.AssetFieldTypeEnum_AssetFieldType)(0),                                                // 15: google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	(enums.AssetSetTypeEnum_AssetSetType)(0),                                                    // 16: google.ads.googleads.v22.enums.AssetSetTypeEnum.AssetSetType
	(enums.AdGroupPrimaryStatusEnum_AdGroupPrimaryStatus)(0),                                    // 17: google.ads.googleads.v22.enums.AdGroupPrimaryStatusEnum.AdGroupPrimaryStatus
	(enums.AdGroupPrimaryStatusReasonEnum_AdGroupPrimaryStatusReason)(0),                        // 18: google.ads.googleads.v22.enums.AdGroupPrimaryStatusReasonEnum.AdGroupPrimaryStatusReason
	(enums.DemandGenChannelConfigEnum_DemandGenChannelConfig)(0),                                // 19: google.ads.googleads.v22.enums.DemandGenChannelConfigEnum.DemandGenChannelConfig
	(enums.DemandGenChannelStrategyEnum_DemandGenChannelStrategy)(0),                            // 20: google.ads.googleads.v22.enums.DemandGenChannelStrategyEnum.DemandGenChannelStrategy
}
var file_google_ads_googleads_v22_resources_ad_group_proto_depIdxs = []int32{
	8,  // 0: google.ads.googleads.v22.resources.AdGroup.status:type_name -> google.ads.googleads.v22.enums.AdGroupStatusEnum.AdGroupStatus
	9,  // 1: google.ads.googleads.v22.resources.AdGroup.type:type_name -> google.ads.googleads.v22.enums.AdGroupTypeEnum.AdGroupType
	10, // 2: google.ads.googleads.v22.resources.AdGroup.ad_rotation_mode:type_name -> google.ads.googleads.v22.enums.AdGroupAdRotationModeEnum.AdGroupAdRotationMode
	11, // 3: google.ads.googleads.v22.resources.AdGroup.url_custom_parameters:type_name -> google.ads.googleads.v22.common.CustomParameter
	12, // 4: google.ads.googleads.v22.resources.AdGroup.display_custom_bid_dimension:type_name -> google.ads.googleads.v22.enums.TargetingDimensionEnum.TargetingDimension
	13, // 5: google.ads.googleads.v22.resources.AdGroup.targeting_setting:type_name -> google.ads.googleads.v22.common.TargetingSetting
	1,  // 6: google.ads.googleads.v22.resources.AdGroup.audience_setting:type_name -> google.ads.googleads.v22.resources.AdGroup.AudienceSetting
	14, // 7: google.ads.googleads.v22.resources.AdGroup.effective_target_cpa_source:type_name -> google.ads.googleads.v22.enums.BiddingSourceEnum.BiddingSource
	14, // 8: google.ads.googleads.v22.resources.AdGroup.effective_target_roas_source:type_name -> google.ads.googleads.v22.enums.BiddingSourceEnum.BiddingSource
	14, // 9: google.ads.googleads.v22.resources.AdGroup.effective_target_cpc_source:type_name -> google.ads.googleads.v22.enums.BiddingSourceEnum.BiddingSource
	15, // 10: google.ads.googleads.v22.resources.AdGroup.excluded_parent_asset_field_types:type_name -> google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	16, // 11: google.ads.googleads.v22.resources.AdGroup.excluded_parent_asset_set_types:type_name -> google.ads.googleads.v22.enums.AssetSetTypeEnum.AssetSetType
	17, // 12: google.ads.googleads.v22.resources.AdGroup.primary_status:type_name -> google.ads.googleads.v22.enums.AdGroupPrimaryStatusEnum.AdGroupPrimaryStatus
	18, // 13: google.ads.googleads.v22.resources.AdGroup.primary_status_reasons:type_name -> google.ads.googleads.v22.enums.AdGroupPrimaryStatusReasonEnum.AdGroupPrimaryStatusReason
	2,  // 14: google.ads.googleads.v22.resources.AdGroup.demand_gen_ad_group_settings:type_name -> google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings
	3,  // 15: google.ads.googleads.v22.resources.AdGroup.video_ad_group_settings:type_name -> google.ads.googleads.v22.resources.AdGroup.VideoAdGroupSettings
	4,  // 16: google.ads.googleads.v22.resources.AdGroup.ai_max_ad_group_setting:type_name -> google.ads.googleads.v22.resources.AdGroup.AiMaxAdGroupSetting
	5,  // 17: google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.channel_controls:type_name -> google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.DemandGenChannelControls
	7,  // 18: google.ads.googleads.v22.resources.AdGroup.VideoAdGroupSettings.video_ad_sequence:type_name -> google.ads.googleads.v22.resources.AdGroup.VideoAdGroupSettings.VideoAdSequenceStepSetting
	19, // 19: google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.DemandGenChannelControls.channel_config:type_name -> google.ads.googleads.v22.enums.DemandGenChannelConfigEnum.DemandGenChannelConfig
	20, // 20: google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.DemandGenChannelControls.channel_strategy:type_name -> google.ads.googleads.v22.enums.DemandGenChannelStrategyEnum.DemandGenChannelStrategy
	6,  // 21: google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.DemandGenChannelControls.selected_channels:type_name -> google.ads.googleads.v22.resources.AdGroup.DemandGenAdGroupSettings.DemandGenChannelControls.DemandGenSelectedChannels
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_resources_ad_group_proto_init() }
func file_google_ads_googleads_v22_resources_ad_group_proto_init() {
	if File_google_ads_googleads_v22_resources_ad_group_proto != nil {
		return
	}
	file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[0].OneofWrappers = []any{}
	file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[4].OneofWrappers = []any{}
	file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes[5].OneofWrappers = []any{
		(*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_ChannelStrategy)(nil),
		(*AdGroup_DemandGenAdGroupSettings_DemandGenChannelControls_SelectedChannels)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_ad_group_proto_rawDesc), len(file_google_ads_googleads_v22_resources_ad_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_resources_ad_group_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_resources_ad_group_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_resources_ad_group_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_resources_ad_group_proto = out.File
	file_google_ads_googleads_v22_resources_ad_group_proto_goTypes = nil
	file_google_ads_googleads_v22_resources_ad_group_proto_depIdxs = nil
}
