// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/resources/campaign_goal_config.proto

package resources

import (
	common "github.com/Optable/google-ads-pb/protogen/common"
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A link between a campaign and a goal enabling campaign-specific optimization.
type CampaignGoalConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Immutable. The resource name of the campaign goal config.
	// campaign goal config resource names have the form:
	// `customers/{customer_id}/campaignGoalConfigs/{campaign_id}~{goal_id}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Immutable. The resource name of the campaign for this link.
	Campaign string `protobuf:"bytes,2,opt,name=campaign,proto3" json:"campaign,omitempty"`
	// Immutable. The resource name of the goal this link is attached to.
	Goal string `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	// Output only. The goal type this link is attached to.
	GoalType enums.GoalTypeEnum_GoalType `protobuf:"varint,4,opt,name=goal_type,json=goalType,proto3,enum=google.ads.googleads.v22.enums.GoalTypeEnum_GoalType" json:"goal_type,omitempty"`
	// The settings specific to this campaign goal config.
	//
	// Types that are valid to be assigned to CampaignGoalConfigSettings:
	//
	//	*CampaignGoalConfig_CampaignRetentionSettings
	CampaignGoalConfigSettings isCampaignGoalConfig_CampaignGoalConfigSettings `protobuf_oneof:"campaign_goal_config_settings"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CampaignGoalConfig) Reset() {
	*x = CampaignGoalConfig{}
	mi := &file_google_ads_googleads_v22_resources_campaign_goal_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignGoalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignGoalConfig) ProtoMessage() {}

func (x *CampaignGoalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_campaign_goal_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignGoalConfig.ProtoReflect.Descriptor instead.
func (*CampaignGoalConfig) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDescGZIP(), []int{0}
}

func (x *CampaignGoalConfig) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *CampaignGoalConfig) GetCampaign() string {
	if x != nil {
		return x.Campaign
	}
	return ""
}

func (x *CampaignGoalConfig) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CampaignGoalConfig) GetGoalType() enums.GoalTypeEnum_GoalType {
	if x != nil {
		return x.GoalType
	}
	return enums.GoalTypeEnum_GoalType(0)
}

func (x *CampaignGoalConfig) GetCampaignGoalConfigSettings() isCampaignGoalConfig_CampaignGoalConfigSettings {
	if x != nil {
		return x.CampaignGoalConfigSettings
	}
	return nil
}

func (x *CampaignGoalConfig) GetCampaignRetentionSettings() *common.CampaignGoalSettings_CampaignRetentionGoalSettings {
	if x != nil {
		if x, ok := x.CampaignGoalConfigSettings.(*CampaignGoalConfig_CampaignRetentionSettings); ok {
			return x.CampaignRetentionSettings
		}
	}
	return nil
}

type isCampaignGoalConfig_CampaignGoalConfigSettings interface {
	isCampaignGoalConfig_CampaignGoalConfigSettings()
}

type CampaignGoalConfig_CampaignRetentionSettings struct {
	// Retention goal campaign settings.
	CampaignRetentionSettings *common.CampaignGoalSettings_CampaignRetentionGoalSettings `protobuf:"bytes,5,opt,name=campaign_retention_settings,json=campaignRetentionSettings,proto3,oneof"`
}

func (*CampaignGoalConfig_CampaignRetentionSettings) isCampaignGoalConfig_CampaignGoalConfigSettings() {
}

var File_google_ads_googleads_v22_resources_campaign_goal_config_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDesc = "" +
	"\n" +
	"=google/ads/googleads/v22/resources/campaign_goal_config.proto\x12\"google.ads.googleads.v22.resources\x1a<google/ads/googleads/v22/common/campaign_goal_settings.proto\x1a.google/ads/googleads/v22/enums/goal_type.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x81\x05\n" +
	"\x12CampaignGoalConfig\x12X\n" +
	"\rresource_name\x18\x01 \x01(\tB3\xe0A\x05\xfaA-\n" +
	"+googleads.googleapis.com/CampaignGoalConfigR\fresourceName\x12E\n" +
	"\bcampaign\x18\x02 \x01(\tB)\xe0A\x05\xfaA#\n" +
	"!googleads.googleapis.com/CampaignR\bcampaign\x129\n" +
	"\x04goal\x18\x03 \x01(\tB%\xe0A\x05\xfaA\x1f\n" +
	"\x1dgoogleads.googleapis.com/GoalR\x04goal\x12W\n" +
	"\tgoal_type\x18\x04 \x01(\x0e25.google.ads.googleads.v22.enums.GoalTypeEnum.GoalTypeB\x03\xe0A\x03R\bgoalType\x12\x95\x01\n" +
	"\x1bcampaign_retention_settings\x18\x05 \x01(\v2S.google.ads.googleads.v22.common.CampaignGoalSettings.CampaignRetentionGoalSettingsH\x00R\x19campaignRetentionSettings:}\xeaAz\n" +
	"+googleads.googleapis.com/CampaignGoalConfig\x12Kcustomers/{customer_id}/campaignGoalConfigs/{campaign_id}~{unified_goal_id}B\x1f\n" +
	"\x1dcampaign_goal_config_settingsB\x89\x02\n" +
	"&com.google.ads.googleads.v22.resourcesB\x17CampaignGoalConfigProtoP\x01ZKgithub.com/Optable/google-ads-pb/protogen/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V22.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V22\\Resources\xea\x02&Google::Ads::GoogleAds::V22::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDesc), len(file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDescData
}

var file_google_ads_googleads_v22_resources_campaign_goal_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_resources_campaign_goal_config_proto_goTypes = []any{
	(*CampaignGoalConfig)(nil),                                        // 0: google.ads.googleads.v22.resources.CampaignGoalConfig
	(enums.GoalTypeEnum_GoalType)(0),                                  // 1: google.ads.googleads.v22.enums.GoalTypeEnum.GoalType
	(*common.CampaignGoalSettings_CampaignRetentionGoalSettings)(nil), // 2: google.ads.googleads.v22.common.CampaignGoalSettings.CampaignRetentionGoalSettings
}
var file_google_ads_googleads_v22_resources_campaign_goal_config_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v22.resources.CampaignGoalConfig.goal_type:type_name -> google.ads.googleads.v22.enums.GoalTypeEnum.GoalType
	2, // 1: google.ads.googleads.v22.resources.CampaignGoalConfig.campaign_retention_settings:type_name -> google.ads.googleads.v22.common.CampaignGoalSettings.CampaignRetentionGoalSettings
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_resources_campaign_goal_config_proto_init() }
func file_google_ads_googleads_v22_resources_campaign_goal_config_proto_init() {
	if File_google_ads_googleads_v22_resources_campaign_goal_config_proto != nil {
		return
	}
	file_google_ads_googleads_v22_resources_campaign_goal_config_proto_msgTypes[0].OneofWrappers = []any{
		(*CampaignGoalConfig_CampaignRetentionSettings)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDesc), len(file_google_ads_googleads_v22_resources_campaign_goal_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_resources_campaign_goal_config_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_resources_campaign_goal_config_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_resources_campaign_goal_config_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_resources_campaign_goal_config_proto = out.File
	file_google_ads_googleads_v22_resources_campaign_goal_config_proto_goTypes = nil
	file_google_ads_googleads_v22_resources_campaign_goal_config_proto_depIdxs = nil
}
