// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/resources/final_url_expansion_asset_view.proto

package resources

import (
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FinalUrlExpansionAssetView Resource.
type FinalUrlExpansionAssetView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The resource name of the FinalUrlExpansionAsset.
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Output only. Campaign in which the asset served.
	Campaign *string `protobuf:"bytes,2,opt,name=campaign,proto3,oneof" json:"campaign,omitempty"`
	// Output only. The ID of the asset.
	Asset *string `protobuf:"bytes,3,opt,name=asset,proto3,oneof" json:"asset,omitempty"`
	// Output only. The field type of the asset.
	FieldType enums.AssetFieldTypeEnum_AssetFieldType `protobuf:"varint,4,opt,name=field_type,json=fieldType,proto3,enum=google.ads.googleads.v22.enums.AssetFieldTypeEnum_AssetFieldType" json:"field_type,omitempty"`
	// Output only. Status of the FinalUrlExpansionAsset.
	Status *enums.AssetLinkStatusEnum_AssetLinkStatus `protobuf:"varint,5,opt,name=status,proto3,enum=google.ads.googleads.v22.enums.AssetLinkStatusEnum_AssetLinkStatus,oneof" json:"status,omitempty"`
	// Output only. Final URL of the FinalUrlExpansionAsset.
	FinalUrl string `protobuf:"bytes,6,opt,name=final_url,json=finalUrl,proto3" json:"final_url,omitempty"`
	// Serving level of FinalUrlExpansionAsset.
	//
	// Types that are valid to be assigned to Level:
	//
	//	*FinalUrlExpansionAssetView_AdGroup
	//	*FinalUrlExpansionAssetView_AssetGroup
	Level         isFinalUrlExpansionAssetView_Level `protobuf_oneof:"level"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalUrlExpansionAssetView) Reset() {
	*x = FinalUrlExpansionAssetView{}
	mi := &file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalUrlExpansionAssetView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalUrlExpansionAssetView) ProtoMessage() {}

func (x *FinalUrlExpansionAssetView) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalUrlExpansionAssetView.ProtoReflect.Descriptor instead.
func (*FinalUrlExpansionAssetView) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDescGZIP(), []int{0}
}

func (x *FinalUrlExpansionAssetView) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *FinalUrlExpansionAssetView) GetCampaign() string {
	if x != nil && x.Campaign != nil {
		return *x.Campaign
	}
	return ""
}

func (x *FinalUrlExpansionAssetView) GetAsset() string {
	if x != nil && x.Asset != nil {
		return *x.Asset
	}
	return ""
}

func (x *FinalUrlExpansionAssetView) GetFieldType() enums.AssetFieldTypeEnum_AssetFieldType {
	if x != nil {
		return x.FieldType
	}
	return enums.AssetFieldTypeEnum_AssetFieldType(0)
}

func (x *FinalUrlExpansionAssetView) GetStatus() enums.AssetLinkStatusEnum_AssetLinkStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return enums.AssetLinkStatusEnum_AssetLinkStatus(0)
}

func (x *FinalUrlExpansionAssetView) GetFinalUrl() string {
	if x != nil {
		return x.FinalUrl
	}
	return ""
}

func (x *FinalUrlExpansionAssetView) GetLevel() isFinalUrlExpansionAssetView_Level {
	if x != nil {
		return x.Level
	}
	return nil
}

func (x *FinalUrlExpansionAssetView) GetAdGroup() string {
	if x != nil {
		if x, ok := x.Level.(*FinalUrlExpansionAssetView_AdGroup); ok {
			return x.AdGroup
		}
	}
	return ""
}

func (x *FinalUrlExpansionAssetView) GetAssetGroup() string {
	if x != nil {
		if x, ok := x.Level.(*FinalUrlExpansionAssetView_AssetGroup); ok {
			return x.AssetGroup
		}
	}
	return ""
}

type isFinalUrlExpansionAssetView_Level interface {
	isFinalUrlExpansionAssetView_Level()
}

type FinalUrlExpansionAssetView_AdGroup struct {
	// Output only. Ad Group in which FinalUrlExpansionAsset served.
	AdGroup string `protobuf:"bytes,7,opt,name=ad_group,json=adGroup,proto3,oneof"`
}

type FinalUrlExpansionAssetView_AssetGroup struct {
	// Output only. Asset Group in which FinalUrlExpansionAsset served.
	AssetGroup string `protobuf:"bytes,8,opt,name=asset_group,json=assetGroup,proto3,oneof"`
}

func (*FinalUrlExpansionAssetView_AdGroup) isFinalUrlExpansionAssetView_Level() {}

func (*FinalUrlExpansionAssetView_AssetGroup) isFinalUrlExpansionAssetView_Level() {}

var File_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDesc = "" +
	"\n" +
	"Ggoogle/ads/googleads/v22/resources/final_url_expansion_asset_view.proto\x12\"google.ads.googleads.v22.resources\x1a5google/ads/googleads/v22/enums/asset_field_type.proto\x1a6google/ads/googleads/v22/enums/asset_link_status.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\x98\a\n" +
	"\x1aFinalUrlExpansionAssetView\x12`\n" +
	"\rresource_name\x18\x01 \x01(\tB;\xe0A\x03\xfaA5\n" +
	"3googleads.googleapis.com/FinalUrlExpansionAssetViewR\fresourceName\x12J\n" +
	"\bcampaign\x18\x02 \x01(\tB)\xe0A\x03\xfaA#\n" +
	"!googleads.googleapis.com/CampaignH\x01R\bcampaign\x88\x01\x01\x12A\n" +
	"\x05asset\x18\x03 \x01(\tB&\xe0A\x03\xfaA \n" +
	"\x1egoogleads.googleapis.com/AssetH\x02R\x05asset\x88\x01\x01\x12e\n" +
	"\n" +
	"field_type\x18\x04 \x01(\x0e2A.google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldTypeB\x03\xe0A\x03R\tfieldType\x12e\n" +
	"\x06status\x18\x05 \x01(\x0e2C.google.ads.googleads.v22.enums.AssetLinkStatusEnum.AssetLinkStatusB\x03\xe0A\x03H\x03R\x06status\x88\x01\x01\x12 \n" +
	"\tfinal_url\x18\x06 \x01(\tB\x03\xe0A\x03R\bfinalUrl\x12E\n" +
	"\bad_group\x18\a \x01(\tB(\xe0A\x03\xfaA\"\n" +
	" googleads.googleapis.com/AdGroupH\x00R\aadGroup\x12N\n" +
	"\vasset_group\x18\b \x01(\tB+\xe0A\x03\xfaA%\n" +
	"#googleads.googleapis.com/AssetGroupH\x00R\n" +
	"assetGroup:\xd6\x01\xeaA\xd2\x01\n" +
	"3googleads.googleapis.com/FinalUrlExpansionAssetView\x12bcustomers/{customer_id}/finalUrlExpansionAssetViews/{campaign_id}~{asset_id}~{field_type}~{url_fp}*\x1bfinalUrlExpansionAssetViews2\x1afinalUrlExpansionAssetViewB\a\n" +
	"\x05levelB\v\n" +
	"\t_campaignB\b\n" +
	"\x06_assetB\t\n" +
	"\a_statusB\x91\x02\n" +
	"&com.google.ads.googleads.v22.resourcesB\x1fFinalUrlExpansionAssetViewProtoP\x01ZKgithub.com/Optable/google-ads-pb/protogen/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V22.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V22\\Resources\xea\x02&Google::Ads::GoogleAds::V22::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDesc), len(file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDescData
}

var file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_goTypes = []any{
	(*FinalUrlExpansionAssetView)(nil),             // 0: google.ads.googleads.v22.resources.FinalUrlExpansionAssetView
	(enums.AssetFieldTypeEnum_AssetFieldType)(0),   // 1: google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	(enums.AssetLinkStatusEnum_AssetLinkStatus)(0), // 2: google.ads.googleads.v22.enums.AssetLinkStatusEnum.AssetLinkStatus
}
var file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v22.resources.FinalUrlExpansionAssetView.field_type:type_name -> google.ads.googleads.v22.enums.AssetFieldTypeEnum.AssetFieldType
	2, // 1: google.ads.googleads.v22.resources.FinalUrlExpansionAssetView.status:type_name -> google.ads.googleads.v22.enums.AssetLinkStatusEnum.AssetLinkStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_init() }
func file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_init() {
	if File_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto != nil {
		return
	}
	file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_msgTypes[0].OneofWrappers = []any{
		(*FinalUrlExpansionAssetView_AdGroup)(nil),
		(*FinalUrlExpansionAssetView_AssetGroup)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDesc), len(file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto = out.File
	file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_goTypes = nil
	file_google_ads_googleads_v22_resources_final_url_expansion_asset_view_proto_depIdxs = nil
}
