// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/resources/goal.proto

package resources

import (
	common "github.com/Optable/google-ads-pb/protogen/common"
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Representation of goals.
type Goal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Immutable. The resource name of the goal.
	// Goal resource names have the form:
	// `customers/{customer_id}/goals/{goal_id}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Output only. The ID of this goal.
	GoalId *int64 `protobuf:"varint,2,opt,name=goal_id,json=goalId,proto3,oneof" json:"goal_id,omitempty"`
	// Output only. The type of this goal.
	GoalType enums.GoalTypeEnum_GoalType `protobuf:"varint,3,opt,name=goal_type,json=goalType,proto3,enum=google.ads.googleads.v22.enums.GoalTypeEnum_GoalType" json:"goal_type,omitempty"`
	// Output only. The resource name of the goal owner customer.
	OwnerCustomer *string `protobuf:"bytes,4,opt,name=owner_customer,json=ownerCustomer,proto3,oneof" json:"owner_customer,omitempty"`
	// Output only. Indicates if this goal is eligible for campaign optimization.
	OptimizationEligibility enums.GoalOptimizationEligibilityEnum_GoalOptimizationEligibility `protobuf:"varint,6,opt,name=optimization_eligibility,json=optimizationEligibility,proto3,enum=google.ads.googleads.v22.enums.GoalOptimizationEligibilityEnum_GoalOptimizationEligibility" json:"optimization_eligibility,omitempty"`
	// The settings specific to this goal.
	//
	// Types that are valid to be assigned to GoalSettings:
	//
	//	*Goal_RetentionGoalSettings
	GoalSettings  isGoal_GoalSettings `protobuf_oneof:"goal_settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goal) Reset() {
	*x = Goal{}
	mi := &file_google_ads_googleads_v22_resources_goal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goal) ProtoMessage() {}

func (x *Goal) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_goal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goal.ProtoReflect.Descriptor instead.
func (*Goal) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_goal_proto_rawDescGZIP(), []int{0}
}

func (x *Goal) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *Goal) GetGoalId() int64 {
	if x != nil && x.GoalId != nil {
		return *x.GoalId
	}
	return 0
}

func (x *Goal) GetGoalType() enums.GoalTypeEnum_GoalType {
	if x != nil {
		return x.GoalType
	}
	return enums.GoalTypeEnum_GoalType(0)
}

func (x *Goal) GetOwnerCustomer() string {
	if x != nil && x.OwnerCustomer != nil {
		return *x.OwnerCustomer
	}
	return ""
}

func (x *Goal) GetOptimizationEligibility() enums.GoalOptimizationEligibilityEnum_GoalOptimizationEligibility {
	if x != nil {
		return x.OptimizationEligibility
	}
	return enums.GoalOptimizationEligibilityEnum_GoalOptimizationEligibility(0)
}

func (x *Goal) GetGoalSettings() isGoal_GoalSettings {
	if x != nil {
		return x.GoalSettings
	}
	return nil
}

func (x *Goal) GetRetentionGoalSettings() *common.GoalSetting_RetentionGoal {
	if x != nil {
		if x, ok := x.GoalSettings.(*Goal_RetentionGoalSettings); ok {
			return x.RetentionGoalSettings
		}
	}
	return nil
}

type isGoal_GoalSettings interface {
	isGoal_GoalSettings()
}

type Goal_RetentionGoalSettings struct {
	// Retention goal settings.
	RetentionGoalSettings *common.GoalSetting_RetentionGoal `protobuf:"bytes,7,opt,name=retention_goal_settings,json=retentionGoalSettings,proto3,oneof"`
}

func (*Goal_RetentionGoalSettings) isGoal_GoalSettings() {}

var File_google_ads_googleads_v22_resources_goal_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_resources_goal_proto_rawDesc = "" +
	"\n" +
	"-google/ads/googleads/v22/resources/goal.proto\x12\"google.ads.googleads.v22.resources\x1a2google/ads/googleads/v22/common/goal_setting.proto\x1aBgoogle/ads/googleads/v22/enums/goal_optimization_eligibility.proto\x1a.google/ads/googleads/v22/enums/goal_type.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xbe\x05\n" +
	"\x04Goal\x12J\n" +
	"\rresource_name\x18\x01 \x01(\tB%\xe0A\x05\xfaA\x1f\n" +
	"\x1dgoogleads.googleapis.com/GoalR\fresourceName\x12!\n" +
	"\agoal_id\x18\x02 \x01(\x03B\x03\xe0A\x03H\x01R\x06goalId\x88\x01\x01\x12W\n" +
	"\tgoal_type\x18\x03 \x01(\x0e25.google.ads.googleads.v22.enums.GoalTypeEnum.GoalTypeB\x03\xe0A\x03R\bgoalType\x12U\n" +
	"\x0eowner_customer\x18\x04 \x01(\tB)\xe0A\x03\xfaA#\n" +
	"!googleads.googleapis.com/CustomerH\x02R\rownerCustomer\x88\x01\x01\x12\x9b\x01\n" +
	"\x18optimization_eligibility\x18\x06 \x01(\x0e2[.google.ads.googleads.v22.enums.GoalOptimizationEligibilityEnum.GoalOptimizationEligibilityB\x03\xe0A\x03R\x17optimizationEligibility\x12t\n" +
	"\x17retention_goal_settings\x18\a \x01(\v2:.google.ads.googleads.v22.common.GoalSetting.RetentionGoalH\x00R\x15retentionGoalSettings:S\xeaAP\n" +
	"\x1dgoogleads.googleapis.com/Goal\x12/customers/{customer_id}/goals/{unified_goal_id}B\x0f\n" +
	"\rgoal_settingsB\n" +
	"\n" +
	"\b_goal_idB\x11\n" +
	"\x0f_owner_customerB\xfb\x01\n" +
	"&com.google.ads.googleads.v22.resourcesB\tGoalProtoP\x01ZKgithub.com/Optable/google-ads-pb/protogen/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V22.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V22\\Resources\xea\x02&Google::Ads::GoogleAds::V22::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v22_resources_goal_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_resources_goal_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_resources_goal_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_resources_goal_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_resources_goal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_goal_proto_rawDesc), len(file_google_ads_googleads_v22_resources_goal_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_resources_goal_proto_rawDescData
}

var file_google_ads_googleads_v22_resources_goal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_resources_goal_proto_goTypes = []any{
	(*Goal)(nil),                     // 0: google.ads.googleads.v22.resources.Goal
	(enums.GoalTypeEnum_GoalType)(0), // 1: google.ads.googleads.v22.enums.GoalTypeEnum.GoalType
	(enums.GoalOptimizationEligibilityEnum_GoalOptimizationEligibility)(0), // 2: google.ads.googleads.v22.enums.GoalOptimizationEligibilityEnum.GoalOptimizationEligibility
	(*common.GoalSetting_RetentionGoal)(nil),                               // 3: google.ads.googleads.v22.common.GoalSetting.RetentionGoal
}
var file_google_ads_googleads_v22_resources_goal_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v22.resources.Goal.goal_type:type_name -> google.ads.googleads.v22.enums.GoalTypeEnum.GoalType
	2, // 1: google.ads.googleads.v22.resources.Goal.optimization_eligibility:type_name -> google.ads.googleads.v22.enums.GoalOptimizationEligibilityEnum.GoalOptimizationEligibility
	3, // 2: google.ads.googleads.v22.resources.Goal.retention_goal_settings:type_name -> google.ads.googleads.v22.common.GoalSetting.RetentionGoal
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_resources_goal_proto_init() }
func file_google_ads_googleads_v22_resources_goal_proto_init() {
	if File_google_ads_googleads_v22_resources_goal_proto != nil {
		return
	}
	file_google_ads_googleads_v22_resources_goal_proto_msgTypes[0].OneofWrappers = []any{
		(*Goal_RetentionGoalSettings)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_goal_proto_rawDesc), len(file_google_ads_googleads_v22_resources_goal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_resources_goal_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_resources_goal_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_resources_goal_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_resources_goal_proto = out.File
	file_google_ads_googleads_v22_resources_goal_proto_goTypes = nil
	file_google_ads_googleads_v22_resources_goal_proto_depIdxs = nil
}
