// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/resources/group_content_suitability_placement_view.proto

package resources

import (
	enums "github.com/Optable/google-ads-pb/protogen/enums"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A group content suitability placement view.
type GroupContentSuitabilityPlacementView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Output only. The resource name of the group content suitability placement
	// view. Group content suitability placement view resource names have the
	// form:
	//
	// `customers/{customer_id}/groupContentSuitabilityPlacementViews/{placement_fingerprint}`
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// Output only. The display name is URL for websites, YouTube video name for
	// YouTube videos, and translated mobile app name for mobile apps.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Output only. The automatic placement string at group level, for example.
	// website url, mobile application id, or a YouTube video id.
	Placement string `protobuf:"bytes,3,opt,name=placement,proto3" json:"placement,omitempty"`
	// Output only. Represents the type of the placement, for example, Website,
	// YouTubeVideo and MobileApplication.
	PlacementType enums.PlacementTypeEnum_PlacementType `protobuf:"varint,4,opt,name=placement_type,json=placementType,proto3,enum=google.ads.googleads.v22.enums.PlacementTypeEnum_PlacementType" json:"placement_type,omitempty"`
	// Output only. URL of the placement, for example, website, link to the mobile
	// application in app store, or a YouTube video URL.
	TargetUrl     string `protobuf:"bytes,5,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupContentSuitabilityPlacementView) Reset() {
	*x = GroupContentSuitabilityPlacementView{}
	mi := &file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupContentSuitabilityPlacementView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupContentSuitabilityPlacementView) ProtoMessage() {}

func (x *GroupContentSuitabilityPlacementView) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupContentSuitabilityPlacementView.ProtoReflect.Descriptor instead.
func (*GroupContentSuitabilityPlacementView) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDescGZIP(), []int{0}
}

func (x *GroupContentSuitabilityPlacementView) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *GroupContentSuitabilityPlacementView) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GroupContentSuitabilityPlacementView) GetPlacement() string {
	if x != nil {
		return x.Placement
	}
	return ""
}

func (x *GroupContentSuitabilityPlacementView) GetPlacementType() enums.PlacementTypeEnum_PlacementType {
	if x != nil {
		return x.PlacementType
	}
	return enums.PlacementTypeEnum_PlacementType(0)
}

func (x *GroupContentSuitabilityPlacementView) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

var File_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDesc = "" +
	"\n" +
	"Qgoogle/ads/googleads/v22/resources/group_content_suitability_placement_view.proto\x12\"google.ads.googleads.v22.resources\x1a3google/ads/googleads/v22/enums/placement_type.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x19google/api/resource.proto\"\xd8\x04\n" +
	"$GroupContentSuitabilityPlacementView\x12j\n" +
	"\rresource_name\x18\x01 \x01(\tBE\xe0A\x03\xfaA?\n" +
	"=googleads.googleapis.com/GroupContentSuitabilityPlacementViewR\fresourceName\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\x03\xe0A\x03R\vdisplayName\x12!\n" +
	"\tplacement\x18\x03 \x01(\tB\x03\xe0A\x03R\tplacement\x12k\n" +
	"\x0eplacement_type\x18\x04 \x01(\x0e2?.google.ads.googleads.v22.enums.PlacementTypeEnum.PlacementTypeB\x03\xe0A\x03R\rplacementType\x12\"\n" +
	"\n" +
	"target_url\x18\x05 \x01(\tB\x03\xe0A\x03R\ttargetUrl:\xe7\x01\xeaA\xe3\x01\n" +
	"=googleads.googleapis.com/GroupContentSuitabilityPlacementView\x12Ucustomers/{customer_id}/groupContentSuitabilityPlacementViews/{placement_fingerprint}*%groupContentSuitabilityPlacementViews2$groupContentSuitabilityPlacementViewB\x9b\x02\n" +
	"&com.google.ads.googleads.v22.resourcesB)GroupContentSuitabilityPlacementViewProtoP\x01ZKgithub.com/Optable/google-ads-pb/protogen/resources;resources\xa2\x02\x03GAA\xaa\x02\"Google.Ads.GoogleAds.V22.Resources\xca\x02\"Google\\Ads\\GoogleAds\\V22\\Resources\xea\x02&Google::Ads::GoogleAds::V22::Resourcesb\x06proto3"

var (
	file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDesc), len(file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDescData
}

var file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_goTypes = []any{
	(*GroupContentSuitabilityPlacementView)(nil), // 0: google.ads.googleads.v22.resources.GroupContentSuitabilityPlacementView
	(enums.PlacementTypeEnum_PlacementType)(0),   // 1: google.ads.googleads.v22.enums.PlacementTypeEnum.PlacementType
}
var file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_depIdxs = []int32{
	1, // 0: google.ads.googleads.v22.resources.GroupContentSuitabilityPlacementView.placement_type:type_name -> google.ads.googleads.v22.enums.PlacementTypeEnum.PlacementType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_init()
}
func file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_init() {
	if File_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDesc), len(file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_depIdxs,
		MessageInfos:      file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto = out.File
	file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_goTypes = nil
	file_google_ads_googleads_v22_resources_group_content_suitability_placement_view_proto_depIdxs = nil
}
