// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/errors/asset_generation_error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing GenAI asset generation errors.
type AssetGenerationErrorEnum_AssetGenerationError int32

const (
	// Enum unspecified.
	AssetGenerationErrorEnum_UNSPECIFIED AssetGenerationErrorEnum_AssetGenerationError = 0
	// The received error code is not known in this version.
	AssetGenerationErrorEnum_UNKNOWN AssetGenerationErrorEnum_AssetGenerationError = 1
	// No assets were generated for the given request.
	AssetGenerationErrorEnum_NO_ASSETS_GENERATED AssetGenerationErrorEnum_AssetGenerationError = 2
	// A final URL is required but was not provided, and could not be sourced
	// from the existing generation context because no existing generation
	// context was provided.
	AssetGenerationErrorEnum_FINAL_URL_REQUIRED AssetGenerationErrorEnum_AssetGenerationError = 3
	// A final URL is required but was not provided, and could not be sourced
	// from the provided existing generation context.
	AssetGenerationErrorEnum_GENERATION_CONTEXT_MISSING_FINAL_URL AssetGenerationErrorEnum_AssetGenerationError = 4
	// The provided final URL is considered sensitive, and assets cannot be
	// generated.
	AssetGenerationErrorEnum_FINAL_URL_SENSITIVE AssetGenerationErrorEnum_AssetGenerationError = 5
	// The language of the provided final URL is not supported.
	AssetGenerationErrorEnum_FINAL_URL_UNSUPPORTED_LANGUAGE AssetGenerationErrorEnum_AssetGenerationError = 6
	// The provided final URL was not indexed or could otherwise not be
	// processed.
	AssetGenerationErrorEnum_FINAL_URL_UNAVAILABLE AssetGenerationErrorEnum_AssetGenerationError = 7
	// Campaign type is required but was not provided, and could not be sourced
	// from the existing generation context because no existing generation
	// context was provided.
	AssetGenerationErrorEnum_CAMPAIGN_TYPE_REQUIRED AssetGenerationErrorEnum_AssetGenerationError = 8
	// The provided campaign type is not supported for this asset generation
	// operation.
	AssetGenerationErrorEnum_UNSUPPORTED_CAMPAIGN_TYPE AssetGenerationErrorEnum_AssetGenerationError = 9
	// The provided field type is not supported for this asset generation
	// operation.
	AssetGenerationErrorEnum_UNSUPPORTED_FIELD_TYPE AssetGenerationErrorEnum_AssetGenerationError = 10
	// The provided field type is not supported for the given campaign type.
	AssetGenerationErrorEnum_UNSUPPORTED_FIELD_TYPE_FOR_CAMPAIGN_TYPE AssetGenerationErrorEnum_AssetGenerationError = 11
	// The language of the provided freeform prompt is not supported.
	AssetGenerationErrorEnum_FREEFORM_PROMPT_UNSUPPORTED_LANGUAGE AssetGenerationErrorEnum_AssetGenerationError = 12
	// The provided freeform prompt is considered sensitive, and assets cannot
	// be generated.
	AssetGenerationErrorEnum_FREEFORM_PROMPT_SENSITIVE AssetGenerationErrorEnum_AssetGenerationError = 13
	// The provided image file size exceeds the limit.
	AssetGenerationErrorEnum_INPUT_IMAGE_FILE_SIZE_TOO_LARGE AssetGenerationErrorEnum_AssetGenerationError = 14
	// The provided image is empty.
	AssetGenerationErrorEnum_INPUT_IMAGE_EMPTY AssetGenerationErrorEnum_AssetGenerationError = 15
	// Exactly one generation type must be provided.
	AssetGenerationErrorEnum_GENERATION_TYPE_REQUIRED AssetGenerationErrorEnum_AssetGenerationError = 16
	// Too many keywords provided in request.
	AssetGenerationErrorEnum_TOO_MANY_KEYWORDS AssetGenerationErrorEnum_AssetGenerationError = 17
	// A provided keyword does not have a valid length.
	AssetGenerationErrorEnum_KEYWORD_INVALID_LENGTH AssetGenerationErrorEnum_AssetGenerationError = 18
	// All keywords were filtered out.
	AssetGenerationErrorEnum_NO_VALID_KEYWORDS AssetGenerationErrorEnum_AssetGenerationError = 19
	// The provided freeform prompt does not have a valid length.
	AssetGenerationErrorEnum_FREEFORM_PROMPT_INVALID_LENGTH AssetGenerationErrorEnum_AssetGenerationError = 20
	// The provided freeform prompt references children.
	AssetGenerationErrorEnum_FREEFORM_PROMPT_REFERENCES_CHILDREN AssetGenerationErrorEnum_AssetGenerationError = 21
	// The provided freeform prompt references specific people.
	AssetGenerationErrorEnum_FREEFORM_PROMPT_REFERENCES_SPECIFIC_PEOPLE AssetGenerationErrorEnum_AssetGenerationError = 22
	// The provided freeform prompt violates Ads Policy.
	AssetGenerationErrorEnum_FREEFORM_PROMPT_VIOLATES_ADS_POLICY AssetGenerationErrorEnum_AssetGenerationError = 23
	// The provided freeform prompt contains brand content.
	AssetGenerationErrorEnum_FREEFORM_PROMPT_BRAND_CONTENT AssetGenerationErrorEnum_AssetGenerationError = 24
	// The provided image depicts children.
	AssetGenerationErrorEnum_INPUT_IMAGE_DEPICTS_CHILDREN AssetGenerationErrorEnum_AssetGenerationError = 25
	// The provided image contains brand content.
	AssetGenerationErrorEnum_INPUT_IMAGE_CONTAINS_BRAND_CONTENT AssetGenerationErrorEnum_AssetGenerationError = 26
	// The provided image contains sensitive subject matter.
	AssetGenerationErrorEnum_INPUT_IMAGE_SENSITIVE AssetGenerationErrorEnum_AssetGenerationError = 27
	// The provided image may violate Google Ads policies.
	AssetGenerationErrorEnum_INPUT_IMAGE_VIOLATES_POLICY AssetGenerationErrorEnum_AssetGenerationError = 28
	// All output images were filtered out because they included depictions of
	// children.
	AssetGenerationErrorEnum_ALL_OUTPUT_IMAGES_FILTERED_OUT_CHILDREN_DEPICTION AssetGenerationErrorEnum_AssetGenerationError = 29
	// All output images were filtered out because they included depictions of
	// specific people.
	AssetGenerationErrorEnum_ALL_OUTPUT_IMAGES_FILTERED_OUT_SPECIFIC_PEOPLE AssetGenerationErrorEnum_AssetGenerationError = 30
	// All output images were filtered out for a reason not covered by a more
	// specific error code.
	AssetGenerationErrorEnum_ALL_OUTPUT_IMAGES_FILTERED_OUT AssetGenerationErrorEnum_AssetGenerationError = 31
	// At least one input image is required for certain requests.
	AssetGenerationErrorEnum_INPUT_IMAGE_REQUIRED AssetGenerationErrorEnum_AssetGenerationError = 32
	// The provided image is of an unsupported type.
	AssetGenerationErrorEnum_INPUT_IMAGE_UNSUPPORTED_IMAGE_TYPE AssetGenerationErrorEnum_AssetGenerationError = 33
	// Asset Group could not be found with the provided ID.
	AssetGenerationErrorEnum_CONTEXT_ASSET_GROUP_NOT_FOUND AssetGenerationErrorEnum_AssetGenerationError = 34
	// Ad Group Ad could not be found with the provided ID combination.
	AssetGenerationErrorEnum_CONTEXT_AD_GROUP_AD_NOT_FOUND AssetGenerationErrorEnum_AssetGenerationError = 35
	// Could not find Campaign associated with the provided generation context.
	AssetGenerationErrorEnum_CONTEXT_CAMPAIGN_NOT_FOUND AssetGenerationErrorEnum_AssetGenerationError = 36
)

// Enum value maps for AssetGenerationErrorEnum_AssetGenerationError.
var (
	AssetGenerationErrorEnum_AssetGenerationError_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "UNKNOWN",
		2:  "NO_ASSETS_GENERATED",
		3:  "FINAL_URL_REQUIRED",
		4:  "GENERATION_CONTEXT_MISSING_FINAL_URL",
		5:  "FINAL_URL_SENSITIVE",
		6:  "FINAL_URL_UNSUPPORTED_LANGUAGE",
		7:  "FINAL_URL_UNAVAILABLE",
		8:  "CAMPAIGN_TYPE_REQUIRED",
		9:  "UNSUPPORTED_CAMPAIGN_TYPE",
		10: "UNSUPPORTED_FIELD_TYPE",
		11: "UNSUPPORTED_FIELD_TYPE_FOR_CAMPAIGN_TYPE",
		12: "FREEFORM_PROMPT_UNSUPPORTED_LANGUAGE",
		13: "FREEFORM_PROMPT_SENSITIVE",
		14: "INPUT_IMAGE_FILE_SIZE_TOO_LARGE",
		15: "INPUT_IMAGE_EMPTY",
		16: "GENERATION_TYPE_REQUIRED",
		17: "TOO_MANY_KEYWORDS",
		18: "KEYWORD_INVALID_LENGTH",
		19: "NO_VALID_KEYWORDS",
		20: "FREEFORM_PROMPT_INVALID_LENGTH",
		21: "FREEFORM_PROMPT_REFERENCES_CHILDREN",
		22: "FREEFORM_PROMPT_REFERENCES_SPECIFIC_PEOPLE",
		23: "FREEFORM_PROMPT_VIOLATES_ADS_POLICY",
		24: "FREEFORM_PROMPT_BRAND_CONTENT",
		25: "INPUT_IMAGE_DEPICTS_CHILDREN",
		26: "INPUT_IMAGE_CONTAINS_BRAND_CONTENT",
		27: "INPUT_IMAGE_SENSITIVE",
		28: "INPUT_IMAGE_VIOLATES_POLICY",
		29: "ALL_OUTPUT_IMAGES_FILTERED_OUT_CHILDREN_DEPICTION",
		30: "ALL_OUTPUT_IMAGES_FILTERED_OUT_SPECIFIC_PEOPLE",
		31: "ALL_OUTPUT_IMAGES_FILTERED_OUT",
		32: "INPUT_IMAGE_REQUIRED",
		33: "INPUT_IMAGE_UNSUPPORTED_IMAGE_TYPE",
		34: "CONTEXT_ASSET_GROUP_NOT_FOUND",
		35: "CONTEXT_AD_GROUP_AD_NOT_FOUND",
		36: "CONTEXT_CAMPAIGN_NOT_FOUND",
	}
	AssetGenerationErrorEnum_AssetGenerationError_value = map[string]int32{
		"UNSPECIFIED":                                       0,
		"UNKNOWN":                                           1,
		"NO_ASSETS_GENERATED":                               2,
		"FINAL_URL_REQUIRED":                                3,
		"GENERATION_CONTEXT_MISSING_FINAL_URL":              4,
		"FINAL_URL_SENSITIVE":                               5,
		"FINAL_URL_UNSUPPORTED_LANGUAGE":                    6,
		"FINAL_URL_UNAVAILABLE":                             7,
		"CAMPAIGN_TYPE_REQUIRED":                            8,
		"UNSUPPORTED_CAMPAIGN_TYPE":                         9,
		"UNSUPPORTED_FIELD_TYPE":                            10,
		"UNSUPPORTED_FIELD_TYPE_FOR_CAMPAIGN_TYPE":          11,
		"FREEFORM_PROMPT_UNSUPPORTED_LANGUAGE":              12,
		"FREEFORM_PROMPT_SENSITIVE":                         13,
		"INPUT_IMAGE_FILE_SIZE_TOO_LARGE":                   14,
		"INPUT_IMAGE_EMPTY":                                 15,
		"GENERATION_TYPE_REQUIRED":                          16,
		"TOO_MANY_KEYWORDS":                                 17,
		"KEYWORD_INVALID_LENGTH":                            18,
		"NO_VALID_KEYWORDS":                                 19,
		"FREEFORM_PROMPT_INVALID_LENGTH":                    20,
		"FREEFORM_PROMPT_REFERENCES_CHILDREN":               21,
		"FREEFORM_PROMPT_REFERENCES_SPECIFIC_PEOPLE":        22,
		"FREEFORM_PROMPT_VIOLATES_ADS_POLICY":               23,
		"FREEFORM_PROMPT_BRAND_CONTENT":                     24,
		"INPUT_IMAGE_DEPICTS_CHILDREN":                      25,
		"INPUT_IMAGE_CONTAINS_BRAND_CONTENT":                26,
		"INPUT_IMAGE_SENSITIVE":                             27,
		"INPUT_IMAGE_VIOLATES_POLICY":                       28,
		"ALL_OUTPUT_IMAGES_FILTERED_OUT_CHILDREN_DEPICTION": 29,
		"ALL_OUTPUT_IMAGES_FILTERED_OUT_SPECIFIC_PEOPLE":    30,
		"ALL_OUTPUT_IMAGES_FILTERED_OUT":                    31,
		"INPUT_IMAGE_REQUIRED":                              32,
		"INPUT_IMAGE_UNSUPPORTED_IMAGE_TYPE":                33,
		"CONTEXT_ASSET_GROUP_NOT_FOUND":                     34,
		"CONTEXT_AD_GROUP_AD_NOT_FOUND":                     35,
		"CONTEXT_CAMPAIGN_NOT_FOUND":                        36,
	}
)

func (x AssetGenerationErrorEnum_AssetGenerationError) Enum() *AssetGenerationErrorEnum_AssetGenerationError {
	p := new(AssetGenerationErrorEnum_AssetGenerationError)
	*p = x
	return p
}

func (x AssetGenerationErrorEnum_AssetGenerationError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetGenerationErrorEnum_AssetGenerationError) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_errors_asset_generation_error_proto_enumTypes[0].Descriptor()
}

func (AssetGenerationErrorEnum_AssetGenerationError) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_errors_asset_generation_error_proto_enumTypes[0]
}

func (x AssetGenerationErrorEnum_AssetGenerationError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetGenerationErrorEnum_AssetGenerationError.Descriptor instead.
func (AssetGenerationErrorEnum_AssetGenerationError) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing GenAI asset generation errors.
type AssetGenerationErrorEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetGenerationErrorEnum) Reset() {
	*x = AssetGenerationErrorEnum{}
	mi := &file_google_ads_googleads_v22_errors_asset_generation_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetGenerationErrorEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetGenerationErrorEnum) ProtoMessage() {}

func (x *AssetGenerationErrorEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_errors_asset_generation_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetGenerationErrorEnum.ProtoReflect.Descriptor instead.
func (*AssetGenerationErrorEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_errors_asset_generation_error_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDesc = "" +
	"\n" +
	"<google/ads/googleads/v22/errors/asset_generation_error.proto\x12\x1fgoogle.ads.googleads.v22.errors\"\xfc\t\n" +
	"\x18AssetGenerationErrorEnum\"\xdf\t\n" +
	"\x14AssetGenerationError\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\x17\n" +
	"\x13NO_ASSETS_GENERATED\x10\x02\x12\x16\n" +
	"\x12FINAL_URL_REQUIRED\x10\x03\x12(\n" +
	"$GENERATION_CONTEXT_MISSING_FINAL_URL\x10\x04\x12\x17\n" +
	"\x13FINAL_URL_SENSITIVE\x10\x05\x12\"\n" +
	"\x1eFINAL_URL_UNSUPPORTED_LANGUAGE\x10\x06\x12\x19\n" +
	"\x15FINAL_URL_UNAVAILABLE\x10\a\x12\x1a\n" +
	"\x16CAMPAIGN_TYPE_REQUIRED\x10\b\x12\x1d\n" +
	"\x19UNSUPPORTED_CAMPAIGN_TYPE\x10\t\x12\x1a\n" +
	"\x16UNSUPPORTED_FIELD_TYPE\x10\n" +
	"\x12,\n" +
	"(UNSUPPORTED_FIELD_TYPE_FOR_CAMPAIGN_TYPE\x10\v\x12(\n" +
	"$FREEFORM_PROMPT_UNSUPPORTED_LANGUAGE\x10\f\x12\x1d\n" +
	"\x19FREEFORM_PROMPT_SENSITIVE\x10\r\x12#\n" +
	"\x1fINPUT_IMAGE_FILE_SIZE_TOO_LARGE\x10\x0e\x12\x15\n" +
	"\x11INPUT_IMAGE_EMPTY\x10\x0f\x12\x1c\n" +
	"\x18GENERATION_TYPE_REQUIRED\x10\x10\x12\x15\n" +
	"\x11TOO_MANY_KEYWORDS\x10\x11\x12\x1a\n" +
	"\x16KEYWORD_INVALID_LENGTH\x10\x12\x12\x15\n" +
	"\x11NO_VALID_KEYWORDS\x10\x13\x12\"\n" +
	"\x1eFREEFORM_PROMPT_INVALID_LENGTH\x10\x14\x12'\n" +
	"#FREEFORM_PROMPT_REFERENCES_CHILDREN\x10\x15\x12.\n" +
	"*FREEFORM_PROMPT_REFERENCES_SPECIFIC_PEOPLE\x10\x16\x12'\n" +
	"#FREEFORM_PROMPT_VIOLATES_ADS_POLICY\x10\x17\x12!\n" +
	"\x1dFREEFORM_PROMPT_BRAND_CONTENT\x10\x18\x12 \n" +
	"\x1cINPUT_IMAGE_DEPICTS_CHILDREN\x10\x19\x12&\n" +
	"\"INPUT_IMAGE_CONTAINS_BRAND_CONTENT\x10\x1a\x12\x19\n" +
	"\x15INPUT_IMAGE_SENSITIVE\x10\x1b\x12\x1f\n" +
	"\x1bINPUT_IMAGE_VIOLATES_POLICY\x10\x1c\x125\n" +
	"1ALL_OUTPUT_IMAGES_FILTERED_OUT_CHILDREN_DEPICTION\x10\x1d\x122\n" +
	".ALL_OUTPUT_IMAGES_FILTERED_OUT_SPECIFIC_PEOPLE\x10\x1e\x12\"\n" +
	"\x1eALL_OUTPUT_IMAGES_FILTERED_OUT\x10\x1f\x12\x18\n" +
	"\x14INPUT_IMAGE_REQUIRED\x10 \x12&\n" +
	"\"INPUT_IMAGE_UNSUPPORTED_IMAGE_TYPE\x10!\x12!\n" +
	"\x1dCONTEXT_ASSET_GROUP_NOT_FOUND\x10\"\x12!\n" +
	"\x1dCONTEXT_AD_GROUP_AD_NOT_FOUND\x10#\x12\x1e\n" +
	"\x1aCONTEXT_CAMPAIGN_NOT_FOUND\x10$B\xf9\x01\n" +
	"#com.google.ads.googleads.v22.errorsB\x19AssetGenerationErrorProtoP\x01ZEgithub.com/Optable/google-ads-pb/protogen/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V22.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V22\\Errors\xea\x02#Google::Ads::GoogleAds::V22::Errorsb\x06proto3"

var (
	file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDesc), len(file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDescData
}

var file_google_ads_googleads_v22_errors_asset_generation_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_errors_asset_generation_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_errors_asset_generation_error_proto_goTypes = []any{
	(AssetGenerationErrorEnum_AssetGenerationError)(0), // 0: google.ads.googleads.v22.errors.AssetGenerationErrorEnum.AssetGenerationError
	(*AssetGenerationErrorEnum)(nil),                   // 1: google.ads.googleads.v22.errors.AssetGenerationErrorEnum
}
var file_google_ads_googleads_v22_errors_asset_generation_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_errors_asset_generation_error_proto_init() }
func file_google_ads_googleads_v22_errors_asset_generation_error_proto_init() {
	if File_google_ads_googleads_v22_errors_asset_generation_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDesc), len(file_google_ads_googleads_v22_errors_asset_generation_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_errors_asset_generation_error_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_errors_asset_generation_error_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_errors_asset_generation_error_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_errors_asset_generation_error_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_errors_asset_generation_error_proto = out.File
	file_google_ads_googleads_v22_errors_asset_generation_error_proto_goTypes = nil
	file_google_ads_googleads_v22_errors_asset_generation_error_proto_depIdxs = nil
}
