// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.1
// source: google/ads/googleads/v22/errors/campaign_goal_config_error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing possible campaign goal config errors.
type CampaignGoalConfigErrorEnum_CampaignGoalConfigError int32

const (
	// Enum unspecified.
	CampaignGoalConfigErrorEnum_UNSPECIFIED CampaignGoalConfigErrorEnum_CampaignGoalConfigError = 0
	// The received error code is not known in this version.
	CampaignGoalConfigErrorEnum_UNKNOWN CampaignGoalConfigErrorEnum_CampaignGoalConfigError = 1
	// Goal is either removed or does not exist for this account.
	CampaignGoalConfigErrorEnum_GOAL_NOT_FOUND CampaignGoalConfigErrorEnum_CampaignGoalConfigError = 3
	// Campaign is either removed or does not exist.
	CampaignGoalConfigErrorEnum_CAMPAIGN_NOT_FOUND CampaignGoalConfigErrorEnum_CampaignGoalConfigError = 4
	// If high lifetime value is present then value should be present.
	CampaignGoalConfigErrorEnum_HIGH_LIFETIME_VALUE_PRESENT_BUT_VALUE_ABSENT CampaignGoalConfigErrorEnum_CampaignGoalConfigError = 9
	// High lifetime value should be greater than value.
	CampaignGoalConfigErrorEnum_HIGH_LIFETIME_VALUE_LESS_THAN_OR_EQUAL_TO_VALUE CampaignGoalConfigErrorEnum_CampaignGoalConfigError = 10
	// When using customer lifecycle optimization goal, campaign type should be
	// supported.
	CampaignGoalConfigErrorEnum_CUSTOMER_LIFECYCLE_OPTIMIZATION_CAMPAIGN_TYPE_NOT_SUPPORTED CampaignGoalConfigErrorEnum_CampaignGoalConfigError = 11
	// Customer must be allowlisted to use retention only goal.
	CampaignGoalConfigErrorEnum_CUSTOMER_NOT_ALLOWLISTED_FOR_RETENTION_ONLY CampaignGoalConfigErrorEnum_CampaignGoalConfigError = 12
)

// Enum value maps for CampaignGoalConfigErrorEnum_CampaignGoalConfigError.
var (
	CampaignGoalConfigErrorEnum_CampaignGoalConfigError_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "UNKNOWN",
		3:  "GOAL_NOT_FOUND",
		4:  "CAMPAIGN_NOT_FOUND",
		9:  "HIGH_LIFETIME_VALUE_PRESENT_BUT_VALUE_ABSENT",
		10: "HIGH_LIFETIME_VALUE_LESS_THAN_OR_EQUAL_TO_VALUE",
		11: "CUSTOMER_LIFECYCLE_OPTIMIZATION_CAMPAIGN_TYPE_NOT_SUPPORTED",
		12: "CUSTOMER_NOT_ALLOWLISTED_FOR_RETENTION_ONLY",
	}
	CampaignGoalConfigErrorEnum_CampaignGoalConfigError_value = map[string]int32{
		"UNSPECIFIED":        0,
		"UNKNOWN":            1,
		"GOAL_NOT_FOUND":     3,
		"CAMPAIGN_NOT_FOUND": 4,
		"HIGH_LIFETIME_VALUE_PRESENT_BUT_VALUE_ABSENT":                9,
		"HIGH_LIFETIME_VALUE_LESS_THAN_OR_EQUAL_TO_VALUE":             10,
		"CUSTOMER_LIFECYCLE_OPTIMIZATION_CAMPAIGN_TYPE_NOT_SUPPORTED": 11,
		"CUSTOMER_NOT_ALLOWLISTED_FOR_RETENTION_ONLY":                 12,
	}
)

func (x CampaignGoalConfigErrorEnum_CampaignGoalConfigError) Enum() *CampaignGoalConfigErrorEnum_CampaignGoalConfigError {
	p := new(CampaignGoalConfigErrorEnum_CampaignGoalConfigError)
	*p = x
	return p
}

func (x CampaignGoalConfigErrorEnum_CampaignGoalConfigError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CampaignGoalConfigErrorEnum_CampaignGoalConfigError) Descriptor() protoreflect.EnumDescriptor {
	return file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_enumTypes[0].Descriptor()
}

func (CampaignGoalConfigErrorEnum_CampaignGoalConfigError) Type() protoreflect.EnumType {
	return &file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_enumTypes[0]
}

func (x CampaignGoalConfigErrorEnum_CampaignGoalConfigError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CampaignGoalConfigErrorEnum_CampaignGoalConfigError.Descriptor instead.
func (CampaignGoalConfigErrorEnum_CampaignGoalConfigError) EnumDescriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDescGZIP(), []int{0, 0}
}

// Container for enum describing possible campaign goal config errors.
type CampaignGoalConfigErrorEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignGoalConfigErrorEnum) Reset() {
	*x = CampaignGoalConfigErrorEnum{}
	mi := &file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignGoalConfigErrorEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignGoalConfigErrorEnum) ProtoMessage() {}

func (x *CampaignGoalConfigErrorEnum) ProtoReflect() protoreflect.Message {
	mi := &file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignGoalConfigErrorEnum.ProtoReflect.Descriptor instead.
func (*CampaignGoalConfigErrorEnum) Descriptor() ([]byte, []int) {
	return file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDescGZIP(), []int{0}
}

var File_google_ads_googleads_v22_errors_campaign_goal_config_error_proto protoreflect.FileDescriptor

const file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDesc = "" +
	"\n" +
	"@google/ads/googleads/v22/errors/campaign_goal_config_error.proto\x12\x1fgoogle.ads.googleads.v22.errors\"\xdc\x02\n" +
	"\x1bCampaignGoalConfigErrorEnum\"\xbc\x02\n" +
	"\x17CampaignGoalConfigError\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aUNKNOWN\x10\x01\x12\x12\n" +
	"\x0eGOAL_NOT_FOUND\x10\x03\x12\x16\n" +
	"\x12CAMPAIGN_NOT_FOUND\x10\x04\x120\n" +
	",HIGH_LIFETIME_VALUE_PRESENT_BUT_VALUE_ABSENT\x10\t\x123\n" +
	"/HIGH_LIFETIME_VALUE_LESS_THAN_OR_EQUAL_TO_VALUE\x10\n" +
	"\x12?\n" +
	";CUSTOMER_LIFECYCLE_OPTIMIZATION_CAMPAIGN_TYPE_NOT_SUPPORTED\x10\v\x12/\n" +
	"+CUSTOMER_NOT_ALLOWLISTED_FOR_RETENTION_ONLY\x10\fB\xfc\x01\n" +
	"#com.google.ads.googleads.v22.errorsB\x1cCampaignGoalConfigErrorProtoP\x01ZEgithub.com/Optable/google-ads-pb/protogen/errors;errors\xa2\x02\x03GAA\xaa\x02\x1fGoogle.Ads.GoogleAds.V22.Errors\xca\x02\x1fGoogle\\Ads\\GoogleAds\\V22\\Errors\xea\x02#Google::Ads::GoogleAds::V22::Errorsb\x06proto3"

var (
	file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDescOnce sync.Once
	file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDescData []byte
)

func file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDescGZIP() []byte {
	file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDescOnce.Do(func() {
		file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDesc), len(file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDesc)))
	})
	return file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDescData
}

var file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_goTypes = []any{
	(CampaignGoalConfigErrorEnum_CampaignGoalConfigError)(0), // 0: google.ads.googleads.v22.errors.CampaignGoalConfigErrorEnum.CampaignGoalConfigError
	(*CampaignGoalConfigErrorEnum)(nil),                      // 1: google.ads.googleads.v22.errors.CampaignGoalConfigErrorEnum
}
var file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_init() }
func file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_init() {
	if File_google_ads_googleads_v22_errors_campaign_goal_config_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDesc), len(file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_goTypes,
		DependencyIndexes: file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_depIdxs,
		EnumInfos:         file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_enumTypes,
		MessageInfos:      file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_msgTypes,
	}.Build()
	File_google_ads_googleads_v22_errors_campaign_goal_config_error_proto = out.File
	file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_goTypes = nil
	file_google_ads_googleads_v22_errors_campaign_goal_config_error_proto_depIdxs = nil
}
